### ISSUE TITLE
Add "simple" numeric conversions

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1059]
Flix is currently missing conversion functions between its number types.

In the first instance I think we should have conversions based on `java.lang.Number`. At some point it would be nice to have the "math" style conversions like `ceil` and `floor` but these can come later (maybe they merit being in a separate module / namespace etc.).

**Comment by stephentetley** [comment]
From Gitter:

> @magnus How are we going to handle narrowing that might lose precision? Will we return an option?

Good question.

Is an "asymmetric" API acceptable here?

i.e. All widening conversions return the result directly, all narrowing conversions wrap the answer in an option.

For Int32 the conversions to Int8 and Int16 is narrowing, the others are widening.
~~~

pub def toInt8(x: Int32): Option[Int8] =

pub def toInt16(x: Int32): Option[Int16] =

pub def toInt64(x: Int32): Int64 =

pub def toBigInt(x: Int32): BigInt =

pub def toFloat32(x: Int32): Float32 =

pub def toFloat64(x: Int32): Float64 =

~~~

It would be a pity to wrap widening conversions just to have a uniform API.

**Comment by magnus-madsen** [comment]
> It would be a pity to wrap widening conversions just to have a uniform API.

Yes. Let us not do that.

As for the whole API design, I am not sure what is best. I want to look at Rust, I believe they tried to address problem in a principled way. 

I don't know too much about machine numbers. Is it true that an `Int32` can be converted to a `float32` without loss of precision?

**Comment by Herbstein** [comment]
> As for the whole API design, I am not sure what is best. I want to look at Rust, I believe they tried to address problem in a principled way.

This is partially true. Using the `as` keyword it's possible to do `i32` -> `i8` conversions that silently round down. 

Rust also has the traits `From` and `TryFrom` that have the respective functions `from :: a -> b` and `try_from :: a -> Option[b]`. 

My impression is that the vast majority of Rust programmers just do casts with `as`. One indication of this is that Clippy, the official Rust linter, [doesn't have a lint that encourages people to use the newer trait](https://rust-lang.github.io/rust-clippy/master/) (that I can find or have seen).

It's also worth mentioning that the traits are later additions to that language that were stabilized around a year ago.

[This excellent StackOverflow answer gives a bit more detail.](https://stackoverflow.com/a/28280042/3350284)

> I don't know too much about machine numbers. Is it true that an `Int32` can be converted to a `Float32` without loss of precision?

The mantissa of 32-bit floating points is 23 bits. As such any integer below `2^23` is representable without losing precision. 64-bit floating point numbers have a mantissa of 53 bits. So `Int32` -> `Float32` isn't lossless, while `Int32` -> `Float64` is. 

I'm not sure how to show the loss of precision in the API, however. Because even in the `Int32` -> `Float32` there isn't really a failure condition, so returning `Option` or `Result` doesn't make too much sense in my opinion. Maybe you could encode the conversion in an enum with `Lossless` and `Lossy` variants? But that could also become a more cumbersome API.

**Comment by Herbstein** [comment]
One last observation: converting from floating points to integers only through `ceil` and `floor` functions seems like a very nice API that can also do bounds checking.

**Comment by stephentetley** [comment]
I didn't know much about machine numbers either until I looked yesterday... :)

int32 to float32 is a "widening" conversion

The "overall magnitude" of the number will (should?) be preserved but it may lose precision.

https://docs.oracle.com/javase/specs/jls/se13/html/jls-5.html#jls-5.1.2

The principle I'm now following after working on it for a day is: we don't track loss of precision but we do use Option to track representability.

Some examples:

* Int8 to Int64

No loss of representation any number that's in the Int8 range has a corresponding number in the Int64 range. No need for Option.

* Int64 to Int8

Most of the Int64 range is not representable in the Int8 range. Use an Option.

* Int32 to Float32

Any number in the Int32 range can be represented, however there is noticable imprecision near Int32.maxValue() and Int32.minValue().

Don't use Option. Magnitude is correct but there is imprecision. If a user wants the value they need to be able to get it, though they should really be using Double...

* Int32 to Float64

Any number in the Int32 range can be represented, I haven't seen imprecision near Int32.maxValue() and Int32.minValue() with some testing.

Don't use Option. Specification says the numeric value is preserved exactly.


* Float32 to Int32

Float32 has a greater range than can be represented by Int32, it also has NaN +Inf and -Inf. Use an Option.

* Float32 to Int64

Float32 has a greater range than can be represented by Int64, it also has NaN +Inf and -Inf. Use an Option.

* Float64 to Int32

Float64 has a much greater range than can be represented by Int32, it also has NaN +Inf and -Inf. Use an Option.

* Float64 to Int64

Float64 has a much greater range than can be represented by Int64, it also has NaN +Inf and -Inf. Use an Option.

 * BigInt to anything
  
BigInt has a much greater range than can be represented by any of the other types. Use an Option.

**Comment by magnus-madsen** [comment]
I think this is a great discussion. I want to add two comments:

- Currently `Int` is an alias for `Int32`, but I am seriously considering if it should have been an alias for `BigInt`. I think languages like Racket (?) and Haskell got it right when they made the arbitrary precision arithmetic the default. It is hard to see why a "modern" programming language would default to 32-bit integers- especially when processors are already 64 bit! 
- If the above is accomplished, I would like to have the ability to annotate the int type with optional ranges, e.g. `age: Int[0; 100]`. In the research literature these are called refinement types and can be checked statically. But in practice I am skeptical this can work. Instead, I propose that such ranges are just checked at run-time.

**Comment by stephentetley** [comment]
I've created a pull request:

Add numeric conversions #1063

**Comment by magnus-madsen** [comment]
In Rust they seem to support four types of operations on ints:

- checked_add (returns an Option)
- overflow_add (returns a pair of the number and a boolean that indicates if it overflowed)
- saturating_add (instead of overflowing goes to the maximum value supported by the type)
- wrapping_add (overflows - as we know it)

All the above operations are defined on the _same type_. I can't decide if that is smart or burdensome. It means that if you want to do e.g. saturating arithmetic you have to write very verbose code. Why did they not define four integer types (e.g. `CheckedInt32`, `OverflowingInt32`, `SaturatingInt32`, `ModularInt32` or the like) and then simply overload +?

I have not yet figured out how they handle widening and narrowing. 

I read that Swift has also made some interesting design choices in this space, so I will look into that too.

**Comment by magnus-madsen** [comment]
(Accidentally hit the wrong button)

**Comment by magnus-madsen** [comment]
Swift provides:

- Overflow addition (&+)
- Overflow subtraction (&-)
- Overflow multiplication (&*)

It looks like they also have a design with some elements like Rust. By default integers cannot overflow (causes exception). But then the above operators can be used. They also have `Int8.addWithOverflow` which corresponds to Rust's `overflow_add`.

**Comment by stephentetley** [comment]
Oh no, overflow on addition (or subtraction, multiplication...) is another can of worms. Though, closely related of course. 

The JVM might make things that are feasible in Rust or Swift difficult for Flix (or Scala etc.).

**Comment by Herbstein** [comment]
> Why did they not define four integer types [..] and then simply overload +?

I think this partially comes down to personal preference, but the more verbose methods allows you to do all types of addition on the same value. For some operations that is useful.

Since Rust is developed in the open I started looking for some of the discussions, but they seem to have happened in a now-defunct discussion board that Internet Archive hasn't taken snapshots of.

> I have not yet figured out how they handle widening and narrowing.

Rust uses the `From` trait. E.g. `u16` implements `From<u8>` but not vice versa. This gives an automatic implementation of `Into<u16` for `u8`. `let n: u16 = 0x42_u8.into()` is an example of how you can do widening.

For narrowing they use the `TryFrom` trait I mentioned in my previous reply. It does exactly what Stephen implemented, it's just encoded into a trait.

Also of note is that `wrapping_add` is the default behavior of `+` for the integer types, and that the overflow checks are only present in debug builds.

**Comment by magnus-madsen** [comment]
Do we consider the original issue of numeric conversions to be solved?

**Comment by stephentetley** [comment]
I think so, yes.
