### ISSUE TITLE
Float32.toDecimalString and Float64.toDecimalString Test Fails Locally

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1086]
I noticed that some of the test cases for Float32.toDecimalString and Float64.toDecimalString fail locally, but they did not fail on travis (??). Maybe again Java version issues?

**Comment by stephentetley** [comment]
I will investigate this.

It could be something to do with the locale of the machine has affects the formatting, although I thought the tests were so simplistic that it wouldn't matter.

**Comment by magnus-madsen** [comment]
> 
> 
> I will investigate this.
> 
> It could be something to do with the locale of the machine affects the formatting, although I thought the tests were so simplistic that it wouldn't matter.

That would make sense. I am on a danish locale and we use , and . for different things.

**Comment by stephentetley** [comment]
Hi Magnus, I think the problem is due to different decimal formats from different JVM locales rather than Java versions.

I'd be happy enough to have this function removed for the time being. Maybe the `Float32` and `Float64` modules are the wrong place for it - Java has number formatting in the `java.text.*` namespace (`java.text.NumberFormat` and `java.text.DecimalFormat`).

If it's worth keeping then I suggest adding `fromDecimalString` which reads a decimal string written with the same decimal formatting taken from the JVM's locale. If we have both functions we can round trip between them.

From experiments I ran, the current `fromString` in Float64 can only read very simple decimal strings. Once any formatting has been inserted it fails. So we can't roundtrip with it and `toDecimalString`.

I have implemented `fromDecimalString` on the branch here:

https://github.com/stephentetley/flix/tree/decimal-string

**Comment by magnus-madsen** [comment]
Hmmm.

Is there no internationally accepted number format? Or is that the engineering format that we find hard to read?

**Comment by stephentetley** [comment]
I think "E notation" is as close as there is to a common standard format, but that's what I was wanting to provide an alternative to: 

https://en.wikipedia.org/wiki/Scientific_notation#E_notation

I've definitely moved towards thinking `toDecimalString` should be somewhere else rather than in Float32 / Float64. Java's standard libraries have a lot of nice support for formatting but we would probably have to expose at least Locale in an API.

**Comment by magnus-madsen** [comment]
OK; sounds good. Let us remove it then.

**Comment by magnus-madsen** [comment]
Did we actually remove them?
