### ISSUE TITLE
Build system and dependency management

### ISSUE THREAD

**Issue by Dmunch04** [flix/flix#1178]
Hi! I saw this language, and was wondering if it was in need of a build system together with a package manager? If so, I would like to Work om that.

**Comment by magnus-madsen** [comment]
Hello! and welcome :)

Yes, we need a build system. Some preliminary work has already been done, but most of the work remains to be done.

We are planning to write the build system in Flix itself and then link it with the Scala code.

What parts of the build system are you interested in working on?

**Comment by Dmunch04** [comment]
Oh I see. Would you mind sending me a link to where I can find the current progress?

**Comment by mlutze** [comment]
These two PRs contain work on package management: https://github.com/flix/flix/pull/941, https://github.com/flix/flix/pull/1115

**Comment by Herbstein** [comment]
While it's true that #941 points to a branch where work was done, some more work is present on another branch. The [`init_build_jar`](https://github.com/Herbstein/flix/tree/init_build_jar) branch has a tiny bit of work on a minimal interface to the compiler - though it's not pretty. That is the branch #1115 points to.

A bunch of work has also been put into a parser for the TOML configuration language in #1123 and the [`toml_parser_combinator` branch](https://github.com/Herbstein/flix/tree/toml_parser_combinator).

A not-quite-SemVer datatype and implementation has already been merged. The only real limitation for not yet having a full-spec SemVer (Sematic Versioning) type is parsing it from a string. Everything else is fairly easy to implement. Most dependency managers use a modified version of SemVer that is range-based. Implementing that would be a lot harder - especially when it comes to dependency resolution. The CocoaPods developers created the [Molinillo dependency resolution algorithm](https://github.com/CocoaPods/Molinillo) that might be interesting to port. It's also used in the Ruby Bundler project as far as I'm aware.

For the spec-compliant SemVer (non-range-based) I have a [very small algorithm that does dependency resolution](https://github.com/Herbstein/flix/blob/old_master/main/src/library/pkger/Manifest.flix#L70). It still needs some work with deduplication, and crashes if no matching package is found, but both of those shouldn't be too hard to add on top. Specifically, `lockPackageHelper` would have to return `Option[DependencyTree]` instead of simply `DependencyTree`. And then appropriate changes of course need to be made to accomodate this.

That's a quick overview of some of the work. Reach out if you need to!

**Comment by Dmunch04** [comment]
Thank you! Both of you. Although if you don't mind, I would like to first experiment with this in a separate repo. I wanna make the package system Git-based (decentralized). And does Flix have any HTTP server/client lib yet?

**Comment by Herbstein** [comment]
Flix doesn't really have anything related to network connectivity at all. In #1076 I implemented, among other things, support for working with IOStreams from Java. But there's no URL handling, low-level TCP functionality, or higher-level HTTP client/server stuff. Most of that can be pulled in from [the Java standard library via interop](https://flix.dev/programming-flix/#/interoperability/).

**Comment by magnus-madsen** [comment]
> Thank you! Both of you. Although if you don't mind, I would like to first experiment with this in a separate repo. I wanna make the package system Git-based (decentralized). And does Flix have any HTTP server/client lib yet?

I think we are still very much in the early stages, so experimentation is completely fine and warranted.

**Comment by Dmunch04** [comment]
Would the best option to get HTTP libs be to just use Java libs? And "wrap" them, so they can be used in Flix.

**Comment by magnus-madsen** [comment]
Yes, writing a wrapper around the appropriate network utilities would be a reasonable start.

I think Java recently got a new HTTP api?

**Comment by magnus-madsen** [comment]
We now have a nascent package manager. What is missing is dependency resolution.
