### ISSUE TITLE
User-defined annotations

### ISSUE THREAD

**Issue by mlutze** [flix/flix#1182]
Currently we have a fixed set of annotations that are processed by the compiler. Especially when macros come, allowing users to define their own annotations could be very useful.

Example:

```flix
annotation LogCalls

@LogCalls
def getRecipe(id: Int64): Recipe = ...

// (Then a macro or something modifies the function to write to a log every time the function is called)
```

**Comment by magnus-madsen** [comment]
Agreed. And I think annotations need to take pure expression arguments too.

**Comment by mlutze** [comment]
Would expression arguments need to be proven to terminate? Or I guess they could be passed by name.

**Comment by magnus-madsen** [comment]
> 
> 
> Would expression arguments need to be proven to terminate? Or I guess they could be passed by name.

Yeah, they would not be evaluated.

**Comment by magnus-madsen** [comment]
I think it would be nice to allow arguments (expressions) to annotations. For example:

```
    @Time(1) @Space(1)
    pub def isEmpty(xs: List[a]): Bool = match xs {
        case Nil => true
        case _ => false
    }

    @Time(time(f) * length(xs)) @Space(space(f) * length(xs))
    pub def map(f: a -> b & e, xs: List[a]): List[b] & e = match xs {
        case Nil => Nil
        case x :: rs => f(x) :: map(f, rs)
    }
```

Notice how the variables of `map` are in scope of the annotations (!).

Such expressions are naturally type checked and so forth.  A question is whether they must be pure?

The #1185 PR allows a preliminary version of this. (It only parses such expressions.)

Now, as for user-defined annotations (that the compiler does not know about), I wonder if we should somehow reuse types as annotations. (In Java an annotation is a kind of interface).

For example:

```
enum Color {
  case Red,
  case Green,
  case RGB({red: Int, green: Int, blue: Int})
}
```

and then you could write something like that:

```
@Blue
def foo(): Int = 123
```

or even:

```
@RGB({red = 123, blue = 0, green = 255})
def foo(): Int = 123
```

Note how the argument passed to `RGB` neatly fits with the type of the tag.

Now, this does not answer the question of whether *every* tag can be used as an annotation nor whether an annotation can be presented multiple times:

```
@Blue @Green
def foo(): Int = 123
```

**Comment by magnus-madsen** [comment]
Maybe reusing the type name is a bad idea. We could introduce one level of indirection and have:

```
annotation MyAnnotation(Color)
```

or some such. (I dislike the syntax).

**Comment by magnus-madsen** [comment]
@mlutze What do you think about this (stark) opinion:

Built-in annotations are good because they have clear semantics (e.g. `LazyWhenPure` and `Deprecated`). We should support a minimal set of such annotations. User-defined annotations, on the other hand, are horribly because they are a (very) poor mans form of meta documentation (and sometimes meta-programming). Can we really say that annotations made Java better? I think it lead to meta-programming reflective hell and a lot of awkward frameworks. Moreover, if annotation *is* useful then it must be part of the language. Consider `@NonNull` it was standardize too late (or never?) consequence there at at least 5 different `@NonNull`  annotations. 

In sum, lets ban user-defined annotations and focus on a few built-in annotations (almost quasi-keywords). 

We can formulate this as a principle.

**Comment by mlutze** [comment]
I'm having trouble giving up the dream, as I have visions of putting a nice `@memo` annotation on a function to memoize it.

But I think your points are convincing. When we get to the point where we have hygienic macros, etc. we can revisit the question.

**Comment by magnus-madsen** [comment]
Even memo is difficult because when do you want to garbage collect it? Or do you plan to keep it for all eternity?

**Comment by magnus-madsen** [comment]
Until there is a better use case, we will not have user-defined annotations.
