### ISSUE TITLE
Update Unconditional Recursion Check

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1198]
The PR #1197 changes the internal representation of curried and uncurried functions. Before every function was curried, but now the strategy is a bit richer, so top-level definitions are never curried, and instead we introduce some extra lambdas when needed. 

This requires a slightly different approach to the recursion check in `Redundancy`, but I am not yet sure entirely how to do it.

**Comment by magnus-madsen** [comment]
@mlutze Maybe you could offer some pointers?

The essence is that now we can have an `Apply` node with `n` args. I tried to account for this by changing `incApply` to take a number, but there are still some tests that fail. 

Maybe it is just this check I need to change?

```
      override def isRecursiveCall(call: Symbol.DefnSym): Boolean = {
        defn == call && arity == 0
      }
```

**Comment by mlutze** [comment]
I don't see any obvious errors. I'm wondering if somehow we have an off-by-one error since we were previously incrementing by 1 but now we're skipping some numbers. I'll take a closer look this evening.

**Comment by mlutze** [comment]
I found a couple problems, both issues with my implementation :(

1. We're not properly finding the arity from a type scheme. I believe the `arity` function should instead be
```scala
  /**
    * Finds the arity of the function represented by the given Type.
    */
  @tailrec
  private def arity(tpe: Type, acc: Int = 0): Int = tpe.typeConstructor match {
    // Arity of the function represented by an Arrow is:
    // * 1 less than the Arrow type arity (because Arrow type includes return type)
    // * plus arity of the return type (because Arrow is right-associative: a -> (b -> c) == a -> b -> c)
    case Type.Arrow(arity0, _) => arity(tpe.typeArguments.last, acc + arity0 - 1)
    case _ => acc
  }
```

2. We're not handling lambdas properly. When we encounter a lambda in the tree, we should decrement the apply counter since we add an abstraction. For example:
```
(y -> f(x))(a) == f(x)
// 2 applies, 1 lambda == 1 apply
```
This gets especially tricky to handle since lambdas at the top level of the expression form part of the type scheme. Example:
```
def f(x): Int -> Int = y -> 123
```
The top-level lambda is counted twice here: once when looking at the type scheme to get the arity, and once when looking at the expression to check for redundancy.

The simple solution to this is to use the count of formal params, rather than the type scheme, to find the arity of a function. I recall from discussion that we thought that this would not be very robust. (Note that if we go with this solution, error 1 above doesn't matter).

**Comment by magnus-madsen** [comment]
> The simple solution to this is to use the count of formal params, rather than the type scheme, to find the arity of a function. I recall from discussion that we thought that this would not be very robust. (Note that if we go with this solution, error 1 above doesn't matter).

In #1197 I make the internal representation of functions match the external syntax. E.g.

```
def f(x: Int, y: Int): Int = f(1, 2)
```

Actually has two formal parameters. How about we simplify and try to just catch such cases?


If you write:

```
def f(x: Int, y: Int): Int = f(1)(2)
```

the compiler expands this to:

```
def f(x: Int, y: Int): Int = (v -> u -> f(x, u))(1)(2)
```

😮 

which is probably too impractical and brittle to analyze for infinite recursive calls.

**Comment by magnus-madsen** [comment]
I merged in the PR. Do you want to take a look at simplifying the checker? :)

**Comment by mlutze** [comment]
For clarification, after simplification,

This throws an error:
```
def f(x: Int, y: Int): Int = f(1, 2)
```
And this passes:
```
def f(x: Int, y: Int): Int = f(1)(2)
```
Is that right?

I think we might lose significant value by loosening restrictions, especially since the second case is more likely to be missed by a human than the first IMO.

That said, I agree there's a lot of complexity in the apply counting and such, particularly since that needs to be handled among all of the other redundancy checking.

**Comment by magnus-madsen** [comment]
> 
> 
> For clarification, after simplification,
> 
> This throws an error:
> 
> ```
> def f(x: Int, y: Int): Int = f(1, 2)
> ```
> 
> And this passes:
> 
> ```
> def f(x: Int, y: Int): Int = f(1)(2)
> ```
> 
> Is that right?

Yes

> I think we might lose significant value by loosening restrictions, especially since the second case is more likely to be missed by a human than the first IMO.
> 
> That said, I agree there's a lot of complexity in the apply counting and such, particularly since that needs to be handled among all of the other redundancy checking.

I can see that. Still, there are also many other cases where we do not catch the problem, so maybe the simplification is alright.

**Comment by magnus-madsen** [comment]
Fixed in master.
