### ISSUE TITLE
What is the semantics of top-level definitions: Expressions vs. Lambdas.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#130]
What is the difference between:

```
def f(x: Int): Int = x
def f: Int -> Int = x -> x
```

**Comment by magnus-madsen** [comment]
@mhyee I would like to sit down and try to resolve this issue together. I think we agreed at some point (or maybe I just agreed with myself??) that we need to allow nullary functions to be invoked like so:

```
def f: Int = 42
def g: Int = f()

rel A(x: Int)
A(f())
```

At least, for the time being, this seems to be the most clean fix.

**Comment by mhyee** [comment]
Yes, the problem was that we need a way to distinguish constants from variables in the head of a rule. The simplest and cleanest solution is to allow zero-arg functions.

Of course, this reverses our earlier decision, and will probably affect a lot of other things. We definitely need to think about this very carefully, and see how it interacts with rules, pattern matching, lambdas, and probably other things I'm missing right now.

**Comment by magnus-madsen** [comment]
This was surprisingly easy to fix. I simply allow you to write `f()` in expressions and terms. The I had to change the signature of `def f: Int = 42` to be a function from `() -> Int` and things seems to work.

**Comment by magnus-madsen** [comment]
I added some test case. This program, for example:

```
rel A(x: Int, y: Int, z: Int);

def f: Int = 42
def g: Int = 21
def h: Int = f() + g()

A(f(), g(), h()).
```

which now works.

I wonder if there are any simplifications that can be done to the backend now that every definition is a constant? Otherwise, I would like to close the ticket, and then we can open new tickets, if there are specific issues.

**Comment by mhyee** [comment]
I'd like to think about this a little more before closing the issue. I'll try to post some comments tonight, since I'm working on something else right now.

**Comment by mhyee** [comment]
So to summarize:

Defined constants are actually functions that take nothing and return a constant value. They are declared without parentheses. These functions are called with parentheses.

We can now refer to constants from the head of a rule, because we're calling a function and not referring to some variable bound by the body of the rule.

Looking at the example from before:

```
def f(x: Int): Int = x     // f(42) returns 42
def f: Int -> Int = x -> x // f() returns a lambda, so f()(42) returns 42
```
We can't write lambdas yet, but now there's an actual difference between the two functions.

For pattern matches, we end up generating error functions:

```
def err: Int = MatchError // throws an error
```

There were some modifications to only evaluate constants when they were asked for, to avoid pattern matches from throwing immediately. I suppose we could remove that code now, since constants are now functions?

The code generator also had some extra code to handle the old constants. They were wrapped into functions, but that's done by the typer now. So there's some dead code that can be removed, but leaving it alone for now shouldn't hurt.

---

**Final comments and action items**

I think these changes will be fine. We've already gone through the headache of discovering the issues, and the change seems to work well and fix those issues.

I'd like to see one more test added. Something like:

```
def x: Int = 42

rel A(x: Int, y: Int)
rel B(x: Int)

A(x(), x) :- B(x).
B(100).
```

Also, some questions:

```
def f: Int = 5     // OK before, still OK
def g(): Int = 5   // ???

def w: Int = f     // ???
def x: Int = f()   // OK now
def y: Int = g     // ???
def z: Int = g()   // ???
```

**Comment by magnus-madsen** [comment]
I added your test case, and this more devious one:

```
    val s =
      """rel A(x: Int, y: Int, z: Int)
        |rel B(x: Int)
        |
        |def x(x: Int): Int = x + 1
        |
        |A(x(x(x)), x(x), x) :- B(x).
        |B(21).
      """.stripMargin
```

As for the questions, I think that will have to wait until we have to type system sorted out. That should help clarify things.

**Comment by magnus-madsen** [comment]
I think we have finally figured this out by separation of vals and defs. See #507 where the work continues.
