### ISSUE TITLE
Here's my issue

### ISSUE THREAD

**Issue by h2o7** [flix/flix#1370]
Can we just stop with building new programming languages?

**Comment by magnus-madsen** [comment]
The original question was:

> Can we just stop with building new programming languages?

The FAQ contains an approximate answer to this question:

> Flix aims to offer a combination of features that are not found in any existing programming language. You may also want to explore the innovations.

We build new programming languages and we do research on programming languages because we want to offer developers better tools to write programs. We want tools that make it simpler, safer, and faster to write correct programs. We want tools that increase productivity and that aid in program maintenance. And so forth.

The situation is not unlike why we would want better airplanes or better cars or better surgical instruments.
