### ISSUE TITLE
Add Source Locations to Type

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1423]
We should add source locations to Type such that we can rename type variables and enums etc.

**Comment by magnus-madsen** [comment]
@mlutze 

I want to add locations such that we can have e.g.:

![image](https://user-images.githubusercontent.com/2287953/97807333-7593f100-1c60-11eb-8177-2e3383acbd1a.png)

And you can actually click/hover on "Color" to see its definition.

Now, my question is, should we add source locations to `Type` or to `TypeConstructor` or to both?

**Comment by mlutze** [comment]
I think we should only add it to `Type`.

If we only add location to `TypeConstructor`, then it won't be present for `Type.Apply`s and `Type.Var`s, which I think would be useful.

Since any `TypeConstructor`'s location should be identical to the surrounding `Type.Cst(...)`, I think it would be redundant to include it in `TypeConstructor`.

**Comment by magnus-madsen** [comment]
We are in the process.  I think we just need it for type variables.
