### ISSUE TITLE
The use of ??? should not disable variable shadowing check

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1541]
Right now, if a function contains an `???` then we remove all redundancy warnings inside that function.

**Comment by jacopol** [comment]
More precisely, I would like to type check and test partial code with ??? holes (for instance, if some cases are still missing, I want to run and test the missing cases). So when should the flix-compiler complain? It should complain if there is no way to fill the ??? correctly. In particular, it should complain if the code is already shadowing some variables, since that cannot be repaired by filling in ???. However, it should not complain if some variables are missing (i.e. redundant), since this can be repaired by filling in the ???.
Example:

`f(x,y) = match x { case Nil => ??? ; case x::xs => f(xs,xs) }`

Here `x` is shadowed (in the second pattern) and this is an error that should be reported.
Also `y` is redundant, but this should not be reported, since the ??? might use `y`.

The solution seems to be that ??? are declared to use all variables in scope.
