### ISSUE TITLE
Type Classes: Add Order Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1560]
- [ ] Add definition of `Order` class.
- [ ] Add instance for `Unit`.
- [ ] Add instance for `Bool` (?)
- [ ] Add instance for `Char`.
- [ ] Add instance for `Int8`.
- [ ] Add instance for `Int16`.
- [ ] Add instance for `Int32`.
- [ ] Add instance for `Int64`.
- [ ] Add instance for `BigInt`
- [ ] Add instance for `String`.
- [ ] Add instances for tuples from N=2 to N=10.
- [ ] Ensure that instances are declared in a consistent order and consistent place.
- [ ] Use `Order` throughout the standard library (e.g. for sets and maps).
- [ ] Rewrite Synthesize to use `Order` and kill all `__cmp`.

No instances for:
- `Float32` and `Float64`
- `Array`, `Channel`, `Lazy`, `Ref`, etc.

Questions:
- What about collections (e.g. List, Set, or Map)?

```
class Order[a] {
  def compare(x: a, y: a): Ordering // see Core/Cmp.
}
```

We might want to break this PR into two; one for the type class and instances, and one for the library updates.

**Comment by esbenbjerre** [comment]
Can I use `<`, `==` and `>` to implement the order instances for `IntX`, or is that gonna be a problem?

**Comment by magnus-madsen** [comment]
You cannot. I think you need to wait for me to add some of the same infrastructure in:

https://github.com/flix/flix/issues/1581

**Comment by magnus-madsen** [comment]
OK; I guess you can do it now (it will work) and then we can refactor?

**Comment by esbenbjerre** [comment]
> You cannot. I think you need to wait for me to add some of the same infrastructure in:
> 
> #1581

Roger.

> OK; I guess you can do it now (it will work) and then we can refactor?

Roger 2.0.

**Comment by magnus-madsen** [comment]
I think the plan is then that `<=>` will be an alias for a call to `Order.compare`.

**Comment by magnus-madsen** [comment]
I think we can start on this-- but delay swapping the meaning of `<=>` until a bit later. Maybe wait for the Eq stuff to be in place.

**Comment by magnus-madsen** [comment]
While `Order` is now in, I am not closing this ticket, because we need to deal with `<`, `<=` and so forth when we allow implementations inside `Order`.

**Comment by magnus-madsen** [comment]
@esbenbjerre Would the following work:

We reduce the definition of `Order` to:

```
pub class Order[a] {

    ///
    /// Returns `LessThan` if `x` < `y`, `Equal` if `x` == `y` or `GreaterThan` `if `x` > `y`.
    ///
    pub def compare(x: a, y: a): Comparison

}
```

then in the companion namespace we add:

```
namespace  Order {
    /// Returns `true` if and only if `x < y`.
    pub def less[a: Order](x: a, y: a): Bool = ...
    // and lessEqual, greater, greaterEqual
}
```

then we rewrite `<`, `<=` and so forth to call `Order.less` etc?

Would that not work and allow us to avoid all these duplicate definitions?

**Comment by esbenbjerre** [comment]
> Would that not work and allow us to avoid all these duplicate definitions?

If I understand you correctly, you suggest we rewrite `<`, `<=` etc. in terms of `compare`?
If yes, then I agree. that seems very reasonable.

**Comment by magnus-madsen** [comment]
Sort of:

We write `<=` to `Order.lessEqual` which itself is implemented in terms of `compare` (here `lessEqual is a definition with an implementation, not a signature.)

**Comment by esbenbjerre** [comment]
> Sort of:
> 
> We write `<=` to `Order.lessEqual` which itself is implemented in terms of `compare` (here `lessEqual` is a definition with an implementation, not a signature.)

Yes that is actually what I meant. I'll look into it.

**Comment by magnus-madsen** [comment]
This trick also works for `Eq.neg`.

**Comment by esbenbjerre** [comment]
Hmm two concerns strike me now that I look at it.

1. What about all the shiny new intrinsics we defined? I have defined `compare` in terms of `lessEqual` for the built-in types, so this would essentially render the other intrinsics useless.
2. Does the suggested change degrade performance of comparisons?

**Comment by magnus-madsen** [comment]
> Hmm two concerns strike me now that I look at it.
> 
> 1. What about all the shiny new intrinsics we defined? I have defined `compare` in terms of `lessEqual` for the built-in types, so this would essentially render the other intrinsics useless.
> 2. Does the suggested change degrade performance of comparisons?

Right on both accounts. 

Hmm..  Ill get back to you. Hold for now :)

**Comment by magnus-madsen** [comment]
Order is almost done, but we need to:

- Move `min` and `max` into Order.
- Move `Order.toInt` to `Comparison.toInt` (same for `fromInt`).
- Add a function that converts an order to a function `a -> a -> Comparison`?
- Decide on PartialEq/PartialOrder and Eq/Order relationship.

**Comment by felixwiemuth** [comment]
Regarding the function `a -> a -> Comparison` we just discussed that this is actually `Order.compare` (which can also be partially applied). However, maybe one would want a function that represents the reverse order. This would be `flip >> compare`. I am not sure whether it is worth giving this a name like `reverseCompare` (in the `Order` namespace) or whether `(flip >> compare)` is readable enough and saving the extra function is a plus (smaller library, less to remember for user). As a reference, Haskell doesn't have that extra function.

We agreed that `Order` should extend `Eq` (same as in Haskell) and that we wait with `PartialOrder` and `PartialEq` because there the situation (also of the typeclasses themselves) is not that clear.

**Comment by magnus-madsen** [comment]
I will open a separate ticket for the Eq/PartialEq question. 

As for reverse, I guess we can leave it for another time.

**Comment by felixwiemuth** [comment]
Regarding reverse ordering, I just came across an interesting concept Haskell uses: a [Down](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Ord.html#t:Down) wrapper.

There is a
```haskell
newtype Down a 
```
together with an implementation of `Ord` which reverses the ordering on the original type:
```haskell
instance Ord a => Ord (Down a) where
    compare (Down x) (Down y) = y `compare` x
```
Thus, instead of
```haskell
sortBy (compare . flip) [2,1,3]
```
you can do
```haskell
sortOn Down [2,1,3]
```
which applies the data constructor `Down` to each element before comparing.

This I find more intuitive to read, as you sort on a *property* of the elements instead of having to provide a function that compares. In this case the property is the "down" value which could be seen as a generalization of negated integers (where you could do a (less readable) `sortOn neg [2,1,3]`).

I assume the same would work in Flix (with ordinary datatypes instead of newtype).

**Comment by magnus-madsen** [comment]
> Regarding reverse ordering, I just came across an interesting concept Haskell uses: a [Down](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Ord.html#t:Down) wrapper.
> 
> There is a
> 
> ```haskell
> newtype Down a 
> ```
> 
> together with an implementation of `Ord` which reverses the ordering on the original type:
> 
> ```haskell
> instance Ord a => Ord (Down a) where
>     compare (Down x) (Down y) = y `compare` x
> ```
> 
> Thus, instead of
> 
> ```haskell
> sortBy (compare . flip) [2,1,3]
> ```
> 
> you can do
> 
> ```haskell
> sortOn Down [2,1,3]
> ```
> 
> which applies the data constructor `Down` to each element before comparing.
> 
> This I find more intuitive to read, as you sort on a _property_ of the elements instead of having to provide a function that compares. In this case the property is the "down" value which could be seen as a generalization of negated integers (where you could do a (less readable) `sortOn neg [2,1,3]`).
> 
> I assume the same would work in Flix (with ordinary datatypes instead of newtype).

I am familiar with this idea, but I am neither convinced nor unconvinced. I think for Haskell its pretty good. But I do wonder how a 1st year student would react to the notion that you have a list and then you (conceptually) wrap each element in `Down` and then you sort the list. Again, that is not to say we should not have it. 

Does Rust do the same: https://doc.rust-lang.org/std/cmp/struct.Reverse.html or is this different?

**Comment by felixwiemuth** [comment]
I agree that having some explicit "reverseCompare" (or whatever a good name could be) for `flip >> compare` is probably a good idea and doesn't hurt, even if there are more sophisticated ways like using `Down`.

The `Down` method can still be useful in more complex situations. Imagine for instance you want reverse ordering in an existing algorithm without changing it; then you can just map `Down` over the elements before passing them to the algorithm and it would still work – at least as long as elements are sufficiently abstract in the algorithm's interface (like just constrained by `Ord`, but it can also be other type class constraints) so that there also exist instances for `Down` (and one could even supply them for this application).

> Does Rust do the same: https://doc.rust-lang.org/std/cmp/struct.Reverse.html or is this different?

Actually yes, the [implementation of `Ord`](https://doc.rust-lang.org/src/core/cmp.rs.html#611-616) (and that of `PartialOrd`) is analogous to that in Haskell.

**Comment by magnus-madsen** [comment]
We can close this one now, right? And then continue the other discussions in new tickets?

**Comment by felixwiemuth** [comment]
I'll add one more PR for the relationship making `Order` extend `Eq` and laws for `Order`.

Then I think the only new ticket that's missing is about the `PartialEq`/`PartialOrder` which you wanted to create.

Regarding the original description of this issue where you wrote that floats should not implement `Eq` and `Order`, can you briefly say why the instances now exist? Is it just temporary until it is decided whether they should rather have instances for `PartialEq`/`PartialOrder` instead because of the `NaN` problem?

**Comment by magnus-madsen** [comment]
> Regarding the original description of this issue where you wrote that floats should not implement `Eq` and `Order`, can you briefly say why the instances now exist? Is it just temporary until it is decided whether they should rather have instances for `PartialEq`/`PartialOrder` instead because of the `NaN` problem?

OK, I did not know that they exists. I think that should be debated in a PartialEq/Eq ticket.
