### ISSUE TITLE
Add Index and IndexMut type classes?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1599]
To abstract over `e[e]` and `e[e] = e`.

Argument against: Maybe this is going too far with overloading...

**Comment by stephentetley** [comment]
The Haskell world has a couple of classes related to this. The class `Ix` (Data.Ix) lets you make ranges for array indexing including for more exotic types than ints like Char and Unit. The classes `IArray` and `MArray `let you create arrays and perform some operations on them. The "derived" functions on IArray like `(!)` are the preferred functions to use rather than the unsafe ones provided by the class. Flix doesn't have Haskell's various array types so maybe the module exported functions, rather than a class, are good enough.

**Comment by magnus-madsen** [comment]
I think that we do not need these type classes. At least not yet.
