### ISSUE TITLE
Add Monad Type Class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1648]
```
class Monad[f] extends Applicative[f] {
  def point(x: a): f[a]
  def flatMap(fa: f[a])(f: a ⇒ f[b]): f[b] 
}
```

**Comment by stephentetley** [comment]
I've been working out translations of the Haskell functions in `Control.Monad` and `Control.Applicative` here:

https://github.com/stephentetley/flix-monadlib

I think I've got most of them done now (documentation and tests are still to write).

I'm having some problems defining functional monads (Reader and State) in the presence of effects, which I've commented on in #1649.

As well as `Monad` and `Applicative` we will also need an `Alternative` class. `MonadPlus` is unnecessary as it is legacy of Haskell missing out `Applicative` when it added `Monad`.

**Comment by magnus-madsen** [comment]
Excellent! Looking forward to it :)

**Comment by felixwiemuth** [comment]
The above MR provides a first basic version of the `Monad` type class.
It for now only adds the `flatMap` function to `Applicative`, plus all necessary laws.

The following is a discussion of existing and potential type class functions.

### `point`
I did not add a different function for `Applicative.point` (like `return` in Haskell).
Even if one wants to allow non-corresponding `Applicative` and `Monad` instances (breaking the `apCorrespondence` law) the `point` function will probably still be the same.

Regarding the name (for now the prefixed `Applicative.point`) I think eventually we want to have at least the basic typeclass functions for `Functor`, `Applicative` and `Monad` be available without namespace prefix, and the functions of the parent type class should be available under the same namespace. So we will be able to write `point` or `Monad.point` instead of `Applicative.point`, which might be a bit unintuitive.

### `>>` : `flatMap` with discarding

*Note that Flix currently uses `>>` for function composition.*

`>> : m[a] -> m[b] -> m[b]` is `flatMap` discarding the value from the first "action".

The default implementation would be

`flatMap_(x: m[a], y: m[b]) : m[b]) = flatMap(_ -> y, x)`

This would also be a law if we want to allow to override this definition (for performance reasons one might want to implement this function directly for `Option` etc.).

I did not add this yet, but probably we want to have it. What would be a good name? Or (as this probably will nearly exclusively be used in symbolic notation) would it be enough to have a symbolic operator `>>` for this (similarly as we said we would have `>>=` for `flatMap` with swapped arguments)?


### `flatten`
We can think about adding `flatten : m[m[a]] -> m[a]` (see Cats, or Haskell's `join`), which can both be defined in terms of `flatMap` and be used to define `flatMap`:
- `flatten(x) = flatMap(x, id)`
- `flatMap(f,x) = flatten(map(f,x))`

Then both functions could have a default implementation based on the other and when implementing an instance, any of the two can be chosen to be implemented. The situation is the same as with `ap` and `liftA2` for `Applicative`. As we do not have a mechanism yet to state that at least one of two functions must be implemented (see https://github.com/flix/flix/pull/2187#discussion_r702269179), we probably want to provide a default implementation for only one.


### `liftMX`, `liftAX`, `liftX`
I did not add `liftMX` functions because they have the same signature and meaning as the `liftAX` functions. So as opposed to the suggestion [here](https://github.com/flix/flix/pull/2187#discussion_r700351263) (which led to calling it `liftAX` instead of `liftX`) we actually only need one lift function if I did not miss anything.

Then we could actually rename `liftAX` to `liftX` (hoping that it won't break much).

I think the reason for having both would be if one wants to define instances that don't adhere to all laws (so that Monad and Applicative do not correspond as defined by law `apCorrespondence`).


### `flatMapX`

`Option`, `List` and `Array` currently have a `flatMap2` function.

In `List` and `Array` this is defined to apply the given function to pairs of elements at the same index, producing a list of results for each pair, which are then concatenated. While this function can be useful, I think the name is misleading, because the `Applicative` and `Monad` instances are about all possible combinations of elements in the datastructure (where the intuition can be non-deterministic computations) and not pairwise combination, see examples below.

#### Example `Applicative`
In applicative style we have (in Haskell syntax):
```
(\x y -> x + y) <$> [1,2] <*> [10,20] = [11,21,12,22]
```

#### Example `Monad`
Similar example, but the function produces a monadic value (multiple results):

```
do
  x <- [1,2]
  y <- [10,20]
  \x y -> [x+y, -(x+y)]
```
Results in `[11,-11,21,-21,12,-12,22,-22]`.

With general parameters this do-expression would be

```
do
  x <- xs
  y <- ys
  f(x,y)
```

and we could call it `flatMap2`:

`flatMap2(f, x, y) = flatMap(u -> flatMap(v -> f(u,v), y), x)`

While one would probably prefer do-notation in most cases, I think a function `flatMapX` can still be useful, also for X>2.

#### A general `flatMapX`

The meaning of a general `flatMapX` would be that we have a function that takes multiple pure arguments and produces a single monadic result and we want to apply this function to multiple monadic arguments in parallel. That is, instead of just sequential combination of monadic values, we now also have a parallel combination. The default implementation for `flatMapN` could just be the do-expression

```
do
  x1 <- xs1
  x2 <- xs2
  ...
  xN <- xsN
  f(x1, x2, ..., xN)
```

so we sequence the monadic arguments in order. This is maybe also the most intuitive meaning.
But maybe for some data types there will be other implementations that make sense, for example to improve performance by actually inspecting all arguments before using `flatMap` on them.

Note that `flatMapX` corresponds to `liftAX`, with the difference that the provided function returns a normal value for `liftAX` and a monadic value for `flatMapX`.


### Laws

We have the same laws as in Haskell, see also https://wiki.haskell.org/Monad_laws.
In the [documentation of Monad](https://hackage.haskell.org/package/base-4.15.0.0/docs/Prelude.html#t:Monad) Haskell also mentions two laws regarding the correspondence of `Applicative` and `Monad`. As we do not have a distinct `point` function in `Monad` (as `return` in Haskell) we do not need a law stating that these functions should be the same. The other law regarding correspondence of `ap` and `flatMap` is added (`apCorrespondence`).

**Comment by magnus-madsen** [comment]
Available in master, but could use some more functionality.
