### ISSUE TITLE
Visibility of functions in type class instances

### ISSUE THREAD

**Issue by esbenbjerre** [flix/flix#1666]
It does not currently seem possible to define helper functions inside a type class instance. For `Functor` I would like to move the definition inside the namespace, but I get:
```
-- Resolution Error -------------------------------------------------- List.flix

>> Undefined name 'mapHelper'.

92 |         mapHelper(f, xs, ys -> ys)
             ^^^^^^^^^
             name not found
```
With the implementation
```
instance Functor[List] {
    def map(f: a -> b & e, xs: List[a]): List[b] & e =
        mapHelper(f, xs, ys -> ys)

    def mapHelper(f: a -> b & e, xs: List[a], k: List[b] -> List[b]): List[b] & e = match xs {
        case Nil => k(Nil)
        case x :: rs => {
            let a = f(x);
            mapHelper(f, rs, ys -> k(a :: ys))
        }
    }
}
```

The only solution I can think of right now is to move the helper function inside the companion namespace of `Functor`, but that sort of groups unrelated helper function together.
EDIT: `pub def` does not do anything.

**Comment by magnus-madsen** [comment]
I think - for most instances- you should be able to call e.g. `List.map`.

But of course this problem should also be looked into.

**Comment by esbenbjerre** [comment]
> I think - for most instances- you should be able to call e.g. `List.map`.
> 
> But of course this problem should also be looked into.

Ahh - okay. I had an idea that all definitions in type classes should be independent of the std. library, but maybe that was just for the "core"-ish operators?

**Comment by magnus-madsen** [comment]
That was only for the ones in core (see Flix.scala)

**Comment by mlutze** [comment]
The main implementation complication here is that instances don't really have a namespace. E.g., the **signature** `map` of **class** `Functor` is put in the `Functor` namespace. But any **definition**s in an **instance** aren't added to a namespace; their implementation is just put in place of the signature later.

I'm thinking we can address this by creating a special un-referrable namespace for each instance. (We can't use the companion namespace since e.g. we would have a `mapHelper` for each type conflicting with each other.) Then we require implementation defs to be `pub` whereas helper defs are private.

**Comment by magnus-madsen** [comment]
For the moment, the plan is *not* to have private definitions instances classes or instances.

Instead, we should implement letrec such that the local visitor could just be defined inside `map`.

**Comment by magnus-madsen** [comment]
For the moment, we are going to allow any private functions / types / type aliases etc inside classes or instances.
