### ISSUE TITLE
Can another symbol be used for effects than &

### ISSUE THREAD

**Issue by sirinath** [flix/flix#1695]
Using common symbols used in langues for other meaning like `&` would be confusing.

**Comment by magnus-madsen** [comment]
Do you have some suggestions?

**Comment by sirinath** [comment]
Say `~`

**Comment by stephentetley** [comment]
I'm happy with `&` but I've a preference for calling the polymorphic effect `ef` in signatures rather than `e` or `f`. E.g

   pub def ap(f: m[a -> b & ef] , x: m[a]): m[b] & ef
   
`f` I would quite often use as a variable name for function arguments and `e` I might want to use to signify a polymorphic error type as we do already in `Result`. I'd never use `ef` anywhere except as an abbreviated name for the polymorphic effect.

**Comment by sirinath** [comment]
Alternatively you can have `a ->{XXX} b`  where `XXX` can be what ever you want. For pure `->{}`.

**Comment by magnus-madsen** [comment]
I like your comment about using `ef` for the effect variable. I think we should adopt that in the standard library.

As for `& ef` vs. `a ->{..} b` I don't have a strong opinion. We chose `a -> b & e` because it is easier to "see" the input/output part and you can read it as "function from a to b with effect e" or "function from a to be and an effect e".

**Comment by sirinath** [comment]
The other options is as what I said before `b ~ XXX`

**Comment by magnus-madsen** [comment]
We are discussion changes to the effect syntax, but that is happening in other tickets.
