### ISSUE TITLE
What can be done to improve *imperative* programming in Flix?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1932]
What steps can we take to improve imperative programming in Flix? I don't mean to "compromise" the language by adding for or while-loops. Yet, we should make it easy to express similar code. 

Things to consider in the short term:
- What is the idiomatic way to write code that "looks like" an imperative loop? We have lots of Array functions, but I am still not sure how you would do it.
- What is the idiomatic way to write a loop that does some computation until a `changed` flag becomes false? (See e.g. `Stratifier.flix` for an example).

Things for longer term:
- Support using mutable data inside pure functions (2nd class values).

Other ideas?

**Comment by magnus-madsen** [comment]
For example, I can already imagine something like:

```scala
let changed = ref true;
Loop.while(changed)(_ => { // will set changed to false
  // do work
 if (more work) {
   changed = true
 }
})
```

Not exactly pretty.

**Comment by mlutze** [comment]
Scala (also Kotlin, I think) has two features that make this kind of thing prettier: by-name parameters and `{...}` parameter syntax.

With by-name parameters, we could have:
```scala
let changed = ref true;
Loop.while(changed)({
  // do work
  if (more work) {
    changed = true
  }
})
```

With `{...}` parameter syntax, we could have:
```scala
let changed = ref true;
Loop.while(changed) {_ => {
  // do work
 if (more work) {
   changed = true
 }
}
```

With both, we could have
```scala 
Loop.while(changed) {
  // do work
 if (more work) {
   changed = true
 }
}
```

I'm not so sure about by-name parameters, since it might make code harder to reason about.

And a point against the brace syntax is that it makes "function-last" parameter order more attractive, rather than the curry-style "object-last".
