### ISSUE TITLE
Time / Duration API

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1947]
We should some proper library support for times/duration. We already have some stuff, but I am not really sure what the overall plan is? How do I express "5 seconds" and pass it to a function?

**Comment by stephentetley** [comment]
I've a lot of Java's time library wrapped here:

https://github.com/stephentetley/flix-time

Getting a 5 second duration would be:

> let fiveSeconds = Time/Duration.fromSeconds(5i64);

Although I'm thinking of changing functions like `fromSeconds` to `ofSeconds`. This is the Java convention and because we don't have a `Seconds` type I don't know that I like my current `toX` and `fromX` naming scheme.

The main problem of my time library is that it is big with some parts that are under-developed. Unless someone wrote a time library from scratch, a library wrapping `java.time` would always be large - time is simple a large subject. As I've worked on the Flix wrapper I've found I generally like the Java time library, certainly a lot more than I like the Haskell one; and personally I'd always be inclined to work with the Java library as a base than try from scratch.

To get a releasable library in a realistic time frame - I think I'd have to look at dropping features rather than working them up to release quality. I think we would need all the modules from `Clock` to `ZonedDateTime` in the top level folder of the Flix wrapper.

https://github.com/stephentetley/flix-time/tree/master/src/flix

We would also need `DateFormat`, `TimeFormat` and `DateTimeFormat` from `Format`. Maybe we can manage without the `Zone` modules for a first release. 

I would like to include the `Chrono` modules at some point but they probably won't be ready for a first release. 

The `Temporal` modules ideally would be removed with the functionality provided by "internal" modules - I think for the Java library they are essentially simulating multiple dispatch. There should be a better way to design them for Flix, especially if Flix gains multi-param type classes at some point.

**Comment by mlutze** [comment]
I'd be interested in learning more about the multi-param type class use case.

**Comment by stephentetley** [comment]
@mlutze 

The `until` method in java.time's `LocalDate`, `Instant`, `Year` and various others is one of the examples of multiple dispatch (I think Java experts may consider it "method overloading" rather than technically multiple dispatch).

> public long until(Temporal endExclusive, TemporalUnit unit)

`TemporalUnit` and `Temporal`are interfaces, although I imagine `endExclusive` would almost always be an object of the same class as it is called on, a simple usage might be something like this:

~~~

public static void test01() throws Exception {
    LocalDate d1 = LocalDate.now();
    LocalDate d2 = d1.withYear(2022);
    System.out.println("Days until: " + d1.until(d2, ChronoUnit.DAYS));
    System.out.println("Eras until: " + d1.until(d2, ChronoUnit.ERAS));
    System.out.println("Quarter years until: " + d1.until(d2, IsoFields.QUARTER_YEARS));
}
    
~~~

`java.time.temporal.ChronoUnit` is the main supplier of `TemporalUnit`'s but the polymorphism provided by `TemporalUnit` is essential to keep `until` extensible so it can use units provided by `IsoFields` or others.

In Java, ChronoUnit is an enum. For Flix, I've mixed feelings whether temporal units should be a single enum with constructors for each case or whether each case should be promoted to a separate type. (When Flix didn't have typeclasses a single enum with multiple constructors made sense and this is what I currently use.) 

Because I haven't explored (single param) typeclasses for the time library, `until` is unpleasantly limited - currently each appropriate Time / Date type defines `until` in its namespace but it uses `ChronoUnit` in the signature so it is limited to `ChronoUnit` 's fixed set of cases:

> pub def until(b: OffsetDateTime, e: OffsetDateTime, unit: ChronoUnit): Int64

`until` should definitely take advantage of single param typeclasses for the unit argument, to be something like this:

> pub def until(b: OffsetDateTime, e: OffsetDateTime, unit: u): Int64 with TemporalUnit[u]

I'm not sure that `until` in itself provides a compelling use-case for multi-param typeclasses. However in Java `until` as well as being a method in the `LocalDate` etc. classes it is also a method in the `Temporal` interface: 

https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/time/temporal/Temporal.html

Discounting the `with` and `isSupported` methods of Temporal you're left with three methods that are much more wide ranging as they are important operations of affine geometry:

* `until` is point subtraction

* `plus` is point plus vector

* and `minus` is point minus vector

Representing this as a type class would require multiple params, Haskell's experience suggests it needs additional power either from functional dependencies[1] or type families[2]: 

[1] https://hackage.haskell.org/package/simple-affine-space-0.1.1/docs/Data-AffineSpace.html

[2] https://hackage.haskell.org/package/vector-space-0.16/docs/Data-AffineSpace.html

**Comment by mlutze** [comment]
Thanks for the explanation!

**Comment by magnus-madsen** [comment]
I think it is reasonable to keep everything with time in a separate library for now. 

We should probably get rid of our own `Time` modules. They are very sparse.
