### ISSUE TITLE
Disallow Types, Type Aliases using pre-defined names

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1965]
E.g. you should not be allowed to define your own `Lazy` or `String` type.

- All the primitives
- Channel
- Lazy
- Ref
- more?

**Comment by magnus-madsen** [comment]
Milestones:

- [ ] Add a `WeederError.ReservedTypeName`
- [ ] Add a `visitIdent(ident: Name.Ident): Validation[...]` to `Weeder`.
- [ ] Use it here https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L219

**Comment by nicdard** [comment]
Hi @magnus-madsen, I would like to start to take a look on this :)

**Comment by magnus-madsen** [comment]
Around here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Weeder.scala#L227

You should call the new `visitIdent`

**Comment by nicdard** [comment]
I was looking at how to implement `visitIdent` and I have the following questions:
* is there any list ready to be used of pre-defined names that we should forbid in type definition, or should I encode it in a match expression by myself? I have tried to search a bit around also in the parser. I would say that maintain this check manually would be painful and annoying and I was wondering if there is a method to have a list of built-ins + standard library types automatically (as I think this is the end goal, but I may be wrong). I am asking also since by going around the code I have found `PredefinedClasses` and I am wondering if they are related to this task.
* my understanding is that we want a generic function (not dependent on the ParsedAst node) that will visit and thus examine the ident of a generic node of an AST, to check for re-usage of type names. Thus I would propose the following signature:
```scala
private def visitIdent(ident: Name.Ident): Validation[Name.Ident, WeederError]
```
in case the check succeeds we get back the ident we passed in, otherwise we raise `WeederError.ReservedTypeName`

Am I on the right track? Thanks in advance :)

**Comment by magnus-madsen** [comment]
@mlutze Could I ask you to weight in and explain? :)

**Comment by mlutze** [comment]
There's no ready-made match anywhere as far as ai know; you'll need to make it yourself. Maybe it could be combined with the code for `SuspiciousTypeVariable`?

The best place to look is in `Type.scala`, which should have all the primitive types. I'm not sure that covering the standard library is within the scope of this change (after all, then the standard library wouldn't compile!).

The signature of your visit function looks reasonable to me. (Personally I prefer to return `Validation[Unit, Err]` when there's no transformation done, but that's a point where Magnus and I differ, I think :) )

**Comment by nicdard** [comment]
Oh right, I didn't think about it, thanks a lot!

**Comment by magnus-madsen** [comment]
I think it is only the Ident in used in enum you should check

**Comment by nicdard** [comment]
I am sorry for the long time, I had unfortunately some interview preparation and then exam session, I will start back to work on this during this weekend :)

**Comment by magnus-madsen** [comment]
No worries. Welcome back :)
