### ISSUE TITLE
Is Pure Operator

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2001]
I think it would be interesting if one could write:

```scala
pub def flatMap(f: a -> List[b] & e, xs: List[a]): List[b] & e = {
  if (ispure(f)) {
    // f is pure hence we can evaluate it in any order on `xs`.
  } else {
    // std. impl.
  }
}
```

(Note: The purists will claim that this violates "parametricity".)

I guess we would need some more examples to determine if this is useful.

**Comment by mlutze** [comment]
Note that we can *almost* do this already with type classes, if we can resolve the type operator question.

**Comment by magnus-madsen** [comment]
> Note that we can _almost_ do this already with type classes, if we can resolve the type operator question.

Yes. I thought about that... But then- do we want every method that wants to use this to be part of a type class?

**Comment by mlutze** [comment]
I don't understand. What I mean is the following:

We add this to the standard library:
```scala
lawless class IsPure[e: Bool] {
  pub def isPure(f: a -> b & e): Bool
}

instance IsPure[true] {
  pub def isPure(_: a -> b & true): Bool = true
}

instance IsPure[false] {
  pub def isPure(_: a -> b & false): Bool = false
}
```

This gives us the `IsPure.isPure` function everywhere, with no magic and no further type class membership necessary.

**Comment by magnus-madsen** [comment]
I see. That is smart! (Too smart? :))

- What happens if you have an effect that is formula?
- Will this IsPure not "pollute" type signatures?

**Comment by mlutze** [comment]
> What happens if you have an effect that is formula?

See also: https://github.com/flix/flix/issues/1842

Here's my initial idea for the formula case, though it might require some changes to how we do boolean unification in the context of instance selection:

```scala
instance IsPure[a and b] with IsPure[a], IsPure[b] {
  pub def isPure(_: _ -> _ & a and b): isPure(a) and isPure(b)
}

// similar for IsPure[a or b], IsPure[not a]
```

> Will this IsPure not "pollute" type signatures?

Yes, I think it would indeed pollute type signatures. Two options I'm thinking of for that:
1. Just handle this case specifically
  * Pros: probably easy to implement
  * Cons: one special magic case: can be confusing
2. Introduce a `total` modifier for type classes: requires that all types of the class's kind have an instance (only relevant for inductively-defined kinds, i.e. only booleans currently). Then we can remove these from type signatures since the type constraint is trivially fulfilled.
  * Pros: generic, could be useful if we allow user-defined kinds or add more kinds in the future
  * Cons: maybe an over-engineered solution, one more modifier for what (currently, at least) is a very rare use case

**Comment by jacopol** [comment]
Would this allow different instance for IsPure[a], IsPure[True and a] and IsPure[a and True]?
Similar for IsPure[a and a] and IsPure[a or a] and IsPure[not not a]...
In other words, should these formulas be understood modulo Boolean equivalence?

**Comment by mlutze** [comment]
Currently we disallow "complex instances". This means that the type of any instance must be of the form `X[a1, a2, a_n]` (`n >= 0`) where: 
1. `X` is a type constructor
2.  `a1 ... a_n` are type variables
3. `a1 ... a_n` are distinct
4. 
These are the same rules as Haskell (without extensions).

This means that `a` (1), `True and a` (2), `a and a` (3), and `not not a` (2) are invalid instance types.
The reason for this is that we want instances to be uniquely identifiable from the type constructor; it saves a lot of extra work disambiguating.

So while `isPure(f: a -> b & True)` and `isPure(g: a -> b & True and ef)` should be equal, they'll be directed to different instances (`True` and `x and y`, respectively). 

Now that I think about it, after monomorphization, we should no longer have free type variables. So any boolean formula should be fully reducible to `True` or `False`, meaning we would only need instances for `True` and `False`, not the boolean type operators. Is that correct?

**Comment by magnus-madsen** [comment]
Research continues offline.
