### ISSUE TITLE
Refactor functions that require impure functions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2010]
We have a few functions that require impure functions. For example, `List.foreach` requires an impure function (i.e. a false Boolean).

With the upcoming region memory managed these functions will not really work as expected any more.

We have very few such functions and I simply propose to make them effect polymorphic.

(Note this does not affect the ability of higher-order functions to demand **pure** function arguments which is the important part of the effect system.)

Simply search for `~>` in the library:

- `foreach`
- `unfoldWithX`
- `queryWith`
- `unfoldString`
- `forIndex`

**Comment by jaschdoc** [comment]
Do you want this change applied to `foreachWithIndex` too?

**Comment by jaschdoc** [comment]
Additionally, since changing the higher-order from always being impure to its effect being polymorphic, I would assume a function which takes multiple effectful functions as arguments is only pure if all received functions are pure (if that makes sense).
Specifically, I stumbled upon a `queryWith` function with the signature
```pub def queryWith(p: k -> Comparison & e, f: (k, v) ~> Unit, tree: RedBlackTree[k, v]): Unit & Impure```
and I suggest changing it to
```pub def queryWith(p: k -> Comparison & ef1, f: (k, v) -> Unit & ef2, tree: RedBlackTree[k, v]): Unit & (ef1 and ef2)```
(notice the function `p` has its signature changed as well as the return type of `queryWith`).
Is this correct / what you had in mind?
