### ISSUE TITLE
Closable Streams - How?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2035]
TBD

**Comment by stephentetley** [comment]
In practice I don't think this will be an issue after all.

In Java, resources that need closing are rarely iterators / streams, instead they are handles of some sort with both `iterator()` [or `stream()`] and `close()` methods.

`iterator()` gets the respective `Iterator` from the handle, `close()` closes the handle rather than the iterator (or stream).

The Flix analogue would be to pair an iterator with a handle that can be closed. Client code would follow a pattern like this:

~~~

let* handle = SqlDb.newQueryHandle(conn, query);
let iter    = SqlDb.getIterator(handle);
let* size   = Iterator.count(iter);     /// Probably something more useful...
let* _      = SqlDb.close(handle);
Ok(size)
        
~~~
