### ISSUE TITLE
File API

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2040]
I want to propose a simple and practical API design for File I/O.

This is not the "Cadillac design", but more like the "Fiat Punto design". (Does this expression work in English?)

The design is not particular type-safe nor does it make particularly good use of the Flix type system. I envision that can come later. 

This supersedes everything in `Core/Io` which should be deleted and replace by a single namespace `File`:

# A Few Design Choices

- We drop the notion of an explicit `File` or `Path` type.

- We drop the Java notions of `InputStream`, `InputStream`, etc. (We will use
  the `Iterator` in a few places where relevant).

- Every IO operation returns a `Result[value, String]` where `Err(msg)` holds an
  error message `msg` if the operation failed. 

- We provide two functions for most operations: One with sensible defaults and
  one that takes a record of options.

- We pass record first, e.g.:
    File.readBytesWith({ ... }, file: String).
  which works better with pipelines.

- All APIs are impure (unless otherwise stated).

The proposed API follows:

# Files & Paths

I think we only need:

- `def pathSeparator(): String` (NB: This is pure).

(Controversial): We add an instance of `Div` for `String` that defines `s1 / s2`
as `s1 + pathSeparator() + s2` (!)

# Basic Queries

```
def exists(file: String): Result[Bool, String]

def isDirectory(file: String): Result[Bool, String]
def isRegularFile(file: String): Result[Bool, String]
def isSymbolicLink(file: String): Result[Bool, String]

def isReadable(file: String): Result[Bool, String]
def isWritable(file: String): Result[Bool, String]
def isExecutable(file: String): Result[Bool, String]
```

# Reading and Writing

## Reading Text

```
def read(file: String): Result[String, String]

def readWith(opts: {offset: Int64, count: Int32, charSet: String}, file: String): Result[String, String]

def readLines(file: String): Result[List[String], String]

def readLinesWith(opts: {charSet: String}, file: String: Result[List[String], String]

def readLinesIter(file: String): Iterator[Result[String, String]]

def readLinesIterWith(opts: {charSet: String}, file: String): Iterator[Result[String, String]]
```

## Reading Bytes

```
def readBytes(file: String): Result[Array[Int8], String]

def readBytesWith(opts: {offset: Int64, count: Int32}, file: String): Result[Array[Int8], String]
```

## Reading Chunks of Bytes

```
def readChunks(file: String, chunkSize: Int32): Iterator[Result[Array[Int8], String]]
```

## Writing Text

```
///
/// Writes `data` to the given `file`.
///
/// Creates `file` if it does not exist. Overwrites it if it exists.
///
/// Returns `true` if the file was created.
///
def write(file: String, data: t): Result[Bool, String] with ToString[t]

///
/// Writes `data` to the given `file`.
/// 
/// Creates `file` if it does not exist. Overwrites it if it exists.
///
/// Returns `true` if the file was created.
///
def writeLines(file: String, data: f[String]): Result[Bool, String] with Foldable[f]

def append(file: String, data: t): Result[Bool, String] with ToString[t]

def appendLines(file: String, data: f[String]): Result[Bool, String] with Foldable[f]
```

## Writing Bytes

```
///
/// Writes `data` to the given `file`.
///
/// Creates `file` if it does not exist. Overwrites it if it exists.
///
/// Returns `true` if the file was created.
///
def writeBytes(file: String, data: f[Int8]): Result[Bool, String] with Foldable[f]

def appendBytes(file: String, data: f[Int8]): Result[Bool, String] with Foldable[f]
```

## Truncate

```
///
/// Returns `true` if the file was created.
///
def truncate(file: String): Result[Bool, String]
```

# Open Questions

- How should iterators release their resources?

- How should operations that return iterators be named?

- What should happen if a directory does not exist?

- The return type of `readLinesIter` is `Iterator[Result[String, String]]`.
  Should it be `Result[Iterator[Result[String, String]], String]` ?

- Is it a good idea to use records?

# Next Step

This is the first of a few tickets that will expand this part of the library.

**Comment by stephentetley** [comment]
I think not having `File` as some kind of abstract type and only having "files" operationally (e.g. through functions like `writeFile` and `readFile`) is a good choice, however I would argue for both `Charset` and `FilePath` to be opaque types, with `Charset` wrapping `##java.nio.charset.Charset` and `FilePath` wrapping `##java.nio.file.Path`.

With Charset as a String there is a significant potential for misspelling, to get around this you could provide a library of constants: 

~~~

pub def utf_8(): String = "UTF_8"

pub def iso_8859_1(): String = "ISO_8859_1"

/// etc.

~~~

But once you provide this, you are half way to wrapping `##java.nio.charset.Charset` anyway. Plus an opaque type indicates what the type means to the user and stops you running arbitrary String operations on a Charset name.


`##java.nio.file.Path` has comparable functionality to Haskell's `System.FilePath` and is essentially "functional" (operations are immutable), plus it already deals with cross platform issues. As a wrapper would be its own type we wouldn't need a division instance for String to make a pleasant concatenation operator. Suppose we added `<>` as an alias for `Semigroup.combine` (like Haskell has done), we could use Semigroup to build paths:

~~~

let outpath = FilePath.new("/home/stephen/") <> FilePath.new("file.txt");
...

~~~

Instantiating a FilePath with `new` is admittedly a bit clunky but we could have a combinator `</>` (snoc) that adds a string rather than a FilePath to the right:

~~~

pub def </>(x: FilePath, name: String): FilePath = 
    x <> FilePath.new(name)
    
    
let outpath = FilePath.new("/home/stephen/") </> "file.txt";
....

~~~


I've implementations of both, here:

https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/Text/Charset.flix
https://github.com/stephentetley/flix-sandbox/blob/master/src/flix/System/FilePath.flix

Both modules I need for their functionality but I haven't properly kept up-to-date (e.g as Flix has got typeclasses) so they would need some polish for the standard library.

**Comment by stephentetley** [comment]
I've a worked up design somewhere between a Cadillac and Fiat Punto in my repo `flix-sandbox`:

https://github.com/stephentetley/flix-sandbox/

The relevant Flix modules are:

I18n/Locale
Text/Charset
System/IO
System/FilePath
System/Directory

The last three modules are patterned after their Haskell namesakes and the first two modules enable them. The dependency on Locale for the System modules is small and could be removed, but it is major dependency for the Time library so it would need adding for that.


These two are a bit less fleshed out and maybe wouldn't be ready for an initial release - again they are patterned after their Haskell namesakes:

System/Environment
System/Process

I think we will still need "handle style" File IO, but we could delegate it into a sub-folder of the System namespace. I've done this with:

System/File/BufferedReader (for reading text files) 
System/File/FileInputStream (for reading binary files)

These modules should get corresponding modules for writing (I haven't needed them yet so haven't created them). There's an argument that these File modules could be in a separate package (when we have packages).

The last System module could certainly be an independent package rather than part of the stdlib:

System/File/BOM

This adds support for BOM files but it brings in a dependency on Apache's `commons-io`. Files with BOM prefixes might be largely avoidable in a Unix only world, but they are a pain you have to work with in the Windows world.

**Comment by magnus-madsen** [comment]
Thanks for the write-up Stephen.

After some discussions and reading through the code I not convinced of the need for `FilePath` at this time. It's not that I don't believe in a type safe notion of a file system path, it is more that I want a sweet, easy to use file API in the short term. (By the way, I am not against a strongly typed `Charset` type). It is more that I want to attract more users soon and I don't want too much friction with file I/O. Ultimately I think there will be *another* file API probably based on algebraic effects (but we are far way from having those). 

For the readers and writers, when are they needed? I was hoping that iterators and lazy lists would be sufficient. 

Other than that I think there is a lot of good api / code that we should try to include in the proposal / implementation.

**Comment by magnus-madsen** [comment]
@ninaandrup Here is some old code that might be useful as inspiration: https://github.com/flix/flix/pull/2166/files#diff-66a3ce8fa865c8586f052f650c624fdb0d4d23aeca20635e22115e346c1cf953

**Comment by magnus-madsen** [comment]
@ninaandrup Which of these are we missing? Is it time for me to extend the list? :)

**Comment by ninaandrup** [comment]
> * pathSeparator

These are not merged in main yet:

- [ ] pathSeparator
- [ ] readChunks *
- [ ] writeBytes *
- [ ] appendBytes *
- [ ] truncate *

The ones with *, I have a draft for them in VS code. I will make a PR now.

**Comment by magnus-madsen** [comment]
Oki doki. Thanks. Ill begin thinking about what comes after that.
