### ISSUE TITLE
Backend: Compile Logic Language to JVM bytecode

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#206]
The logic rules of Flix should be compiled to JVM bytecode via translations to relational-algebra like operators (SELECT, JOIN, PROJECT, etc. + an operator for our lattice semantics). 

This project involves significant work, including:
- Designing the low-level query language.
- Translation from Flix-style horn clauses to the query language.
- Selection of evaluation-order (query planning and costs models).
- Translation to JVM bytecode itself.
- Interop with the solver and related components.

**Comment by olhotak** [comment]
I have a more straightforward design in mind for this project. There is no need to invent a new low-level query language. The language of Flix rules is sufficient, and we already have a semantics defined for it. The translation from Flix rules to Java bytecode can just be a straightforward partial evaluation of the solver algorithm used by the interpreter. Specifically, we determine all possible binding patterns that a given rule will be evaluated with. Then, for each binding pattern, the algorithm will be partially evaluated using that binding pattern as a constant input, resulting in bytecode that just looks things up in the correct indexes. At run time, whenever we need to evaluate a rule, we determine the current binding pattern, and then invoke the partially evaluated bytecode specialized to that binding pattern. A key benefit (in addition to simplicity) is that this guarantees the same semantics as the interpreter algorithm (since it's just a partial evaluation of the same algorithm). Another benefit is that the index data structures can be shared by the interpreter and the partially evaluated code.

If we want to implement additional high-level relational database style optimizations, we can implement them as transformations at the level of the Flix rule language (i.e. we transform rules into sets of other, more efficient rules). Again, this should make it reasonably easy to reason about correctness of the transformation (since they will be at the level of the high-level Flix rule language). In his talk, Rei said that he got a lot of performance improvement from this kind of rule transformation (in particular, splitting one rule into many specialized rules for particular cases).

This design is also more approachable. One can start by doing various refactorings in the interpreter, such as determining the binding pattern before beginning to evaluate a rule. (The current interpreter implementation repeatedly recomputes the binding pattern and selects an index for every single tuple that it loops over.) A lot of the work can be done before even starting to generate any code. Also, the generated code can start out quite simple, because it can just call into functions that have already been written for the interpreter. As specific functions are determined to be performance bottlenecks, they can be added gradually to the set of code that we specialize/partially evaluate. We can always have a working and correct system, and the improvements can be done incrementally.

**Comment by magnus-madsen** [comment]
I am closing this as we decided not to compile the logic language. Instead we need to make sure the interpreter is efficient and using the right data structures.
