### ISSUE TITLE
Add toIterator to collections

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2073]
Add a function `toIterator` to:

- `Option`
- `Result`
- `List`
- `Nel`
- `Array`
- `Set`
- `Map`
- `MutSet`
- `MutMap`

and 

- Add a function `toIterator` to `Foldable` (?)

and

- Remove the function `Iterator.toIter`.

Question: Is `toIterator` a good name?

**Comment by jaschdoc** [comment]
> Question: Is `toIterator` a good name?

`toIter` would be consistent with `toImm` and `toMut` i.e. short names where possible. What is the benefit of using the longer `toIterator` name when abbreviations are already established as names for functions that convert to another data structure? `toList`, `toSet`, `toMap` are all very short to begin with so it makes sense for those functions to include the entire name of the data structure.
Additionally, since [Flix already prefers short keywords](https://flix.dev/principles/) it would be consistent with that too to name the function `toIter`.
I hope that makes sense :)

**Comment by magnus-madsen** [comment]
We shall call it `toIter`.
