### ISSUE TITLE
[Frontend]: Add support for private definitions?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#219]
During the development of the Flix library, we discovered that it was useful to have several "helper functions" when implementing the public API. 

The question is whether these functions should be exposed.

In Java/Scala/etc. there is the notion of `private`, `protected`, `public`, etc. But I don't think Flix wants to go that way. For one, the relations and lattices in Flix are globally accessible, and this is what makes it so nice to write an analysis in Flix/Datalog; you can inject a fact into some relation/lattice from anywhere. Similarly, I see no reason why functions should not be callable from anywhere. Especially given that they have no side-effects.

My only concern - for the Flix library - is that helper functions may become part of the public API and users may come to depend on them. 

I think we should adopt a very light-weight solution to this problem. I would propose one of the following:

a. Allow functions to start with `__` which marks them as non-public.
b. Add an annotation `@private` or `@internal` for the same purpose.

The compiler would not be changed to enforce any kind of visibility, the naming/annotation would simply be a marker to the users that the function is non-public.

**Comment by mhyee** [comment]
I agree on keeping things simple and not having any access specifiers (`public`, `protected`, `private`). I also agree that we don't want uses to depend on "internal" library functions.

Of the two options, I prefer the annotation because it's less intrusive. I'm not sure how I feel about an annotation that doesn't do anything.

Another possibility is to just document it very clearly in the comments or API docs. But maybe that's not as "loud" as an annotation.

**Comment by magnus-madsen** [comment]
I agree. Let us add a special annotation. I suggest `@internal`. It will mark a method as being "non-public". Its only effect will be to omit functions from any (future) generated documentation.

**Comment by magnus-madsen** [comment]
Added `@internal`.
