### ISSUE TITLE
Bug: Fix `List.List.append` bug.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2251]

**Comment by jhckragh** [comment]
Some details about this bug (which is still present in master at the time of writing with extension version `0.53.0`): Autocompleting a qualified name such as `List.append` can cause the namespace part to be duplicated. This seems to happen when the user has already typed in some text after the dot.

For example, this behavior is correct: ✔️

![FlixCompletionOk](https://user-images.githubusercontent.com/129259/142758987-61375efa-d6a8-49ae-80b6-f18dd5e0042f.gif)

But this behavior is wrong: ❌

![FlixCompletionErr](https://user-images.githubusercontent.com/129259/142758997-06d972ee-3175-4067-b826-604be503af9e.gif)

**Comment by magnus-madsen** [comment]
Yes. I am not really sure why it happens. But cool gifs!

**Comment by magnus-madsen** [comment]
This is the place to start, but not sure if it is easy to understand:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala#L281

**Comment by jhckragh** [comment]
I think I now have an idea for why this happens. In the [VSCode API docs for CompletionItem](https://code.visualstudio.com/api/references/vscode-api#CompletionItem) an optional `range` property is mentioned. It seems that if this property is omitted, then VSCode will find a fallback position by going backwards until a non-word character is encountered; that explains why the problem only occurs after the dot (a non-word character):

![range](https://user-images.githubusercontent.com/129259/142772411-4bb01993-edb2-4ddf-97e8-39484d3832ae.png)

I think the problem can be fixed by including the proper range(s) in the LSP response. I don't know how involved that'll be, but at least we now have an explanation for the somewhat mysterious editor behavior. 🙂

**Comment by magnus-madsen** [comment]
Hmm. It is a bit hard to include proper ranges because we are working on a "broken" document while auto-completing.

**Comment by magnus-madsen** [comment]
The current word cannot contain a dot I presume?

**Comment by magnus-madsen** [comment]
I am guessing we need a hack to determine if there is a dot or namespace prefix or something.

**Comment by magnus-madsen** [comment]
I think this might be fixed now?

**Comment by jhckragh** [comment]
Looks good to me after your fix. 🙂

**Comment by magnus-madsen** [comment]
Yay!
