### ISSUE TITLE
Review LazyList

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2307]
(Text TBD- dont start yet)

- [ ] Ensure that appropriate type classes are implemented:
  - [ ] `Eq`, `Order`, `ToString`
  - [ ] `Functor`, `Foldable`.
- [ ] Ensure every function in these TCs also appear in the `LazyList` namespace.
- [ ] Ensure that functions are maximally lazy.
- [ ] Ensure that functions are maximally effect polymorphic.
- [ ] Ensure that functions are tail recursive when possible.
- [ ] Re-order the file so that its content appear in a reasonable order.
- [ ] Reformat comments and code if needed. Tweak comments if needed.
  - [ ] Ensure that the `map`, `mapE`, `mapL` naming convention is used everywhere.
  - [ ] List arguments should be called `l`, functions `f`, and destructed lists `x` and `xs`.
  - [ ] Ensure that doc comments and code agree on names.
- [ ] Review tests
  - [ ] Possibly reduce the amount of tests by 20-30% (keeping the same test coverage, but just having fewer tests overall.)
  - [ ] Ensure that tests do not construct unreasonably large data structures (i.e. lists of more than a few elements).
  - [ ] Ensure that tests construct unreasonably large *lazy* data structures (i.e. only to check laziness).
  - [ ] Rename `TestLazyList2`  to `TestLazyList`.
- [ ] Check correct use of public/private (i.e. only functions that are public should be `pub`).
- [ ] Add `LazyList / TestLazyList` to the compiler benchmarks.
- [ ] ~~Rename `LazyList` to `Seq`. (Unless we have a better name).~~

**Comment by jaschdoc** [comment]
Some test function names are also inconsistent in their schema (`filterFusion` vs. `takeWhiletakeWhileFusion` repeated function name)

**Comment by jaschdoc** [comment]
- [x] Ensure that appropriate type classes are implemented:
- [x] Ensure every function in these TCs also appear in the LazyList namespace.
- [x] Ensure that functions are maximally lazy.
- [ ] Ensure that functions are maximally effect polymorphic.
- [ ] Ensure that functions are tail recursive when possible.
- [ ] Re-order the file so that its content appear in a reasonable order.
- [ ] Reformat comments and code if needed. Tweak comments if needed.
- [ ] Ensure that the map, mapE, mapL naming convention is used everywhere.
    - [ ] List arguments should be called l, functions f, and destructed lists x and xs.
    - [ ] Ensure that doc comments and code agree on names.
- [ ] Review tests
    - [ ] Possibly reduce the amount of tests by 20-30% (keeping the same test coverage, but just having fewer tests overall.)
    - [ ] Ensure that tests do not construct unreasonably large data structures (i.e. lists of more than a few elements).
    - [ ] Ensure that tests construct unreasonably large lazy data structures (i.e. only to check laziness).
    - [ ] Rename TestLazyList2 to TestLazyList.
- [ ] Check correct use of public/private (i.e. only functions that are public should be pub).
- [ ] Add LazyList / TestLazyList to the compiler benchmarks.
- [ ] Tweak `map` according to #2349
- [ ] Resolve #2347 (add to stdlib)

**Comment by jaschdoc** [comment]
Oh right! I forgot, my bad. It would certainly make sense to mimic that.

**Comment by jaschdoc** [comment]
> Re-order the file so that its content appear in a reasonable order

@magnus-madsen what is the guideline for a *reasonable order*?

**Comment by magnus-madsen** [comment]
> 
> 
> > Re-order the file so that its content appear in a reasonable order
> 
> @magnus-madsen what is the guideline for a _reasonable order_?

Yeah. Hard to say. But look in List and try something like that.

**Comment by jaschdoc** [comment]
Should we add aliases `fold`, `find` (possibly others) for `foldLeft` and `findLeft` respectively?

**Comment by magnus-madsen** [comment]
> 
> 
> Should we add aliases `fold`, `find` (possibly others) for `foldLeft` and `findLeft` respectively?

No. I think we are going away from those.
