### ISSUE TITLE
Tweaks to SymbolProvider

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2390]
- [x] https://github.com/flix/flix/issues/2387
- [ ] Use `sym.toString` and not `sym.name` to ensure namespace is included.
- [ ] Use the right source location for the "breadcrumbs" (note `DocumentSymbol` has different source locations, we should probably make use of them)
- [ ] Include public/private information in the symbols?
- [ ] Check the above concerns for `WorkspaceSymbol`.
- [ ] Maybe we can use "groupBy" to rediscover the namespaces?

**Comment by nicdard** [comment]
:+1:

**Comment by nicdard** [comment]
A few comments: 
- I don't know if we really want to include the namespace in the symbol name, by doing this we will see in the "breadcrumbs" and in the outline the "namespace" name prefixed everywhere and this feels redundant, since both of them display things hierarchically.
- the location seems to be already ok within classes and enums, so I think we just need to add the implementation (when available) location range as part of `DocumentSymbol` `range` field.
- private/public information are not carried by `DocumentSymbol` so either we can put this information in the description of the symbol (a simple string used for ui purposes) or just let it as it is.

What do you mean by using "groupBy" to rediscover the namespaces? What's the goal?

**Comment by magnus-madsen** [comment]
How far did we get with this?
