### ISSUE TITLE
Adding support for Sets and Maps

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#244]
We currently have support for algebraic data types which are sufficient for implementing things like Option, Result, List, and general trees. These constructs are not built-in into Flix, except for List which has special syntax for cons `::`. ADTs and lists give us a rich language that together with relations/lattices allow us to express a large range of analyses. However, we still lack a way to work with sets and maps. 

It seems we need sets and maps when we want to define more general lattices or perform aggregation. It may be worth noting that association lists can be used as a poor-mans substitute for sets and maps.

While we could extend Flix with say Vectors (immutable arrays) which would allow for the implementation of HashSet and HashMaps this would be folly; the purpose of Flix is _not_ to be a general-purpose programming language, but a special purpose language. I feel that for these reasons sets and maps should be built-in in a nice way so that they can interact properly with relations and lattices.

I would like to discuss some examples of analyses which require sets and maps in a form which we do not yet have, and I would like to discuss how we should integrate sets and maps.

I feel like when Flix has Option, Result, List, Set, and Map then we will be close to feature-complete for a nice useful functional language. It will then be a matter of having the best possible integration of these features.

**Comment by mhyee** [comment]
> It may be worth noting that association lists can be used as a poor-mans substitute for sets and maps.
[...]
While we could extend Flix with say Vectors (immutable arrays) which would allow for the implementation of HashSet and HashMaps this would be folly [...]

It's also worth noting that sets and maps could be implemented with (self-balancing) trees. (Racket and Haskell use trees, C++ uses red-black trees before they adding the constant time `unordered_set` and `unordered_map`.)


But I agree that sets and maps should probably be built right into Flix.

**Comment by magnus-madsen** [comment]
> It's also worth noting that sets and maps could be implemented with (self-balancing) trees.

That is a very good point. I totally forgot about that. 

I am thinking to better understand what is needed it might be useful to implement something like:

- Pentagons: A Weakly Relational Abstract Domain for the Efficient Validation of Array Accesses

In Flix (or rather first in Scala, to see what features are needed).

**Comment by magnus-madsen** [comment]
What are the minimal features the compiler must support for sets and maps?

Wikipedia talks about boolean algebras, but that assumes negation on some universe.

Are the following sufficient?:

- `def empty[a]: Set[a]`
- `def singleton[a](x: a): Set[a]`
- `def union[a](xs: Set[a], ys: Set[a]): Set[a]`
- `def fold[a, b](f: (a, b) -> b, xs: Set[a]): b`

We could add those as external definitions. We would probably still want set and map literals.

I believe we discussed the syntax:

- Sets: empty set `#{}`, singleton set `#{42}`, and so on `#{1, 2, 3}`
- Maps: empty map `@{}`, singleton map `@{1 -> "foo"}`, and so on `#{1 -> "foo", 2 -> "bar"}`
- (Vectors, for completeness): `#[]`, `#[1]`, and so on `#[1, 2, 3]`.

With this syntax we only need `union` and `fold`.

**Comment by magnus-madsen** [comment]
Then I had this crazy idea that we should allow pattern matching on sets:

```
def f[a](xs: Set[a]): Int = match xs with {
  case #{} => 0
  case #{1, 2, 3} => 42
  case #{x, y} => x - y // ugh
  case #{1, 2, x, rs...} => x + f(rs)
}
```

which has some severe issues because sets are usually un-ordered and then how can make this work.

**Comment by magnus-madsen** [comment]
I would propose the following:

1. We re-affirm our decision that Flix values support structural equality (except function values - it is a type error to compare them). 
2. We introduce a 'natural order' on all Flix values (again except function values).
3. We implement sets and maps with trees based on this natural order.
4. This enables us to support `fold` and even pattern matching on sets.

The cost of this is:

1. We give up on hash-based implementations of sets and maps at the cost performance (but only for sets and maps in the functional language; the solver itself can still use hashing).
2. We must support structural equality on all values (we sort of already do) and a natural ordering (we don't have that).
3. Native JVM objects lack a natural order, so without additional machinery cannot be allowed in sets/maps. Perhaps a hack based on `hashCode()` or some other means could be used.

**Comment by magnus-madsen** [comment]
Looking at this example again (slightly modified):

```
def f[a](xs: Set[a]): Int = match xs with {
  case #{} => 0 // easy, just check if the set equals the empty set.
  case #{3, 1, 2} => 42 // the set {3, 1, 2} has the natural order {1, 2, 3} so compare that to xs.
  case #{x, y} => x - y // this is okay, x will always be < y according to the natural order.
  case #{2, 1, x, rs...} => x + f(rs) // this okay to: It means, check that the set contains 1 and 2, remove those, then extract the smallest element, and name the rest rs.
}
```

**Comment by magnus-madsen** [comment]
The next question is then how sets and maps should integrate with the logic language.

In IFDS we had the example of a function `def f(...): Set[(a, b, c)]` which was returning a triple of values that needed to be unpacked. For that, we used:

```
P(..., fst(abc), snd(abc), ...) :- A(...), B(...), abc <- f(...)
```

The second question is how to integrate sets and maps with aggregate. Say that I have a relation:

```
rel Students(schoolName: Str, studentName: Str).
```

and I want to compute the student names grouped by school name.

**Comment by magnus-madsen** [comment]
Here is an example of how aggregation could look in Flix (inspired by Eve):
```
rel Students(schoolName: Str, studentName: Str).
rel Result(schoolName: Str, studentNames: Set[Str]).

Result(schoolName, students) :- 
  Students(schoolName, studentName) | students = #{studentName}
```

The vertical bar `|` can be read as "group by". The part `#{studentName}` constructs a singleton set and each of these values are then unioned together to form the aggregated set.

Here is the rule for a weak update (a classic example which requires aggregation):

```
... :- isSingleton(objs), VarPointsTo(localVar, obj) | objs = #{obj}.
```

Here is an interesting way to compute the minimum / maximum distance to a vertex.
```
... :- Path(x, c, y), 
       Edge(y, d, z) | dist = Range(c + d, c+ d)
```
The important point is that `dist` is bound to the least upper bound of a sequence of ranges (as `z` varies over different edges outgoing from `y`).

In eve this style of aggregation is called "clause level".

The form:

```
P(x, y, z, ...) | <name1> = <exp1>, <name2> = <exp2> ...
```

requires that `exp1` and `exp2` be of some lattice type (or a set type). Furthermore, only the variables `x`, `y`, and `z` may occur in `exp1` and `exp2`.

Finally, here is a retarded use of both features:

```
Path(x, w) :- 
  Path(x, y), 
  Edge(y, z) | zs = #{z} // aggregate all one-step reachable vertices in `zs`.
  w <- zs // iterate through each element `w` of the set `zs`.
```

An open question is; what should:

```
R(xs) : - R(x) | xs = #{x}
```
comptue if `R` is empty. In eve this would actually compute `R(#{}`) which sort-of makes sense, but allows a bottom value to appear in the relation.

**Comment by magnus-madsen** [comment]
As for the "loop" syntax:

```
abc <- f(...)
```

It currently has the form `Ident <- Expr` which I propose we replace by `Pat <- Expr` to allow general patterns, so that you can write e.g.

```
(a, b, c) <- f(...)
```
with the requirement (in this case) that `f` has type `Set[(..., ..., ...)]`

**Comment by mhyee** [comment]
>> It's also worth noting that sets and maps could be implemented with (self-balancing) trees.

> That is a very good point. I totally forgot about that. 

I think the takeaway is that many functional languages use trees (so O(log n) is "good enough"), not that we should implement a red-black tree in Flix for the standard library.

> What are the minimal features the compiler must support for sets and maps?

We've discussed this, but I don't think we ever came to a conclusion. If you want a truly minimal set of operations, I think we would need (empty) set creation, adding a single element to a set, and destructing a set into a single element and a smaller set.

Everything else can be implemented in terms of these operations, but it would be convenient for the library to provide more functions. (The library implementation could be based on those three built-ins.)

The list of functions you provided is a good start. [We've also discussed looking at other libraries](https://github.com/flix/flix/issues/36#issuecomment-153141849), for example [Scala](http://www.scala-lang.org/api/current/scala/collection/Set.html), [Clojure](https://clojure.github.io/clojure/clojure.set-api.html), [Haskell](https://hackage.haskell.org/package/containers-0.5.6.3/docs/Data-Set.html), [OCaml](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Set.S.html), and [Racket](http://docs.racket-lang.org/reference/sets.html).

> I believe we discussed the syntax:

I'm undecided on syntax. I'd like to see some consistency with list literals. I know `::` is standard, but Haskell has both `1:2:3:[]` and `[1,2,3]`.

> Then I had this crazy idea that we should allow pattern matching on sets:

My preference is to keep it simple. With lists, you can pattern match for the empty list, and you can pattern match `head::tail`. I think we should do the same for sets. Match the empty set, and match some (possibly unspecified) single element and the rest of the set.

Regarding ordering, Haskell sets are ordered, even for hash sets, because they use trees instead of lists for chaining. But maybe we want `fold` to work consistently. How much do we care about performance? Can we tolerate O(n) worst-case hash table lookup? Do we want to provide an unordered set that doesn't allow `fold`?

The performance cost of tree-based structures is probably OK, since basically all other functional languages do this, and we don't really expect people to be writing complicated Flix code. I guess forcing a natural order on everything isn't too bad, but it's a bit unfortunate we can't support native JVM objects without a hack.

> An open question is; what should `R(xs) :- R(x) | xs = #{x}` compute if `R` is empty.

Nothing? If the result would put a bottom value in a result, then it is dropped. To me, that rule is something like:

```
A(x) :- B(x)
```

where `B` is empty.

For the "loop" syntax, if I have:

```
(a, b, c) <- f(...)
```

where can I use `a`, `b`, and `c`? Are they only allowed in the head, or can I use them in the body? I think I have an example where this might be useful.

**Comment by magnus-madsen** [comment]
>> Are they only allowed in the head, or can I use them in the body? I think I have an example where this might be useful.

Yes (and in the filter function). Otherwise that would force an order on clauses.

**Comment by magnus-madsen** [comment]
Translation for set pattern matching:

```
match xs with {
  case #{} // => set/isEmpty(xs)
  case #{y, ys...} // => let y = set/head(xs); let ys = set/minus(xs, y); ...
}

this should cover about everything.

**Comment by magnus-madsen** [comment]
OK; one more case:

```
match xs with {
  case {3, 2, 1, x, ys...} // has to be rewritten so that 3, 2, 1 are sorted, and then the variable x, and then ys.
}

**Comment by magnus-madsen** [comment]
I am closing this and then opening separate tickets for each issue.
