### ISSUE TITLE
Default Uses

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2495]
Would it make sense to do the following:

- We move everything in `Prelude.flix` into a namespace called `Prelude`.
- We move `Option` into the `Option` namespace (same for List etc).

We *generate* the following uses at the top of every file (or in an initial environment):
- `use Prelude.identity`
- `use Prelude.constant` ....
- `use List.List` ... (Note I would not use `List.map`, just the data type itself.)

(If we had wildcards these would be easier to generate)

What would be the right way to do this?

EDIT: I guess we want something similar for classes etc.

**Comment by magnus-madsen** [comment]
@stephentetley How does this work in Haskell?

I seem to remember that the Map type is actually `Map.Map`. Do newcomers not get confused about that?

Is `List` defined in `List.List`?

**Comment by stephentetley** [comment]
Without module level imports Haskell would be:

~~~

-- Types
type IntToStringMap = Data.Map.Map Int String

-- Functions
push :: Int -> String -> IntToStringMap -> IntToStringMap
push k v m = Data.Map.insert k v m

~~~

When qualification isn't used, an import would typically import the type and the functions from a module:

~~~

import Data.Map(Map, insert)

~~~

`List` is a special case due to the global `[]` syntax.


To me, the Haskell convention feels more scalable for the price of a little convenience as the type is within the module's namespace.

**Comment by magnus-madsen** [comment]
We have recently reworked the namespace (now module) mechanism.
Hence this ticket is most likely no longer relevant.
Feel free to common and/or re-open if it is.
