### ISSUE TITLE
`???` should be effect-polymorphic

### ISSUE THREAD

**Issue by mlutze** [flix/flix#2540]
This gives a type error:
```scala
def foo(): x & Impure = ???
```

```
>> The type scheme: '∀('51845). Unit -> '51845' cannot be generalized to '∀(x). Unit ~> x'.

13 | def foo(): x & Impure = ???
         ^^^
         unable to generalize the type scheme.


  Declared: ∀(x). Unit ~> x
  Inferred: ∀('51845). Unit -> '51845
```

I think this can easily be fixed by giving `???` a free variable instead of calling it pure.

**Comment by magnus-madsen** [comment]
This was like that earlier, but it caused a lot of problems, esp. w.r.t. monomorphization.

**Comment by magnus-madsen** [comment]
The problem is something like this: In the program:

```
let f = _ -> ???
f(123) + f(456)
```

how do we perform monomorphization? Because the expressions `f(123)` and `f(456)` are neither pure nor impure. 

(We can come up with schemes on how to avoid this or do it in a principled way-- but until we should not allow such programs). (Note: We also cannot simply replace Boolean variables by `true` (or `false`) since we intend them for other use cases too. So again, we need a more general solution before we can consider the above.)

**Comment by magnus-madsen** [comment]
At the moment we will not support this. Maybe in the future.
