### ISSUE TITLE
[Review] Library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#255]
We are making great progress on the standard library. My hope is that we will be able to release a version 0.1 with the following data types: `Option`, `Result`, `List`, `Set`, and `Map`. Along with several functions for working with floats and ints. Once the implementation of the library is feature-complete, we should have a process to review that we did not make any mistakes in the design. Most importantly, that function **names** and **signatures** are what we want them to be. (Bugs are a concern too, but easier to fix than say renaming a function).

Obviously there are some limitations that we won't address this time around:
- No type classes.
- Performance of sets and maps.
- Pattern matching on sets and maps (but literals should be supported(!))

Let us start with some name controversy. The Flix names are mostly based on Haskell (and a bit on Scala). What I mean by that is unclear, but I guess an example would be that we use `map` and `flatMap` which are Scala-like, unlike `bind`. On the other hand, many of names for functions on sets and maps (not yet implemented) were taken from Haskell because it has a much richer library. Maybe the rule is: Default to Scala names, and where not available use Haskell names.

Here is a list of things to be discussed:

- `getWithDefault` vs. `getOrElse`? (I think I have a slight preference for default)
- `withDefault` vs. `orElse`?  (I think I have a slight preference for default)
- We offer `foldLeft` and `foldRight`, should we offer `fold` as an alias for `foldLeft`?
- We offer `Option/get` but should we? In Flix all functions should be total and `get` is not. We could remove it and force people to write `let Some(x) = opt` to unpack an option in an unsafe way. Similar choices for `head` and `reduce`.
- We offer `map2` and `flatMap2`, but not `map3` and `flatMap3`. I think this is reasonable, since programmers like to count 0, 1, 2, infinity.
- Scala (through inheritance) and Haskell (through type classes) offer e.g. `init` or `take` on e.g. `Option`, should we do the same? I would say that these functions are very questionable to offer on e.g. `Option`, except if you happen to derive them for free, so we should ***not*** manually add stuff like this.

### Check List

- Sort all functions in namespace by name.
- Ensure that every function has a comment and it renders correctly in flixdoc.
- Ensure consistent naming of functions.
- Update the online documentation with examples?
- Ensure that helper functions are nested within the functions where they are used.
- Check algorithmic complexity.
- ***NEW:*** Check for boolean blindness (e.g. how to interpret `filter[a](f: a -> Bool, xs: List[a])`)
- ***NEW:*** Consider whether to rename some functions that have arguably bad names, e.g. `filter` could be replaced by `select`/`keep`/`retain` and/or include `discard` etc.
- ***NEW:*** Use Flixtest for unit tests.
- ***NEW:*** Ensure that Prelude is reasonable.
- ***NEW:*** Check for tailrecursion.
- Check the signature of List/remove

**Comment by magnus-madsen** [comment]
A controversial suggestion might be to use `!` in partial functions, e.g. `Option/get!(o)`, `List/head!(xs)`, etc.

**Comment by magnus-madsen** [comment]
Here is what Haskell says on its NonEmptyList:

> Errors such as taking head or tail of the empty list in Haskell are equivalent to the dereferencing of the zero pointer in C/C++ or NullPointerException in Java. These errors occur because the true domain of the function is smaller than the function's type suggests. For example, the type of head says that the function applies to any list. In reality, it can only be meaningfully applied to non-empty lists. One can eliminate such errors by giving functions head and tail more precise type, such as FullList a. Languages like Cyclone and Cw do exactly that.

https://wiki.haskell.org/Non-empty_list

Since totality of functions is even more important in Flix (due to non-deterministic evaluation) I am starting to think that we should not offer e.g. `Option/get` as part of the standard library.

**Comment by mhyee** [comment]
> Let us start with some name controversy. [...] Maybe the rule is: Default to Scala names, and where not available use Haskell names.

I think that's a reasonable rule. However, we might want to deviate from Haskell names and make them more "Scala-like." (Or maybe we also deviate from Scala names.) I think internal consistency of our own names is more important than using Scala or Haskell names.

> `getWithDefault` vs `getOrElse`

I don't have a strong preference. `getWithDefault` is probably clearer, but `getOrElse` is shorter. Either way, we should (obviously) be consistent and choose the same for `withDefault` vs `orElse`.

> `fold` as an alias for `foldLeft`

Haskell sidesteps this by providing `foldl` and `foldr` which are short enough to type. But this would break our "use Scala names whenever possible" rule.

> We offer `map2` and `flatMap2`, but not `map3` and `flatMap3`. I think this is reasonable, since programmers like to count 0, 1, 2, infinity.

Agree that this is reasonable. Otherwise, where do we stop?

> Scala (through inheritance) and Haskell (through type classes) offer e.g. `init` or `take` on e.g. `Option`, should we do the same? I would say that these functions are very questionable to offer on e.g. `Option`, except if you happen to derive them for free, so we should ***not*** manually add stuff like this.

I agree. `init` and `take` don't really make sense for `Option`.

> `Option/get` and partial functions

You make a good argument that we should not offer partial functions in the standard library. (Regarding `!` as a symbol for partial functions, because Racket and Ruby (and probably others) use it as a symbol for functions that mutate state. But maybe it's more general and for impure functions.)

> Sort all functions in namespace by name.

On the other hand, grouping by functionality also makes sense. For example, `fst` and `snd` should be near each other, even if they aren't alphabetically.

> Update the online documentation with examples?

Why not put small examples in the flixdoc comments?

---

Note: On GitHub, you can make checklists easily:

```
- [ ] one
- [x] two
- [ ] three
```

Becomes:

- [ ] one
- [x] two
- [ ] three

**Comment by magnus-madsen** [comment]
A few decision then:

**Names are primarily based on Scala, where not available we use Haskell or OCaml names. We avoid symbolic operators (e.g. `>>=`) for the time being. The exception is Cons which is written `::`. We may add symbolic operators later, but if so, like in future versions of Scala, they must *also* have a readable name.

For specific case of `getWithDefault` let us stick to that. I believe Scala used `getOrElse` to sort of imply that the else part is lazily executed, but since this is not the case in Flix, I think `getWithDefault` is most natural. Also, unlike Scala, I don't think there is anything wrong with pattern matching on `Option`.

**As for whether to alias `fold` to `foldLeft` I am not yet sure. I think using `foldl` and `foldr` is bad idea since it is easy to miss the `l` or `r`.** I am leaning towards leaving out any `fold` alias and requiring people to be explicit.

** We will offer `map2` and `flatMap2` but no more. No `map3` or `zip5` or whatever.**

** [Controversial]: The standard library should not offer any partial functions. Doing so would promote bad code. So, functions like `get`, `head` and `tail` are out. However, since namespaces are open, nothing prevents the user from adding `Option/get` if they insist.

We should try to put some examples in the documentation, but let us see how much time we have, and currently flixdoc cannot display code found in comments.

**Comment by mhyee** [comment]
I agree with these decisions, but I have a few comments.

> Names are primarily based on Scala, where not available we use Haskell or OCaml names. 

I think *primarily* is the key word here, in that we are strongly inspired by Scala, but can and will deviate. Do we have any guidelines on when we use Haskell or OCaml names?

> As for whether to alias `fold` to `foldLeft` I am not yet sure. I think using `foldl` and `foldr` is bad idea since it is easy to miss the `l` or `r`.

I think the `l` and `r` are distinct enough, but then again, Haskell does tend to prefer shorter names. (I will take this opportunity to say that having `foldl`, `foldl1`, and `foldl'` is annoying.) Since we're "inspired" by Scala, I suppose it's reasonable to write out the `foldLeft` and `foldRight`.

Regarding the `fold` alias, do we expect `foldLeft` to be used very frequently? (For some definition of "very frequently.") If so, I think we should have the alias. Otherwise, we make people write it out.

> [Controversial]: The standard library should not offer any partial functions. Doing so would promote bad code. So, functions like `get`, `head` and `tail` are out.

I think I'd miss `head` and `tail` because they're so common, but I think requiring/encouraging total functions (and discouraging partial functions) is more important.

> However, since namespaces are open, nothing prevents the user from adding `Option/get` if they insist.

It makes sense for user-defined namespaces to be open, but should standard library namespaces be open? In other words, is it a good thing that users can add `Option/get` if they want?

**Comment by magnus-madsen** [comment]
I have begun a review of the standard library code. I will be opening separate tickets for each issue.
