### ISSUE TITLE
[Smallfix] GenSym

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#266]
Flix is a pure functional programming language. But sometimes you really do want side-effects. Now, I am not saying that we want to introduce global variables or mutable storage, but one common issue is the need to generate fresh symbols (e.g. variables names when implementing an interpreter). The proper way to solve this is to thread an integer variable through the program and properly increment and maintain it when necessary. This is cumbersome, but can be made slightly more elegant with monads (but then you have to write everything in monadic style). 

I am wondering whether we should introduce exactly one construct for this impurity. We could call it `genSym()` (or `!!!GENSYM!!!` or whatever) and it would always just return a fresh integer. This would just require one global counter per Flix instance. We could hide it under a feature flag `--Ximpure` to guarantee safety of regular Flix programs.

**Comment by mhyee** [comment]
Are there specific cases where we want to use this? I guess if you're implementing an interpreter in Flix.

Besides #272, are there any other impure features we might add?

**Comment by magnus-madsen** [comment]
Well, everytime you need a unique identifier, but don't want to pull it out of a monad. Perhaps gensym is the malloc of functional languages...? It may be niche, but it seems very important for implementing PL-type stuff.

**Comment by mhyee** [comment]
Actually, I have a better example. (Because, outside of demos/tutorials, I don't think anybody will be implementing interpreters or compilers *in Flix*.)

When implementing a points-to analysis in the course project, it's necessary to assign a unique identifier for each allocation site in the source program. The obvious solution is to use GenSym. But since that didn't exist, we pushed GenSym out to the fact generator.

(Slightly edited from the actual project code.)

```scala
addFact(s"""AssignNew(MethodName("$methodName"), Ref.Var(MethodName("$methodName"), "$leftName"), Object("${GenSym.fresh("obj-")}"), Type("$rightName")).\n""")
```

Note the call to the Scala method in `Object("${GenSym.fresh("obj-")}")`

**Comment by magnus-madsen** [comment]
It seems we agree that this would be useful. Let us add it under `--Ximpure`.

I think I will add it to the grammar and then later when we get better interop we can refactor.

Are you okay with calling it `genSym!` of type `() -> Int` ?

**Comment by mhyee** [comment]
Yes, that seems reasonable.

If we get more impure and/or library functions (right now only `print!` and `println!` are proposed), we might want to put them under some namespace.
