### ISSUE TITLE
Extended constraint system

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2745]
![image](https://user-images.githubusercontent.com/2287953/143894253-5a593568-f367-4020-b54d-a29eefca9a04.png)

**Comment by JonathanStarup** [comment]
I think this can be solved with an open/close operator. `prog` is something that doesn't know anything about `Extended` and thereby doesn't include it. If prog was closed then we wouldn't be able to compose it with `constraints`. If `prog` is open then it might contain a conflicting type of `Extended` with other terms. If we had open/close operators then prog could be closed (we now know that it doesn't have another definition of `Extended`) and we could then open it, allowing us to compose it with `constraints`. This would create functions where the inputs and the outputs are closed.

It doesn't solve it completely though because we lose the abiltiy to maintain the unknown part `r`.

**Comment by magnus-madsen** [comment]
I don't recall what the issue was.

**Comment by JonathanStarup** [comment]
I think there is general difficulty working with datalog programs across functions. closed functions can't be composed with extra predicates and open (fairly enough) can't do that either. The closed input combined with an open operator could work but then the `rest` of the schema can't be used of course. I think there are ways to solve this, maybe we should have a section on the website and figure out what the best way is

**Comment by magnus-madsen** [comment]
Fixed in master.
