### ISSUE TITLE
`import` doesn't adhere to subject-last

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2848]
When you import a java function like this ` import java.io.PrintWriter.print(String)` it is translated into a function something like this: `def print(p: PrintWriter, s: String): Unit = ...` which breaks the principle of subject last.

**Comment by mlutze** [comment]
I can imagine making then last and having `subj |> func(args)` as the idiomatic equivalent of Java's `subj.func(args)`

But it might also be confusing for some users.

**Comment by JonathanStarup** [comment]
My thoughts exactly. I think maybe the current subject-first is a tad more natural coming from java but not enough to be inconsistent and disallow `|>`

**Comment by magnus-madsen** [comment]
This strikes me as clever, but is it too clever? What do you plan to do about static methods? Will you reverse those too?

**Comment by JonathanStarup** [comment]
> This strikes me as clever, but is it too clever? What do you plan to do about static methods? Will you reverse those too?

There is no reversing, its just whether the object is listed first or last, so since there's not object in a static method there's no change.

**Comment by magnus-madsen** [comment]
Would the signature be reversed too? Or just the actual function and it's type?

**Comment by stephentetley** [comment]
`print` is an imperative function that produces `Unit` so you wouldn't be able to chain prints like this:

> newPrintWriter() |> print("Hello") |> print(" ") |> print("World")

You can do only do a single print...

> newPrintWriter() |> print("Hello")

If you can only a single print then we seem to be running back into the limitations we had with UFCS.

If you wanted to chain prints I think a monad would likely be a more natural fit:

~~~

def tell(s: String): PrintWriterM[Unit] = ...

runPrintWriter(tell("Hello") *> tell(" ") *> tell("World"))

/// Where (*>) is applicative seqR / monadic sequence (>>)

~~~

I think this combinator would be work to adapt `Unit` producing functions to return the "subject" rather than Unit: 

> pub def >*>(x: a, f: a -> Unit & ef): a & ef = {let _ = f(a); a}

But now I think you have two pipeline notations without the useful distinction of one being applicative /monadic:

> newPrintWriter() >*> print("Hello") >*> print(" ") >*> print("World")

**Comment by JonathanStarup** [comment]
I think it still works for java code written with this "builder" intent. Take `StringBuilder.append(String)` with the current order it couldn't be used in a pipe. If we put the object last it could. The pipe could mimic the java dot as @mlutze said.

To be precise: The import statement would not change, say `import a.b.C.function(Arg1, Arg2, Arg3)` would be used in flix as the function `def function(a1: Arg1,  a2: Arg2, a3: Arg, c: C)` with whatever return type. The current interpretation is `def function(c: C, a1: Arg1,  a2: Arg2, a3: Arg)`

**Comment by magnus-madsen** [comment]
So, it boils down to whether Java follows the builder pattern?

**Comment by JonathanStarup** [comment]
yes, in regards to chaining calls.
