### ISSUE TITLE
Introduce Input/Output Datalog Predicates

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3051]
From a brainstorm session:

```
    let p = Input => Output = #{
        LocalVar(x) :- Input(x).
        Output(x) :- LocalVar(x).

        Local("hello").
    };
```

here the type of `p` does not refer to `LocalVar` which is alpha renamed to make it truly local. (The types of the terms are left unspecified since they can be inferred).

Question: Is there a difference between input and output?

- The type could track that the input must not occur in the head of a rule? 
- The type could track that the output must not occur in the body of a rule?
- A syntactic check could enforce the above, but for limited gain?

Another construct that was proposed was:

```
let p3 = p1 <+> p2 <+> #{ Input2(x) :- Output(x). } // plus some elimination of Input2 and Output.
```

**Comment by JonathanStarup** [comment]
Another solution could be to hide select predicates instead of showing select prediates. `!` prefix is a hidden predicate.
```flix
let p = #{
    !LocalVar(x) :- Input(x).
    Output(x) :- !LocalVar(x).

    !Local("hello").
};
```
Upside: this reduces the friction for new programmers (you only need to learn about hiding things when you get a stratification error)

Downside: This seems inconsistent with public/private methods where the "safe"/encapsulated choice is implicit.

**Comment by JonathanStarup** [comment]
The "inline" syntax could also be used for visible predicates (with `!` prefix or something like that).

**Comment by JonathanStarup** [comment]
Never the less: we have a set of predicates that should not collide with any other predicate in the program. This can be achieved by renaming the predicates. If this is done statically it means that the hidden predicates of a Datalog expression will not collide with the predicate names of other expressions. This only leaves out collisions between values of the same expression. This doesn't seem like it should be a problem but look at this example:
```flix
pub def main(_args: Array[String]): Int & Impure =
    println("test");
    let instance1 = p(x -> x+1);
    let instance2 = p(x -> x-1);
    query #{B(2).}, instance1 select x from A(x) |> Array.toList |> println;
    query #{B(2).}, instance2 select x from A(x) |> Array.toList |> println;
    query #{B(2).}, instance1, instance2 select x from A(x) |> Array.toList |> println;
    0
  

def p(f: Int32 -> Int32): #{A(Int32), B(Int32) | r} =
  #{
    A(f(x)) :- Local(x).
    Local(f(x)) :- B(x).
  }
```
`instance1` uses `Local` to add 1 and then `A` adds 1 to the number again, effectively adding two to every element of `B`.

`instance2` uses `Local` to subtract 1 and the `A` subtracts 1 to the number again, subtracting two to every element of `B`.

This means that the first query only contains `A(4)` and the second only has `A(0)` (since `B` only contains 2).

The combined query also contains `A(2)` since the local predicate of the two instances interfere to obtain the behaviour or adding and then subtracting or subtracting and then adding. This result would not exist if the local predicates are renamed at runtime. 

What do you think @magnus-madsen?

**Comment by magnus-madsen** [comment]
What would:
```
local A(x, y) :- B(x, y).
C(x) :- A(x).
```
mean? Here `A` is used inconsistently. I think it would be better to think of `I => O #{ ... }` as alpha renaming everything inside `#{ ... }` which is not named `I` or `O`.

**Comment by magnus-madsen** [comment]
In the second example, I think that `instance1` and `instance2` are:

```
instance1 =  #{
    A(f(x)) :- Local123(x).
    Local123(x + 1) :- B(x).
  }
instance2 = #{
    A(f(x)) :- Local123(x).
    Local123(x - 1) :- B(x).
  }
```

The union of these is:

```
#{
    A(f(x)) :- Local123(x).
    Local123(x + 1) :- B(x).
    A(f(x)) :- Local123(x).
    Local123(x - 1) :- B(x).
  }
```

which is what we want, right?

**Comment by magnus-madsen** [comment]
I think for safety we should do the alpha renaming at runtime. Thus a Datalog value becomes: 

```
enum Datalog {
  case Datalog(/* visible pred syms*/ List[PredSym], List[Constraint])
  case Union(Datalog, Datalog)
}
```

then this gets flattened and alpha-renamed.

**Comment by JonathanStarup** [comment]
> What would:
> 
> ```
> local A(x, y) :- B(x, y).
> C(x) :- A(x).
> ```
> 
> mean? Here `A` is used inconsistently.
> 
> I think it would be better to think of `I => O #{ ... }` as alpha renaming everything inside `#{ ... }` which is not named `I` or `O`.

It could be required to be used consistently in the same way that lattice predicates are handled.

**Comment by JonathanStarup** [comment]
> The union of these is:
> 
> ```
> #{
>     A(f(x)) :- Local123(x).
>     Local123(x + 1) :- B(x).
>     A(f(x)) :- Local123(x).
>     Local123(x - 1) :- B(x).
>   }
> ```
> 
> which is what we want, right?

I don't know. Runtime renaming would make it this: (assuming they still come from the p function, i.e. the same expression)
```
 #{
    A(f(x)) :- Local123$1(x).
    Local123$1(x + 1) :- B(x).
    A(f(x)) :- Local123$2(x).
    Local123$2(x - 1) :- B(x).
}
 ```
