### ISSUE TITLE
Pattern Matching Lambda

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#316]
I often find myself writing something like:

```
let f: PromiseValue -> Set2[Outcome] = pv -> match pv with {
  case Pending => ???
  // TODO: Rest
};
```

here the `pv -> match pv with` seems a bit redundant.

We already have syntax for matching on a single case:

```
List.map(match (x, y) -> x + y, xs)
```

can we come up with something for this case?

**Comment by jmittert** [comment]
Since we already have the lambda case, we could extend that to have multiple cases. Something like `match { Some(x) -> 1; None -> 2}`, then you could write

```
let f: PromiseValue -> Set2[Outcome] = match {
    Some(x) -> 1;
    None -> 2
}
```
Which would just work after extending the lambda match. However, it seems inconsistent then that the regular pattern match requires `case` and the lambda match wouldn't. Maybe require case for more than one possibility? Or conversely, require case, but have it be optional in the singleton case.

```
let f: PromiseValue -> Set2[Outcome] = match {
    case Some(x) -> 1
    case None -> 2
}
```
and 
```
List.map(match {
    case Some(a) -> 1
    case None -> 0
}, xs)
```

It's semantically nice, since `match x with {` would just be sugar for `(match {... })(x)`.

**Comment by magnus-madsen** [comment]
This should be easily implementable by adding a case similar to:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L632
