### ISSUE TITLE
[Frontend] Check for Dead and Unreachable Code

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#320]
***What:***
Add a compiler phase to detect and report dead and unreachable code.

***Prerequisites:***
We need a mechanism to instruct the compiler that an entity is part of a library and hence is allowed to be dead or unreachable. A possible solution is to add an annotation or modifier `pub` which can be placed on any `namespace` or `def` to mark it as public and hence to always consider it as reachable.

***Detailed Description:***
Introduce a compiler phase either immediately after the resolver or the typer to check for dead and unreachable code. This phase has some similarity to the `TreeShaker` but its scope is much broader.

The phase should issue an error message if the program contains any: 

- Unused variables, i.e. formal parameters, let-bound variables, or pattern variables which are unused.
- Unused functions, i.e. functions that are declared, but never called from a public function.
- Unused enums and types, i.e. enums or types that are declared but never referenced. 
- Unused cases, i.e. an enum is declared, but not all its cases are references.
- Unused relations/lattices, i.e. relations or lattices are declared, but never used in a constraint.
- A relation/lattice only appears in facts, but never in constraints.
- Unused type variables, i.e. type parameters of a definition or enum which are not referenced.
- Singleton variables in constraints, i.e. a variable of rule must appear at least *twice*.
- A duplicate atom/predicate in a constraint.

***Technical Challenges:***
- Ensure that the AST is traversed at most twice.
- Ensure that the AST is traversed at most once for public entities.
- The phase should be written in monadic style similar to e.g. `Resolver`.

**Comment by mhyee** [comment]
I guess the questions are "do we want to adopt this for Flix (and why)," "how aggressive is the analysis," and "is it a warning or a fatal error."

I think it's a reasonable thing to do, since unused code has a tendency to be broken code, and we also reduce compile time and the size of generated code. [Even Java forbids unreachable statements](http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.21) (though unused classes are OK).

But I can imagine a situation where the programmer is sketching out a Flix program, and has a bunch of unused functions/enums/params/etc., and then has to annotate every single one. This seems pretty annoying.

Would it make sense to---in addition to having annotations---provide a flag to disable the unused code check?

**Comment by magnus-madsen** [comment]
Most of this has been implemented in master.
