### ISSUE TITLE
BoolOp type class

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3245]
To allow overloading the boolean operators `not`, `and`, `or`.

**Comment by magnus-madsen** [comment]
I can think of two significant drawbacks:

- Type errors will be much more messy.
- I cannot think of a single data type I would want to implement `not`, `and`, and `or` on. (And even if I could, would I really want to overload the built-in Boolean operators??)

For `+` it makes sense because we are forced into that situation because we have both integers and floating points (and several of each). For Booleans this is not the case.

**Comment by mlutze** [comment]
My use case is for set-like operations. It's handy to have the built-in precedence.

But I agree that having messier type errors is a pretty major disadvantage.

**Comment by magnus-madsen** [comment]
What is `not <yourset>`?

**Comment by magnus-madsen** [comment]
I would recommend:

```
use Set.intersect;
xs `intersect` ys
```

**Comment by mlutze** [comment]
`not` more-or-less represents set complement.

So far I've indeed been using backticks, but I feel that symbols could be a lot cleaner.

The [literature](https://www.irif.fr/~gc/papers/covcon-again.pdf) that I'm following uses `|` and `&` and `not`. (See also https://github.com/flix/flix/issues/3244).

**Comment by magnus-madsen** [comment]
I propose not to do this :)
