### ISSUE TITLE
Design of Regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3601]
We are updating all mutable data structures to carry a "region" or "lifetime" parameter. 

Regions will allows us to use local mutation (in the spirit of the ST Monad from Haskell).

In other words, we will have `Array[t, r]`, `Ref[t, r]`, and e.g. `MutList[t, r]` for some region variable `r`.

Immutable data structures stay the same.

Using regions, we can write a pure function like:

```scala
def deduplicate(l: List[a]): List[a] with Order[a] =
    /// Declare a new region `r`.
    region r {

        /// Create a new `MutSet` at region `r`.
        /// This will be used to keep track of
        /// unique elements in `l`.
        let s = new MutSet(r);

        /// The lambda used in the call to `filter`
        /// would be impure without a region.
        List.filter(x -> {
            if (MutSet.memberOf(x, s))
                false // `x` has already been seen.
            else {
                MutSet.add!(x, s);
                true
            }
        }, l)
    }
```

where `deduplicate` is pure.

(Thanks to Jakob for the nice example.)

I would like some input on various design choices and questions.

# Question 1: What should we name the global region?

We want to have a global or "static" region whose lifetime corresponds to that of the entire program. In a sense, this region corresponds to array and reference uses being `Impure` today.

What should this region be called and how should it be written?

The current proposal is "static" written as `static`.

Then we can have type aliases:

```scala
type alias StaticArray[t] = Array[t, static]
```

Alternative names include `global` or `heap`. One issue with `static` is that it could potentially be mistaken for a type variable. 

# Proposal 2: Region parameters for `toXYZ` functions?

A function that wants to allocate a mutable data structure needs to know in what region to allocate. 

This means a function such as `toMutSet` will need a region parameter (e.g. `r: Region[r])`). 

On the other hand, a function such as `toList` will *not* need a region parameter (because it does not allocate mutable memory). 

Are we okay with this inconsistency?

Alternative: We do not have ways to quickly convert to mutable collections. Instead the programmer should write:

```
let s = new MutSet(r);
MutSet.addAll!(otherCollection)
```

# Question 3: What should be the "primary" way to allocate a mutable data structure?

We have a `Newable` type class which allows one to write `new MutSet(r)`. Is that ok?

What about `MutSet.empty()`, `MutSet.new()`, `MutSet.range` and so forth? Do we want to delete them?

# Question 4: Do we want region parameters to be (partially) implicit?

Flix does not have implicit parameters (and maybe should not have), but we could hard-code support for implicit region parameters under certain circumstances. For example, we could allow:

```scala
region r {
  let a = [1, 2, 3] // automatically use nearest region
}
```

We would also allow:

```scala
region r {
  let s = new MutSet();
}
```

If so, do we want a region block to be able to omit its name? (Since the name is now immaterial?)

# Question 5: Do we want functions to implicitly introduce a region?

In other words, every function could start by opening a new region scope:

```scala
pub def foo(): Int32 = 
  let a = [1, 2, 3];
  a[2]
```

would work out of the box. 

This could get confusing if there is a region parameter. (Would we then use that instead?)

What would be the name of this region?

# Question 6: Naming

We have a the following principle: *Destructive operations are marked with '!'*. In Flix, every destructive operation is suffixed with an exclamation point. For example, Array.reverse(a) returns a new array with the elements of a in reverse order, whereas Array.reverse!(a) destructively re-orders the elements of a. Note: This principle applies to destructive operations that operate on data structures, not to impure functions in general, e.g. Console.printLine.

Given that soon the effect system will have the same information, do we want to (a) drop this principle or (b) enforce it?

**Comment by mlutze** [comment]
> One issue with static is that it could potentially be mistaken for a type variable.

Why not capitalize it? (`Static`)

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc @ninaandrup @stephentetley @nicdard I would like your input :)

**Comment by JonathanStarup** [comment]
**Question 2:** I support the regions on the toMutSet methods.
**Question 3:** empty() and new() should be deleted but range seems fine, range just has a region.
**Question 4:** "do we want a region block to be able to omit its name?" It seems natural to support region _ { .. }
**Question 5:** I think for inference we should probably base it on case studies to see what code actually looks like. I think it could be nice to have an implicit region around the method body. We could have this happen only when no other regions are present (arguments or programmer inserted region r { .. }).
**Question 6:** I think we should drop it. It should either be moved to a @destructive tag or just be seen in the type in my opinion.

**Comment by nicdard** [comment]
**Question 1**: I think that static could be confusing, as there are different usages of the term in other programming languages (such as static functions in C). Global sounds good to me, and resemble `global` keyword in python. Also `heap` seems good. I would also use a capitalize name as suggested by @mlutze since this is in line with current usage of `Pure` and `Impure` and underline that it is kind of a built-in region not one defined by the programmer.
**Question 2**: I don't personally think that there is an inconsistency, as the name of the function already explicitly contains `Mut`, and only those ones will require the region parameter. Indeed, I think this will help clarify the usage of region related to mutability of data structures. Question: How does region interact with lazy data structures?
**Question 3**: Sorry for this, what does `MutSet.range` does specifically?
**Question 4**: This makes me think a bit to Kotlin soped functions feature. I like @JonathanStarup proposal to support `region _ { .. }` but I still would require the `_` to be passed as argument in calls/constructors that need it.
**Question 5**: At first sight I don't like the feature, as region is a way of manually control lifetime and interaction of memory and this feels a bit against the idea. It seems more consistent to me to introduce a set of semantic rules over regions (I am thinking towards rust now, don't know if this makes sense :sweat_smile: ) more than implicit mechanisms first, then we can surely have shortcuts for good and recurring patterns. I need to mention that I personally like minimal designs, and I kind of prefer explicit clarity over implicit conventions. I agree with @JonathanStarup that we should base this on case studies however.

**Comment by mlutze** [comment]
##### Question 1: What should we name the global region?
`Global` feels the most natural to me.

##### Proposal 2: Region parameters for toXYZ functions?
> Are we okay with this inconsistency?

I'm okay with it.

> Alternative: We do not have ways to quickly convert to mutable collections.

I dislike this alternative.

##### Question 3: What should be the "primary" way to allocate a mutable data structure?
`new` keyword is nice, but what happens when we want a reference to a function constructing new stuff?
```scala
/// creates a list whose contents are the value of `f()` called iteratively
def mkList(len: Int32, f: Unit -> a & ef): List[a] & ef =
    if (len <= 0)
        Nil
    else
       f() :: mkList(len - 1, f)

mkList(45, () -> new MutSet(Global)) // a little cumbersome to write the lambda
mkList(45, MutSet.new(Global)) // maybe a little nicer?
```

Notably, Java found writing the constructor lambdas too cumbersome so they have constructor references (`StringBuilder::new`)

##### Question 4: Do we want region parameters to be (partially) implicit?
I'm still on the fence about this. Is there some very simple syntax we can use to be explicit that the region must be inferred here?

##### Question 5: Do we want functions to implicitly introduce a region?
> What would be the name of this region?

`Local`?

##### Question 6: Naming
> (a) drop this principle or (b) enforce it?

Drop it. This frees up `!` for some future thing to track that isn't expressed by the type system.

**Comment by ninaandrup** [comment]
**Question 1**: I think `global` would make more sense to me, if I just read it without explanation. Does the `static` keyword not clash with `static` in imports from java?
**Question 2**: The inconsistency makes sense, and I think it is okay.
**Question 3**: I do not really have an opinion on this.
**Question 4**: I think it makes sense to be able to write it like this. But on the other hand, if it is a bigger block of code with more regions, the code could become difficult to read and figure out.
**Question 5**: I'm not sure about this.
**Question 6**: maybe drop it for simplicity.

**Comment by stephentetley** [comment]
Question 6 
I'm happy with dropping the bang suffix for functions that do imperative update. I've probably not followed the naming scheme properly when writing monadic-imperative library code even though I was the person who suggested the convention.

One question I have - do imperative but "non-collection" types like `StringBuiler` get associated with a region?

**Comment by magnus-madsen** [comment]
> One question I have - do imperative but "non-collection" types like `StringBuiler` get associated with a region?

Yes, that would be plan. Then we can have pure, but imperative toString functions.

**Comment by jaschdoc** [comment]
**Question 1**
I like `Global` much more than `static`. Mental model wise it is much clearer: "It's the global region".

**Question 2**
I agree with Nicola that it isn't *really* an inconsistency so I support regions on `toXYZ`.

**Question 3**
I like `new MutableDatStructure(r)`.

I'm torn on `range` and `init` etc. I don't like extending functions with an additional parameter just because they operate on mutable data structures, but these functions are also really handy.
It also seems to break the subject last principle and could lead to confusion when using the library with lots of pipes `|>` but I haven't personally run into this issue yet, so I'm not sure how much this would be the problem.
Besides, the type checker would catch an error like that (i.e. `new MutMap(r) |> MutMap.range(a, b);` this doesn't make sense now and wouldn't change with the additional region parameter.

**Question 4**
I like that the default behavior is to use the nearest region. I think it's fair to assume that when you declare a region you'd want mutability to be restricted to that region. This eliminates lots of `@ r` annotations that become cumbersome to write.
It also makes much more clear when something is **not** local to that region as it's annotated with either `@ Global` or `@ r1`.

**Question 5**
I like the `Local` name that Matthew suggested. I think my argument above also holds for this and if there is region parameter, the programmer would still have explicitly annotate mutability in that region with `@ r` (assuming the parameter name is `r`).
If we support **Question 4** then not supporting **Question 5** seems like an inconsistency.

**Question 6**
I agree `!` should removed and handled by effect handlers.

**Other comments**
Why do we have to carry a region value around as parameter everywhere? Isn't it possible to implement it entirely in the type system like Rust lifetimes?

Also does it make sense to have syntatic sugar
like `new Global MutDeque()` or `new r MutDeque()` which would desugar into `new MutDeque(Global)` and `new MutDeque(r)` respectively. Maybe just `Global` example would make sense. Haven't really thought too much about this.

**Comment by magnus-madsen** [comment]
# Question 7: Do region variables go first or last?

Jakob writes:

Come to think of it, I think regions should be **before** the subject in the parameter order so we can still use `|>`:
```scala
pub def toArray(c: Chain[a], r: Region[r]) : ScopedArray[a, r] \ Write(r) = ??? // breaks pipelines like below

pub def sort(c: Chain[a]): Chain[a] with Order[a] = region r {
    c |> toArray(r) |> Array.sort |> Array.toChain // broken, should be toArray(c, r) with current order
}
```

**Comment by jaschdoc** [comment]
> If regions are not last, I am not sure we can support implicit regions.

What if they're consistently the first parameter?

**Comment by mlutze** [comment]
##### Question 7: Do region variables go first or last?
I am strongly in favor of *first*

**Comment by magnus-madsen** [comment]
> 

What about array literals and refs. How would you change the syntax? `ref r @ 123`?

**Comment by mlutze** [comment]
> > I am strongly in favor of first
> 
> What about array literals and refs. How would you change the syntax? `ref r @ 123`?

Does that have to change?

**Comment by magnus-madsen** [comment]
> Does that have to change?

Not necessarily. But it would seem slightly inconsistent?

**Comment by magnus-madsen** [comment]
We have `static` (which will probably become `Static`). We could also have `Local` which would always refer to a local region belonging to each function and would always be in scope.

**Comment by magnus-madsen** [comment]
I have made a few decisions.

These are not set in stone, but I want to move the code in that direction. We can revisit if needed.

1. The global region will be named `Static` with upper case S. 

2. All `toXYZ` functions (for mutable data structures) will take a region parameter.

3. Undecided.

4. Undecided. 

5. No.

6. We keep the current naming. We still have to distinguish between `Array.reverse` and `Array.reverse!` (!)

7. We should follow the subject-last principle, hence regions should not be the last argument, they should probably be the first.

**Comment by stephentetley** [comment]
> Question 7: Do region variables go first or last?

Having done some work converting my code to use regions (with plenty of work still pending...) I think implicit params would be a very nice way of working with regions when the region needs to be threaded through a series of functions (like a parser). Though, it would be a lot of work to add this to the compiler.

**Comment by magnus-madsen** [comment]
> > Question 7: Do region variables go first or last?
> 
> Having done some work converting my code to use regions (with plenty of work still pending...) I think implicit params would be a very nice way of working with regions when the region needs to be threaded through a series of functions (like a parser). Though, it would be a lot of work to add this to the compiler.

Do you have some code we can look at?

**Comment by stephentetley** [comment]
> Do you have some code we can look at?

Thanks Magnus, I'll pick some out when I've got my work repository to compile again.

**Comment by magnus-madsen** [comment]
Hopefully at least there is a feeling of things moving in the right direction.

**Comment by magnus-madsen** [comment]
Available in master.
