### ISSUE TITLE
Investigate dbg! macro

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3671]
See https://doc.rust-lang.org/std/macro.dbg.html

**Comment by JonathanStarup** [comment]
I think `bug!` and `unreachable!` could be handled the same way. Right now they are not really usable because 1) the error site is now the bug method and 2) the call stack is the jvm call stack so tracking the flow backwards is not accessible. 

These could be macros similar to dbg or could use dbg! maybe.

Maybe they should be deleted and holes should just include better information / a string argument and use dbg

**Comment by magnus-madsen** [comment]
We now have `debug`, but its not integrated with `bug!` etc.
