### ISSUE TITLE
[Library] Discussion: Map.get vs. Map.lookup

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#378]
The core operations of Map are currently named: `Map.get`, `Map.insert`, and `Map.delete`. In #372 there is a proposal to rename `Map.delete` to `Map.remove`. Here I want to discuss whether `Map.lookup` would be a better name?

**Comment by mhyee** [comment]
Scala has `get`, Haskell as `lookup`, OCaml has `find`.

Again, we should be internally consistent. If we change `delete` to `remove` and `insert` to `add`, we should probably change `get` to `find` (to be consistent with OCaml).

If we don't do the rename, I think `get` is fine, even though `lookup` would be consistent with `delete`/`insert`. `get` is what Scala uses, and we fall back to Haskell for `delete`/`insert` since Scala uses symbolic names.

**Comment by magnus-madsen** [comment]
I really like `get/put` but we will stick with `insert/remove` for now.
