### ISSUE TITLE
Add `Par` Expression

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4286]
I want to add two new constructs: `ParApply` and `ParTag`. The latter is very similar to the former, but I suggest to implement `ParApply` fully before tackling `ParTag`. 

Both constructs should exists until the Lowering phase where they are translated. 

We allow a programmer to write:

```
par exp1(exp2, exp3, ...)
```

The type system treat this as a normal call, except that `exp2, ... expn` must be pure.

During the lowering phase, we translate `par exp1(exp2, exp3, ...)` to:

```
{
let ch1 = channel 1;
let ch2 = channel 1;
let ch3 = channel 1;
spawn ch1 <- exp1;
spawn ch2 <- exp2;
spawn ch3 <- exp3;
let tmp1 = <- ch1;
let tmp2 = <- ch2;
let tmp3 = <- ch3;
(tmp1)(tmp2, tmp3)
}  as & * the effect of tmp1 to tmp3*
```

**Comment by magnus-madsen** [comment]
@jaschdoc I think this should be a fun task (after/during upcast work) :)

**Comment by athas** [comment]
Why mix it up with function application at all, instead of just returning a tuple?

**Comment by magnus-madsen** [comment]
> Why mix it up with function application at all, instead of just returning a tuple?

It's a good point! If you think about it, parallelism is just the ability to write `exp1 || exp2 || exp3` (possibly with some mechanism for communication). Taking this a step further, you would want a "parallel tuple": `par (exp1, exp2, exp3)`. Then, if you were in Standard ML, you could write `f (par (exp1, exp2, exp3))` and you would have what I propose... But unfortunately Flix has multi-argument functions (and not functions taking tuples), hence this would not be as elegant. Now why do it for calls? I don't have a good answer, except its often were funny stuff happens: call-by-value, call-by-name, etc. etc. Finally, I believe it will allow me to write a recursive parallel List.map function is a straightforward manner and explain it to 1st year student. 

Anyway, its still an experiment! If its no good, we can take it out.

**Comment by athas** [comment]
Surely just having parallel tuples also lets you write a parallel Lisp.map?  Pseudocode:

```
let (y,ys) = par(f(x),List.map(f,xs))
Cons(y,ys)
```

Although if this `par` construct always returns a tuple, you might as well just write ``Cons(par(f(x),List.map(f,xs)))` (maybe you'll need some curry/uncurry stuff; I can never keep track of how tuples interact with using parens for function application).

**Comment by magnus-madsen** [comment]
In fact, we could probably have `Cons(par (f(x), List.map(f, xs))`. Hmm. I will think about it.

**Comment by magnus-madsen** [comment]
@athas You convinced us to start with tuples and then (maybe) go from there 👍 

While I have you on hand, do you think such a "short" parallel construct `par (exp1, exp2)` should enforce purity of exp1 and exp2 or not? Second question, do you think `par (exp1, exp2)` should *only* run in parallel if `exp1` and `exp2` are pure (i.e. its behavior is now *overloaded* based on the purity polymorphic stuff I presented). Third question (ok I need to stop), we have channels and spawn, and now soon this par (as a more lightweight construct), what are the other core functionality you think we should be providing in a *high level* language?

**Comment by athas** [comment]
1. Yes, of course it should enforce purity.  Impure parallelism is a recipe for race conditions.
2. I don't think it should be overloaded, because then refactoring might result in something pure becoming impure, and suddenly it's not parallel anymore, which can result in a significant slowdown.  You might spend quite some time figuring out which `par` is now not actually parallel.
3. Tricky question with no easy answer.  `par` is basically futures, which are wonderful because they are deterministic.  You can build lots of other things on top of this; probably *most* things actually, although some might need side effects.  E.g. an efficient parallel `map` on arrays probably cannot be built on `par`.  The only other potential problem is granularity control of parallelism, but that's more of an implementation challenge.  I'm not quite sure how your channels work, but they sound more like concurrency than parallelism.  You might need both, for different purposes.

I recommend keeping things as simple as possible.  `par` is something you'll definitely want and it is very well-behaved.  In the future, when you need something more sophisticated, you can re-define `par` in terms of those lower-level primitives, but `par` itself will never become a problem.  Adding something more sophisticated right now, without having a full picture, is almost guaranteed to lead to regrets down the line.

**Comment by magnus-madsen** [comment]
Thanks-- those are some useful considerations. We will forge ahead with par and make it require purity.

**Comment by magnus-madsen** [comment]
Just to update on what I would like:

Add `par exp` for any exp. Require `exp` to be pure. After type checking rewrite `par exp` (where exp is a tuple, tag, or apply) to use parallel evaluation. Report an error for any other expression. https://doc.flix.dev/parallelism.html
