### ISSUE TITLE
Rework Concurrent/*

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4436]
I suggest to:

- [ ] Remove `Concurrent/Channel/Ticker` (this is broken because there is no support for cancellation).
- [ ] Remove `Concurrent/Channel/Timer`.
- [ ] Hide everything else in `Concurrent` (i.e. mark `@internal`.).

For the two first two, I don't see how they are useful or even well-designed.

**Comment by JonathanStarup** [comment]
* Ticker can be stopped by the stop function, it only breaks if the ticker channel is full, which can be solved if you can put in select. I think Ticker needs this to be improved. I agree that it's probably too fragile to be worth having atm but useful in a better design for fixed rate loops. 
* Isn't Timer needed to be able to timeout channel operations? you can't use sleep for that directly because you need to have a select case, so you'd have to reimplement Timer yourself.

**Comment by magnus-madsen** [comment]
Fixed in master.
