### ISSUE TITLE
Re-design `par` construct

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4609]
I would like to re-design the `par` construct as follows:

- [x] We keep the `par(exp1, exp2, ... expn)` expression.
  - [x] The compiler should be smart enough that if `exp_i` is a variable or literal, no thread is spawned.
  - [ ] The compiler should only spawn `n - 1` threads.
- [x] We drop the `par exp1(exp2, exp3, ..., expn)` expression (i.e. `ParApply`).
- [x] We add a new expression of the form `par (x <- exp1, y <- exp2, ..., expn) yield exp`. 
  - [ ] The compiler should spawn `n - 1` threads.

I suggest to implement each of these changes in small and incremental PRs.

EDIT: I suggest to start by removing features and tidying up. Then adding new stuff.

**Comment by magnus-madsen** [comment]
@mlutze Acceptable? :)

**Comment by magnus-madsen** [comment]
@jaschdoc Meaningful?

**Comment by jaschdoc** [comment]
Should `x` be a pattern in `par (x <- exp, ...) yield e`?

**Comment by mlutze** [comment]
> Should `x` be a pattern in `par (x <- exp, ...) yield e`?

I vote "yes"

**Comment by magnus-madsen** [comment]
if it can be in `for` then yes

**Comment by jaschdoc** [comment]
I've been toying with the idea of having a `par-select` expression, or just adding a variant of the select expression  that would accommodate the "throw-more-threads-at-the-problem" pattern.
This would look something like
```flix
par (pat <- exp; ... ) select {
    pat => exp
    ...
    pat => exp
}
```
We could potentially also rename this to `select-yield`.

I'm not sure if this would really make sense for pure expressions within the parentheses or it would require or at least allow for a `NonDet` effect.

The only example I can come up with right now, is the case where you want to find prime numbers. Of course, this would be a nondeterministic function, but you could easily imagine, throwing more threads, say 3, at the problem, and then selecting the first case that returns.

The obvious problem is that it's not wildly different from the current select expression that we already have, however, I could see this being more convenient to write but then again, this may only be a niche use case.
The only real upside is that it spares the programmer from writing code that has to set up channels.

Do you have any thoughts on this?

**Comment by magnus-madsen** [comment]
Question: What problem are you trying to solve?

**Comment by jaschdoc** [comment]
Apologies for being unclear. The pattern / problem is wanting to use more threads to solve the same problem and selecting the first available result. In other words, I just want to use redundant threads hoping that one of the threads is much faster than the rest.

Finding random primes comes up as an example: Give me a random prime number of `k` bits. This obviously has some non-determinism attached to it but makes sense that you would want to add more threads.
Another example (but this involves IO) is contacting more web servers with the same request and returning the first available result (this obviously gives a response time of the fastest connection).

So the problem is: "Give me redundancy by using more threads and give me the first result!" or "Do this several times, I don't want to think about setting up channels"

**Comment by magnus-madsen** [comment]
@jaschdoc How far did we get with this?

**Comment by jaschdoc** [comment]
`ParYield` is almost finished. We just need the optimization that it doesn't spawn threads for variables and literals.
`ParTag` still spawns `n` threads (not `n - 1`)  and still spawns threads for variables and literals.

I think once `ParYield` is done, `ParTag` should be easy to finish since it should more or less just call the same helper functions as `ParYield`.

By the way, was there a mismatch of communication on https://github.com/flix/flix/issues/4609#issuecomment-1317148973 ?

**Comment by magnus-madsen** [comment]
> So the problem is: "Give me redundancy by using more threads and give me the first result!" or "Do this several times, I don't want to think about setting up channels"

This is a classic and interesting programming pattern, but it requires support for cancellation which is more than what the `par` construct can offer.

**Comment by jaschdoc** [comment]
Ah okay yeah I think I spoke briefly with Matt about this. Maybe this could be an idea for some of the imperative features of the language? Someone would have to implement it and there are plenty of other things to do I suppose :smile:

**Comment by jaschdoc** [comment]
Update on the situation

- [x] We keep the par(exp1, exp2, ... expn) expression.
    - [ ] Do not spawn threads for variables or literals
    - [ ] The compiler should only spawn n - 1 threads. https://github.com/flix/flix/pull/5070
- [x] We drop the par exp1(exp2, exp3, ..., expn) expression (i.e. ParApply).
- [x] We add a new expression of the form par (x <- exp1, y <- exp2, ..., expn) yield exp.
    - [x] The compiler should spawn n - 1 threads.
    - [x] Do not spawn threads for variables or literals

**Comment by magnus-madsen** [comment]
Are we done then?

**Comment by jaschdoc** [comment]
One last small step: not spawning threads for vars or csts in ParTag

**Comment by jaschdoc** [comment]
Posted status above
