### ISSUE TITLE
[CodeGen] Singleton cases

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#463]
For the enum:

```
enum List[t] {
    case Nil,
    case Cons(t, List[t])
}
```

the code generator emits:

```
public final class Nil implements EnumInterface {
    public Object value;
    public String tag;

    public Nil(Object var1) {
        this.value = var1;
        this.tag = "Nil";
    }
    ...
```

it would be better if we could use the singleton pattern:

```
public final class Nil implements EnumInterface {
    private static Nil INSTANCE = new Nil()
    // private constuctor
    // public getInstance
    ...
```

**Comment by FlaminGuy** [comment]
There is one problem here and that is there is no way to find out the difference between case `Red` and case `Some(Unit)` in `CodeGen` phase based on the data we have.
Now if don't create an `INSTANCE` for `Some` we are going to fail since `CodeGen` will try to access this field. 
One thing we can do is that for every enum case that the field is can be `Unit` we can add an `unitInstance` static field which is already initialized with a Unit.      
Plus side is we save more memory!

**Comment by magnus-madsen** [comment]
I don't follow. To be clear, I *do not* want `Some ()` to be turned into a field. I only want Unit constructors to be turned into fields. NOT a constructor which happens to be given Unit.
