### ISSUE TITLE
bug: regression of `use` of outer namespace definitions

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4722]
This program works in 0.31.0 but not in 0.32.0. Notice that none of these definitions are in the inner namespace scope by default.
* The import of `OuterEnum` is illegal in 0.32.0 (regression)
* The import of `OuterType` is illegal in 0.32.0 (regression)
* The import of `outer` is legal and works in 0.32.0
```
namespace ExampleOuter {
    pub enum OuterEnum { case OuterEnumCase(Int32) }
    pub type alias OuterType = Int32
    pub def outer(): Int32 = 42
    namespace ExampleInner {
        use ExampleOuter.OuterEnum;
        use ExampleOuter.OuterType;
        use ExampleOuter.outer;
        pub def example1(): OuterEnum = ???
        pub def example2(): OuterType = ???
        pub def example3(): Int32 = outer()
    }
}
```

**Comment by paulbutcher** [comment]
So, this behaviour is exactly what I intended to implement, but I designed it while operating under a misapprehension about how namespaces worked.

I thought that this compiled (which it doesn't, both before and after #4694):

```
namespace ExampleOuter {
    pub enum OuterEnum(Int32)
    namespace ExampleInner {
        pub def example1(): OuterEnum = ???
    }
}
```

Whereas this does (again, both before and after #4694):

```
namespace ExampleOuter2 {
    use ExampleOuter.OuterEnum
    namespace ExampleInner2 {
        pub def example2(): OuterEnum = ???
    }
}
```

So the heart of the problem is that the way that names introduced by `enum`, `type alias`, and `class` are scoped is very different from the way that names introduced by `use` and `import` are scoped.

I suspect that the solution is to make them consistent, i.e. either:

* all outer namespace identifiers should be visible within their inner namespaces, or
* names introduced by `use` and `import` should only be visible within their immediate namespace scope

But I'm not sure which of these is the right way to go? And I'm not sure how either would interact with the changes discussed within #4167?

**Comment by JonathanStarup** [comment]
I think it sounds nice if inner spaces have the outer definitions in scope, what does other languages do?

**Comment by magnus-madsen** [comment]
@stephentetley @mlutze @jaschdoc Your thoughts?

**Comment by magnus-madsen** [comment]
In Java, declarations in outer packages are not visible in inner packages.

**Comment by paulbutcher** [comment]
> As for `use`'s I would think the following:
> 
> * A use at the top-level applies to the entire file.
> * A use inside a namespace applies to everything in that namespaces (and sub-names) (in the same file).

So this is pretty much how it currently works. But that leads to issues like this:

```
namespace A {
    use B.C
    namespace D {
        // enum C
        def foo(): C == ???
    }
}
```

As the above stands it compiles. Uncomment the `enum` line and it still compiles, but now the meaning of the program has changed (`C` now refers to `D.C`). This will, I think, cause heartache and pain.

Or, alternatively, we say that it doesn't compile (because we're "redefining" `C`). But now consider this:

In file1.flix:
```
namespace A {
    use B.C
    namespace D {
        def foo(): C == ???
    }
}
```

In file2.flix:
```
namespace A.D {
    enum C
    def bar(): C = ???
}
```

Now we have two functions, both in the namespace `A.D`, both of which refer to `C`, but `C` means something different in both.

The more I think about this, the more I think that the rules around `use` and `import` (which work one way) and `enum`, `type alias` and `class` (which work another way) should be consistent. Otherwise, we're asking for confusion.

**Comment by magnus-madsen** [comment]
Note that you can have this:

```
namespace Foo {
  def f(): X.A
  def f(): X.B
}
```

so I am not sure why that is a problem.

**Comment by magnus-madsen** [comment]
But what's the core problem? Shadowing?

**Comment by paulbutcher** [comment]
> Note that you can have this:
> 
> ```
> namespace Foo {
>   def f(): X.A
>   def g(): X.B
> }
> ```
> 
> so I am not sure why that is a problem.

Apologies Magnus, but I'm not sure what the problem (or lack of a problem) is that you're pointing out here? `X.A` and `X.B` are different things, so what would the problem be in any case?

**Comment by magnus-madsen** [comment]
(Corrected a typo in my example). The point is that its okay that `A` can mean different things in different contexts.

**Comment by magnus-madsen** [comment]
This is okay:

```
namespace Foo {
  def f(): X.A
  def g(): Y.A
}
```

then this is also okay:

```
namespace Foo {
  use X.A;
  def f(): A
}
namespace Foo {
    use Y.A;
    def g(): A
}
```

**Comment by paulbutcher** [comment]
> (Corrected a typo in my example). The point is that its okay that `A` can mean different things in different contexts.

Ah! That makes much more sense.

With respect, I don't think that that's the same at all. If I, as a programmer, read:

```
def frobnicate(): Bank.Account = ???

def munge(): Dramatic.Account = ???
```

Then it's very clear that `Bank.Account` and `Dramatic.Account` are very different things.

If, on the other hand, I have:

```
def frobnicate(): Account = ???

def munge(): Account = ???    
```

Then it's not clear at all that `Account` means different things.

This wouldn't be a problem if `frobnicate` and `munge` were in different namespaces, because we expect that different namespaces have different semantics. But if they're in the *same* namespace, then it's very confusing.

**Comment by paulbutcher** [comment]
> This is okay:
> 
> ```
> namespace Foo {
>   def f(): X.A
>   def g(): Y.A
> }
> ```

I agree that this is OK.

> then this is also okay:
> 
> ```
> namespace Foo {
>   use X.A;
>   def f(): A
> }
> namespace Foo {
>   use Y.A;
>   def g(): A
> }
> ```

I disagree. I think that this should be an error. `A` should only have a single meaning within the namespace `Foo`.

**Comment by magnus-madsen** [comment]
I think we should see what Rust does and try to emulate that. (Whatever that is. Looking at it now).

**Comment by magnus-madsen** [comment]
Rust:

```rust
fn toplevel() {
    println!("called `toplevel()`");
}

mod A {
    fn outer() {
        println!("called `outer()`");
    }
    pub mod B {
        pub fn inner() {
            println!("called `inner()`");
            toplevel();
            outer();
        }
    }
}
```

does not compile because `toplevel` and `outer` are not visible.

**Observation 1:** Outer definitions are not visible in inner namespaces (like Java packages).

Let's import `toplevel` at the top-level:

```rust
use crate::toplevel;

fn toplevel() {
    println!("called `toplevel()`");
}

...
```

Does not compile because `toplevel` is now ambiguous. 

**Observation 2:** It is not allowed to declare a function with the same name as one that has been imported. (No shadowing).

```
fn toplevel() {
    println!("called `toplevel()`");
}

mod A {
    use crate::toplevel;
    pub fn outer() {
        println!("called `outer()`");
    }
    pub mod B {
        use crate::A::outer;
        pub fn inner() {
            println!("called `inner()`");
            toplevel();
            outer();
        }
    }
}
```

does not compile because `toplevel` while used in `A` is not visible inside `B`.

**Observation 3:** Uses/Imports do not cross module namespaces (or if you prefer, opening a new namespace clears all imports).


"Mistakes" we have made:
- Opening a new namespace should clear all imports/uses.
- You should never be allowed to re-declare a name that has been used/imported. 
- Declarations are not visible in inner (nested) namespaces. You must import them.

**Comment by magnus-madsen** [comment]
All three are restrictions which means we will break some code.

One thing that is not clear to me: How do you access top-level functions? We certainly want our `Prelude` to be useful.

**Comment by magnus-madsen** [comment]
I think Rust's design is very conservative (i.e. strict) and I think that's what we want.

**Comment by paulbutcher** [comment]
That gives us consistency (which is my main concern), so 👍 from me

**Comment by paulbutcher** [comment]
How does this interact with the work going on under https://github.com/flix/flix/issues/4167? I've not been following that closely?

**Comment by magnus-madsen** [comment]
In https://github.com/flix/flix/issues/4167 half the proposals are quality of life and/or tooling. All of those we could still (eventually) have.

The following would be voided:

- Declarations being visible in nested namespace.
- I would propose to **ban** qualified imports.
- Orthogonal to whether you need to import both enum types and their tags.
- Orthogonal to treatment of opaque enums.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup @stephentetley 

What's your thoughts? The TLDR is to adopt Rust's design (modulo Prelude, opaque enums, and the fact that we have both Java and Flix names).

**Comment by mlutze** [comment]
>     * I would propose to **ban** qualified imports.

Can you clarify what this one means?

**Comment by JonathanStarup** [comment]
Regarding prelude, all files/namespaces could implicitely start with `import Prelude.{x, y, z, ...}`

This very strict scoping feels very cumbersome, I kind of liked the file-wide import. Maybe it is okay though, the modern solution to imports is just to let the IDE handle it right? Hope users don't have to think about them.

**Comment by magnus-madsen** [comment]
A qualified import is when you are allowed to do:

```
import A.B.C
import C.D.E
import E.f

// f now means A.B.C.D.E.f
```

**Comment by JonathanStarup** [comment]
but this is okay?
```
import A.B.C
import A.B.C.D.E
import A.B.C.D.E.f

// C now means A.B.C
// E now means A.B.C.D.E
// f now means A.B.C.D.E.f
```

**Comment by magnus-madsen** [comment]
> but this is okay (I hope)?
> 
> ```
> import A.B.C
> import A.B.C.D.E
> import A.B.C.D.E.f
> 
> // C now means A.B.C
> // E now means A.B.C.D.E
> // f now means A.B.C.D.E.f
> ```

No. This would not be okay.

**Comment by magnus-madsen** [comment]
Randomly looking at `https://github.com/mlutze/flixball/blob/master/src/BoardLibrary.flix` it does not seem to bad. This code would continue to work as is. I note several of the uses can be collapsed with use of `{...}`. Import `...Board` and `...Board.Board` is perhaps annoying.

**Comment by magnus-madsen** [comment]
@JonathanStarup The only thing that would be okay (at some point in the future) could be: `use Flixball/Core/Board as Board` and then you can write `Board.XYZ` for `Flixball/Core/Board.XYZ`. But critically one `use` ****will never influence another use****.

**Comment by JonathanStarup** [comment]
I really dislike that. If i have `AAAAA.BBBBB.CCCCC.DDDDD.init` then i can either
* use `AAAAA.BBBBB.CCCCC.DDDDD.init` (really annoying)
* use `use AAAAA.BBBBB.CCCCC.DDDDD.init` (this will likely clash with generic function names)
*  use `use AAAAA.BBBBB.CCCCC.DDDDD.{init => dddddInit}` (now I need to remember my arbitrary name)

> I note several of the uses can be collapsed with use of {...}
If they are collapsed with `{...}` then the editor can sort them (no language support only `sort lines`) and its more annoying to (manually) find unused imports

>

**Comment by magnus-madsen** [comment]
The TLDR response is: IDE support plus (eventually) allowing you to shorten a namespace to a shorter name.

**Comment by JonathanStarup** [comment]
> ... shorten a namespace to a shorter name.

Does this mean namespace aliasing?

**Comment by magnus-madsen** [comment]
> > ... shorten a namespace to a shorter name.
> 
> Does this mean namespace aliasing (for non-`use` uses)?

Yes, but this would not be in version 1.0 of the proposal.

**Comment by mlutze** [comment]
I am ok with the conclusions here. The alias thing that Jonathan has brought up feels very important for ergonomics.

There remain some questions about namespaces for instances and classes, but these can be addressed separately.

**Comment by magnus-madsen** [comment]
I will write up a ticket with specific changes.

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/issues/4746

**Comment by paulbutcher** [comment]
Can this be closed (subsumed by https://github.com/flix/flix/issues/4746?)
