### ISSUE TITLE
Error message reported at incorrect source location

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4835]
The following (incorrect) code:

```
def foo(): Map[Int32, Int32] =

    def bar(x: Map[Int32, Int32]): Map[Int32, Int32] =
        bar(Map.insert(1, 1));

    bar(Map#{})
```

Generates:

```
❌ -- Type Error -------------------------------------------------- file:///Users/paulbutcher/Projects/Flix/flix-playground/src/Main.flix

>> Unable to unify the types: '? -> ?' and 'Map'.

6 |     bar(Map#{})
        ^^^^^^^^^^^
        mismatched types.

Type One: (Map[Int32, Int32] -> Map[Int32, Int32]) -> ?result4347108 & ?pur4347109 \ ?eff4347110
Type Two: Map[t4347136, t4347137] -> ?result4347130 & ?pur4347131 \ ?eff4347132
```

The source location is incorrect: the error is on line 4.

(this is a cut down version of something that took me a *long* time to work out thanks to the error misleading me into looking in the wrong place).

**Comment by paulbutcher** [comment]
I've taken a quick look at this, and it's easy enough to see that at the point that the error is created, the `tpe1.loc` is the correct one, and `tpe2.loc` is the incorrect one. But because it's deep within the bowels of `InferMonad` the call stack gives me no help at all in working out which of the many invocations of `unifyTypeM` is the one that's choosing the wrong location.

I suspect that this might need someone who understands the typer better than I do to work out where the mistake is.

@mlutze?

**Comment by mlutze** [comment]
IMO this is another case of desugaring too early.

Here's the desugared form of the function:

```scala
def foo(): Map[Int32, Int32] =
    let rec bar = (x: Map[Int32, Int32]) -> bar(Map.insert(1, 1));
    bar(Map#{})
```

We start by visiting `exp1`: `(x: Map[Int32, Int32]) -> bar(Map.insert(1, 1))`.
From this we gather:
- the type of `bar` is `(Map[Int32, Int32] -> Map[Int32, Int32]) -> ?res`
- the type of `exp1` is `Map[Int32, Int32] -> ?res`

Then we visit `exp2`. Here we see that `bar` is applied to a `Map[Int32, Int32]` which conflicts with what we previously found so we throw an error.

Then we check `bar` and `x` but it's too late :)

We can kind of fix this by reordering the unifications so `bar` and `x` come before `exp2` but this doesn't help us a lot:

```
>> Unable to unify the types: '? -> ?' and 'Map'.

208 |>     def bar(x: Map[Int32, Int32]): Map[Int32, Int32] =
209 |>         bar(Map.insert(1, 1));
210 |> 
211 |>     bar(Map#{})

mismatched types.
```

We can do even better by adjusting the source location in the desugared expression:

```
>> Unable to unify the types: '? -> ?' and 'Map'.

209 |         bar(Map.insert(1, 1));
              ^^^^^^^^^^^^^^^^^^^^^
              mismatched types.
```

This works for this case but I'm not convinced the new source location will not be sometimes be off, since now the location of `exp1` only appears to be the body of the lambda, when in reality it is the whole lambda.
