### ISSUE TITLE
unused `use` is not checked

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4881]
```
use Anything.goes
```
This is a valid program
```
use Anything.goes
def example(): Unit = {
    let g = goes;
    ???
}
```
This now trigger the `Undefined name 'Anything.goes'.` error

**Comment by magnus-madsen** [comment]
@mlutze Is it fixed? :)

**Comment by mlutze** [comment]
Partially:
We check that uses are valid, but we do not check that they are used. So the given example is fixed but this example is not:

```scala
use List.map
def example(): Unit = {
    ???
}
```

**Comment by mlutze** [comment]
> To clarify - does that mean this snippet should trigger an error saying that List.map is not being used?

Yes, that's right.

> This seems something that should be done in the redundancy phase - if that's the case and this is up for grabs I can work on it.

In principle it is up for grabs, though I think it will not be a straightforward implementation. We lose knowledge of part of the AST structure before we hit the redundancy phase. For example:

```
mod A {
    use XYZ
}

mod A {
    use ABC
}
```

probably looks something like
```
mod A {
    use XYZ
    use ABC
}
```
to that phase.


We also don't have anything like a `UseSym`, so that would need addressing too.

So it might take a bit of design beforehand to get in place. But you're welcome to try your hand at it :)

**Comment by JonathanStarup** [comment]
remaining issue captured in  #4883
