### ISSUE TITLE
Prioritization in HoleCompletion

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5073]
Can we do better for:

```
def main(): Unit \ IO = 
    let l1 = l();
    let l2 = List.intersperse(42, l1);
    let l3 = List.map(x -> x :: x :: Nil, l2);
    let _l4 = l3?; // here we know l3 is List[List[Int32]]
    println("abc")
```

by picking more specific schemes first?

**Comment by mlutze** [comment]
So we want e.g. `List.flatten` to come up first here since it's specifically operating on `List[List[a]]`?

I think we can do this by looking at the substitution that we get from the unification, and taking the sum of the sizes of all the types in the substitution.

So if we have a function that takes a `List[List[Int32]]` as a parameter, the substitution will be empty and it will be first on the list. `List.flatten` will have `a -> Int32` and will show up next. Other list stuff will have `a -> List[Int32]` and finally fully-polymorphic functions will have `a -> List[List[Int32]]` and will show up last.
