### ISSUE TITLE
Refactor `Iterable` class

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5189]
As a step towards https://github.com/flix/flix/issues/5132, I would like to change `Iterable` from:

```
pub class Iterable[t: Type -> Region -> Type] {
    pub def iterator(r1: Region[r1], t: t[a, r2]): Iterator[a, r1 and r2] \ { Write(r1), Read(r2) }
    // ...
}
```

to

```
pub class Iterable[t: Type -> Type] {
    pub def iterator(r1: Region[r], t: t[a]): Iterator[a, r] \ r
    // ...
}
```

This means that we can implement `Iterable` for all immutable types (e.g. `List`), but we have to drop the instances for mutable collections. **This is not one step forward and one step back, because we are changing `Iterable` to a signature that is _compatible_ with associated types. Thus this _is future proofing_**.

**Comment by paulbutcher** [comment]
That makes sense, but can I ask how far away associated types are? I.e. how long will this mean that we're without a good solution for mutable types?

**Comment by magnus-madsen** [comment]
> 

I would say 2-6 months. 

In the interim the solution for mutable types is not bad, it is going to be:

```
region rh {
  let result = foreach(x <- immutableList, y <- MutList.iterator(rh, mutableList)) yield x + y
   // ...
}
```

I think that is very reasonable.

**Comment by magnus-madsen** [comment]
But also, currently the situation is that it does not work for immutable collections!

**Comment by stephentetley** [comment]
Has anyone started working on this? 

I can take a look at it and `Collectable` #5190 if no-one has started on them.

**Comment by magnus-madsen** [comment]
> Has anyone started working on this?
> 
> I can take a look at it and `Collectable` #5190 if no-one has started on them.

I don't think anyone has started looking at the code, so you are welcome to take a first stab at it.

**Comment by magnus-madsen** [comment]
Then Paul and Jakob and I can pitch in later with some of the other pieces of the puzzle.

**Comment by stephentetley** [comment]
Thanks - I'll make a start.

**Comment by magnus-madsen** [comment]
By the way, it would be interesting if `Collectable` can be implemented for `Result[List[Int32], ...]`, but I am not sure if that is possible in current Flix.

**Comment by magnus-madsen** [comment]
> By the way, it would be interesting if `Collectable` can be implemented for `Result[List[Int32], ...]`, but I am not sure if that is possible in current Flix.

I guess this is not possible, sadly. I wonder if Haskell can do it.

**Comment by mlutze** [comment]
> > By the way, it would be interesting if `Collectable` can be implemented for `Result[List[Int32], ...]`, but I am not sure if that is possible in current Flix.
> 
> I guess this is not possible, sadly. I wonder if Haskell can do it.

Can you clarify what the full signature would be? I suspect it may be possible with associated types.

**Comment by magnus-madsen** [comment]
> Can you clarify what the full signature would be? I suspect it may be possible with associated types.

I want to collect an `Iterator[Option[a], ...]` into an `Option[List[a]]`. Something like this.

**Comment by mlutze** [comment]
What about this?

```scala
class Collectable[a] {
    associated type Elem[a]
    pub def collect(it: Iterable[Elem[a]]): a
}

instance Collectable[Option[a]] with Collectable[a] {
    associated type Elem[Option[a]] = Option[Elem[a]]
    pub def collect(it: Iterable[Option[Elem[a]]]): Option[a] = ???
}
```

**Comment by stephentetley** [comment]
I've got stuck trying to change the kind of the `Iterable` class to `Type -> Type`.

The current code is here:

https://github.com/stephentetley/flix/tree/iterable-change

The changes in the code (except the change of kind to `Iterable`) are not so relevant to the problem - basically I've changed all but one of the `foreach` comprehensions in the stdlib to use `forEach` (if they were iterators) or `forEachWithIndex` (if they were enumerators). This is to remove repeated instance of the error I'm seeing - there is now just a single `foreach` comprehension in Set.flix (`toString`). 

The comprehension generates this error when trying to run `main` in IntelliJ:

~~~

-- Type Error -------------------------------------------------- Set.flix

>> Expected type: ''0' but found type: 'Iterator[(a, Int32)]'.

106 |         foreach ((x, i) <- enumerator(r, s)) {
                                 ^^^^^^^^^^
                                 expression has unexpected type.

~~~

As far as I can tell the expected type would a region but it gets mangled to `'0'`. My theory is the problem is caused in Weeder.scala circa lines 752+. The code at this point seems to be generating a fresh region variable (`regVar`) but my guess is that it should be using the existing region `r` from the enumerator expression.

Even if my theory is correct I don't know how to implement it and I'll need some help, thanks.

**Comment by mlutze** [comment]
Here are my findings:

The unification in question is trying to unify a free variable `0` with `Iterator[(a, Int32)]`

The free variable `0` has kind `Type -> Type`, but `Iterator[(a, Int32)]` has kind `Bool -> Type` (recall that `Region` is currently an alias for `Bool`)

I believe this unification issue arises because the `foreach` construct magically wraps `enumerator(r, s)` like `Iterable.iterator(reg, enumerator(r, s))`. But if we look at `Iterable.iterator`'s signature, we have this:

```scala
    ///
    /// Returns an iterator over `t`.
    ///
    pub def iterator(rh: Region[r], t: t[a]): Iterator[a, r] \ Write(r)
```

Importantly, that `t` is `Type -> Type`.

`enumerate(r, s)` returns `Iterator[(a, Int32), r]`

We try to unify `t[a]` with `Iterator[(a, Int32), r]`, which fails due to the kind difference.

**Comment by stephentetley** [comment]
Thanks Matthew, I'm still stuck how to solve it unfortunately.

**Comment by mlutze** [comment]
> Thanks Matthew, I'm still stuck how to solve it unfortunately.

I'm not sure of the immediate solution either. Iterator cannot be an instance of the new Iterable class because of the regions.

**Comment by magnus-madsen** [comment]
I am a bit lost, but I guess the issue is the following: By changing the kind, we can only support `m[t]` which rules out mutable types, e.g. `Array[t, r]` (as expected), but also `iterator/enumerator` (unexpected).

**Comment by magnus-madsen** [comment]
But if we drop enumerator -- for the moment -- can we then make progress?

**Comment by stephentetley** [comment]
I've just updated the branch above to disable `enumerator` in `Iterable` but desugaring a `foreach` comprehension that uses `iterator` still has the same error.

**Comment by magnus-madsen** [comment]
Do you have an example?

**Comment by stephentetley** [comment]
`List.toString` is written as a comprehension in the latest commit to that branch. 

~~~

-- Type Error -------------------------------------------------- List.flix

>> Expected type: ''0' but found type: 'Iterator[a]'.

134 |         foreach (x <- iterator(r, l))
                            ^^^^^^^^
                            expression has unexpected type.

~~~

**Comment by mlutze** [comment]
> `List.toString` is written as a comprehension in the latest commit to that branch.
> 
> ```
> 
> -- Type Error -------------------------------------------------- List.flix
> 
> >> Expected type: ''0' but found type: 'Iterator[a]'.
> 
> 134 |         foreach (x <- iterator(r, l))
>                             ^^^^^^^^
>                             expression has unexpected type.
> ```

Can that be replaced with `foreach (x <- l)`? Since `iterator` is implicitly called

**Comment by stephentetley** [comment]
> Can that be replaced with `foreach (x <- l)`? Since iterator is implicitly called

Yes - compiles (and runs) without error.

**Comment by magnus-madsen** [comment]
Is this still blocked or?

**Comment by stephentetley** [comment]
Still blocked.

There are a lot of tests that use an explicit `iterator` in `foreach` loops. It would feel a backward step to change them all to use a list.

My view is that the desugaring in `Weeder` should check the right hand side of the `foreach` fragment (ie. after the left arrow) and not wrap an `iterator` or `enumerator` call in a fresh `iterator`. If the right hand side is a List / Chain etc. expression that has an instance of `Iterable` there should be a fresh iterator built.

**Comment by stephentetley** [comment]
Apropos the above.

Maybe the right hand side of a ForEachFragment should already be an iterator (more accurately an expression of type Iterator) derived by the `Iterable` class.

`Iterator` itself would have an instance of `Iterable` that is just identity [*].

This mean the desugaring doesn't have to inspect the fragments right hand side to choose whether to make a fresh iterator.

[*] Currently this prevented by a mismatch between the kind of `Iterator` and Iterable`.

**Comment by magnus-madsen** [comment]
> Apropos the above.
> 
> Maybe the right hand side of a ForEachFragment should already be an iterator (more accurately an expression of type Iterator) derived by the `Iterable` class.
> 
> `Iterator` itself would have an instance of `Iterable` that is just identity [*].
> 
> This mean the desugaring doesn't have to inspect the fragments right hand side to choose whether to make a fresh iterator.
> 
> [*] Currently this prevented by a mismatch between the kind of `Iterator` and Iterable`.

Yes. This is what I ultimately want :) This is also outlined in the Stream ticket.

**Comment by magnus-madsen** [comment]
> There are a lot of tests that use an explicit `iterator` in `foreach` loops. It would feel a backward step to change them all to use a list.

I am OK with removing stuff so we can get on the right path. 

Alternatively, we could start fresh on `Stream` and `Streamable` and try to implement these? (Later when can then entirely delete Iterable/Iterator and rename Stream/Streamable).

**Comment by stephentetley** [comment]
I've had a think, and I think we could...

1. Change the kind of `Iterable` to be `Type -> Type` and keep `foreach` comprehensions for now, the `ForEachFragment` right-hand side of the arrow has to be a pure `Iterable` like `List` in Matthew's suggestion above. Unfortunately we have to lose `Iterator` as a right-hand side because it can't be made an instance of the `Iterable` with the new kind. We can have `Set` and `Chain` as well as `List` as right-hand sides of the arrow.

2. Remove `enumerator` from `Iterable` as it can't be supported for `foreach` comprehensions when the arrow right-hand side has to be an `Iterable` instance.  Collection types with still be able to use `enumerator` as a function to produce an indexed iterator directly.

3. Add `forEachWithIndex` to all collection types that currently have a `forEach` function. If you squint `forEachWithIndex` is just an enumerator comprehension with the args flipped although for multi-collection enumeration it does lose the syntax convenience.

This keeps comprehensions in place so they don't bit-rot and goes a reasonable of the way to compensate for removing enumerator.

**Comment by magnus-madsen** [comment]
> I've had a think, and I think we could...
> 
>     1. Change the kind of `Iterable` to be `Type -> Type` and keep `foreach` comprehensions for now, the `ForEachFragment` right-hand side of the arrow has to be a pure `Iterable` like `List` in Matthew's suggestion above. Unfortunately we have to lose `Iterator` as a possible right-hand side because it can't be made an instance of `Iterable` with the new kind. We can have `Set` and `Chain` as well as `List` as right-hand sides of the arrow.

I think that is reasonable.

>     2. Remove `enumerator` from `Iterable` as it can't be supported for `foreach` comprehensions when the arrow right-hand side has to be an `Iterable` instance.  Collection types with still be able to use `enumerator` as a function to produce an indexed iterator directly.

I am OK with that for now.

>     3. Add `forEachWithIndex` to all collection types that currently have a `forEach` function. If you squint `forEachWithIndex` is just an enumerator comprehension with the args flipped although for multi-collection enumeration it does lose the syntax convenience.

We can, but not sure if it is important at this point (?)

**Comment by stephentetley** [comment]
Thanks Magnus, I'll work on 1 and 2.

If anyone wants 3 I can add `forEachWithIndex` functions later.

**Comment by stephentetley** [comment]
I've submitted a PR - #5234.

`forEachWithIndex` turned out to be useful, so I have added them to collections that previously used `enumerator` in their `toString` function.
