### ISSUE TITLE
Improve error message for leaving a semicolon at the end of a line.

### ISSUE THREAD

**Issue by Sintrastes** [flix/flix#5491]
If I write a function, and I forget that statements at the end of a function don't need a semicolon (for instance):

```
def main(): Unit \ IO =
    println("Hello");
    println("World");
```

I get a generic error message like this:

```
>> Parse Error: Unexpected end of input, expected QName or Assign (line 88, column 22):
    println("World");
```

While I understand the philosophy of making things errors rather than warnings, I think that the error message is a little bit lacking here nevertheless. As a new user, I'd prefer to see something here more like:

```
>> Parse Error: Unexpected end of input, expected QName or Assign (line 88, column 22):
    println("World");
                   ^^^
Hint: It looks like you added an extra semicolon here. The last statement in a block in Flix does 
 not need a semicolon.
```

Sorry if there is already an issue that covers this, I just thought this would be a nice improvement.

**Comment by magnus-madsen** [comment]
Would be nice yes. Not sure yet how to do it.

**Comment by Sintrastes** [comment]
I'm also not sure. I can do some research into how Elm/Rust get error messages like this a d see if there's a way we could incorporate something like this.

**Comment by magnus-madsen** [comment]
> I'm also not sure. I can do some research into how Elm/Rust get error messages like this and see if there's a way we could incorporate something like this.

I think we need to write a hand-written recursive descent parser-- which has long been a goal but is a large task.

**Comment by Sintrastes** [comment]
@magnus-madsen There's also this: https://research.swtch.com/yyerror

Though I'm not sure if that would end up being easier or harder than building a hand-written recursive descent parser, if nobody has implemented this approach in Scala yet.

**Comment by magnus-madsen** [comment]
I think the plan is to eventually have a hand-written parser with error recovery.

**Comment by magnus-madsen** [comment]
We have a new parser.

**Comment by KamilZielinski** [comment]
> We have a new parser.

Hello @magnus-madsen 👋 Should this issue be marked as completed? The error message is still difficult to understand for newbies in Flix (including me, as I just started looking into it) and it doesn't look like it has been resolved or it's lacking an explanation why this issue has been marked as **completed** (was it resolved / it won't be resolved?).

Currently for such code:
```flix
pub def main(): Unit \ IO = {
    println("test");
}
```

it gives me such 2 errors:
```
❌ -- Parse Error (OtherExpr) -------------------------------------------------- file:///c%3A/Users/me/flixing/src/Main.flix

>> Expected <expression> before '}'.

16 | }
     ^
     Here

❌ -- Parse Error (OtherExpr) -------------------------------------------------- file:///c%3A/Users/me/flixing/src/Main.flix

>> Expected '}' before <end-of-file>.

16 | }
      
      Here
```

which confused me and took me ~2hours to find out what the issue was 😅
If there's a plan to improve this kind of errors (at least for this specific case), it would be great to keep it open IMO.

Maybe also as an additional question related to this confusing error message - why is `;` not allowed in the last line of the function? I guess it's a language-design decision but I couldn't find an explanation or introduction to it in the language [documentation](https://doc.flix.dev/)
