### ISSUE TITLE
The fact that Functor allows effects seems quite problematic

### ISSUE THREAD

**Issue by athas** [flix/flix#5520]
Consider a type

```Flix
enum Parser[a] {
  case Parser(String -> List[(a,String)])
}
```

How can I make a `Functor` instance for this type?  Functor requires that I perform an effect *in the map operation itself*, but here I will always be operating under a function arrow.  E.g:

```Flix
instance Functor[Parser] {
  pub def map(f : a -> b & ef, a : Parser[a]): Parser[b] & ef =
    match a {
      case Parser(g) => s -> Functor.map(p -> (f(fst(p)),snd(p)), g(s))
    }
}
```

A secondary issue is that the function in the Parser type itself cannot have effects.  I could perhaps solve that by parameterising it over an effect variable.  My definition of `Functor.map` would still be pure, though, and that's not good enough as Flix does not allow subeffecting.

**Comment by athas** [comment]
Generally, I'm suspicious of an effect-polymorphic `Functor`.  It's probably inappropriate for many types.

**Comment by magnus-madsen** [comment]
This is a "well-known" issue. We are actively exploring it; two keywords are associated effects and indexed/graded monads. 

We can talk more online :)

**Comment by stephentetley** [comment]
I'm working on a Graded Functor-Applicative-Monad library that capture effects within the constructor in your case `Parser` rather than lets effects float ambiently to the right of function signatures (the "index" of the graded functor is the captured effect). So you would have:

~~~

pub class GradedFunctor[m: Bool -> Type -> Type] {
    pub def map(f: a -> b \ ef1, x: m[ef, a]): m[ef and ef1, b]
}

pub class GradedApplicative[m: Bool -> Type -> Type] with GradedFunctor[m] {
  ...
}

pub class GradedMonad[m: Bool -> Type -> Type] with GradedApplicative[m] {
  ...
} 

enum Parser[ef, a] {
  case Parser(String -> List[(a, String)] \ ef)
}

instance GradedFunctor[Parser] {
  pub def map(f : a -> b \ ef1, a : Parser[ef, a]): Parser[ef and ef1, b] =
    ...
}

instance GradedApplicative[Parser] {
  pub def point(x: a): Parser[ef, b] = ...
  
  pub def ap(f : Parser[ef1, a -> b \ ef2, a : Parser[ef, a]): Parser[ef and ef1 and ef2, b] =
    ...
}

instance GradedApplicative[Parser] {
  pub def flatMap(f : a -> Parser[ef1, b] \ ef2, a : Parser[ef, a]): Parser[ef and ef1 and ef2, b] =
    ...
}


~~~

So far, I've only converted one of my libraries to use graded FAMs (csvio) but it seems to work well and I am working on converting the others.
(I'll probably leave my parser combinator library to the last because it could do with a big refactor).

https://github.com/stephentetley/graded-lib

**Comment by stephentetley** [comment]
I wouldn't recommend anyone use `graded-lib` in their own code for the time being, but combining effects with functors-applicative-monads is being actively worked on.

**Comment by magnus-madsen** [comment]
(Continued elsewhere and offline).
