### ISSUE TITLE
Iterator signature

### ISSUE THREAD

**Issue by mlutze** [flix/flix#6041]
Per discussion with @JonathanStarup, we think the signature of Iterator should be

```
Iterator[a, ef, r]
```

where `ef` includes `r`.

We feel this would lead to more comprehensible signatures.

**Comment by stephentetley** [comment]
I was still a bit vexed the types of the operations / functions on Iterator - they don't feel particularly intuitive to use, so I modeled Flix's Iterator in Haskell with the ST monad taking the place of regions:

https://gist.github.com/stephentetley/602e2e985f6d58b1065c75e364d4b8b3

The most obvious point is that Iterator constructors like `range` that use mutable refs do need an outer region (Flix) or creating in the ST monad (Haskell) they can't just encapsulate mutation in the Iterator body. Hence in the Haskell code `range` returns an Iterator in ST (the pure `empty` doesn't need to be returned in ST)..

`next` also must operate within ST (Haskell) as the body of the Iterator which is "thunked" to get the next element is an ST function. This is perhaps easier to overlook in Flix because regions do not oblige programming with do / forM notation.

I'm not sure this helps us improve the typing / effect typing of the current Iterator module but at least I'm quite a bit happier with my understanding of it.

**Comment by JonathanStarup** [comment]
Fixed on master
