### ISSUE TITLE
Totality Checker?

### ISSUE THREAD

**Issue by sargun** [flix/flix#607]
Does Flix have a totality checker? Is there a mechanism to determine that this will never terminate:

```
def fac(n : Int, acc : Int) : Int = match n with {
    case 0 => acc
    case _ => fac(n-1, acc * n)
}

// dummy main, required for online evaluator.
def f(): Int = fac(-10, 1)
```

**Comment by magnus-madsen** [comment]
Flix does not currently have a totality checker. A program like the above will loop forever.

In future, we would like to add annotation which can ensure totality for simple functions that use algebraic data types. For example to ensure that a function is always structurally recursive on a list or tree.

In the most general case, for example with integer arithmetic, this problem is undecidable. So it is unlikely that Flix will ever be able to reason precisely about code like the above.

However, there has been some progress in the area of SMT solvers (and Flix does not have some support for checking properties of functions via SMT) so perhaps one day.

**Comment by magnus-madsen** [comment]
You can find more information in #448.

**Comment by sargun** [comment]
@magnus-madsen Yeah, the program above would fail the Idris type checker, and Agda type checker. Recursion should not be allowed in the general case.

**Comment by magnus-madsen** [comment]
I am closing this, since we are tracking the issue in #448. Hopefully I will find a good student to work on that :)
