### ISSUE TITLE
Implement newtype

### ISSUE THREAD

**Issue by mhyee** [flix/flix#63]
Basically Haskell's newtype (so not a type alias). See how Haskell implements this.

See: http://learnyouahaskell.com/functors-applicative-functors-and-monoids#the-newtype-keyword

**Comment by magnus-madsen** [comment]
I think I am okay with `newtype Foo = Int`. How does it work with generics? 

If you have `newtype Foo = Option[Int]` is that sugar for:

```
enum Foo {
  case Foo(Option[Int])
}
```
?

and `newtype Foo = Option[a]` is invalid because `a` is not bound?

**Comment by mhyee** [comment]
What about `newtype Foo[Int] = Option[Int]`? That way, you could also write `newtype Foo[Char] = Option[Char]`.

I guess `newtype Foo[a] = Option[a]` doesn't really make sense, since it desugars to
```
enum Foo {
  case Foo(Option[a])
}
```
And `a` is still unbound.

**Comment by magnus-madsen** [comment]
Maybe it is just me, but I find `newtype Foo = Option[Int]` hard to read. Like I understand that it is just wrapping the right hand side, but I still have trouble parsing it.

**Comment by magnus-madsen** [comment]
I'm thinking of the following:

```
type Heap = H(Map[Address, Expression])
```

Notice that the type is named Heap and the constructor is named H.

I dislike the use of `newtype` since the word "new" bothers me. `type` is also not very good. Perhaps `typealias` or some other name?

In general, I still find the feature a bit "odd", although extremely useful!
