### ISSUE TITLE
Associated effects in the standard library?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#6513]
Are associated effects stable enough to be used in the standard library?

Currently the `ToJava` class mandates `IO` as the effect every conversion uses:

~~~

pub class ToJava[t: Type] {
    type O
    pub def toJava(t: t): ToJava.O[t] \ IO
}

~~~

However it would be nice to be more relaxed about the effect need especially for converting simple types like `String` and `BigDecimal` (i.e. not containers) where the conversion would be expected to be pure: 

~~~

pub class ToJava[t: Type] {
    type O: Type
    type Eff: Eff
    pub def toJava(t: t): ToJava.O[t] \ ToJava.Eff[t]
}

instance ToJava[BigDecimal] {
    type O = ##java.math.BigDecimal
    type Eff = {}
    pub def toJava(d: BigDecimal): ##java.math.BigDecimal \ {} = d
}

~~~

**Comment by magnus-madsen** [comment]
> Are associated effects stable enough to be used in the standard library?

Not yet...

But associated effects is our number one priority. We are currently working heavily on the implementation and a paper submission. Our deadline is in 5 weeks-- so hopefully by then the implementation is in place.

We had an initial implementation--which turned out to have some problems.

Unfortunately to overcome these we have had to rewrite the entire type inference infrastructure (~5000 loc). In addition, we have run into some technical challenges, but overall I am hopefully that we can get it done.

So to answer your question. Give us a few more weeks and then should be there :)

Meanwhile, are you on Gitter? I would be happy to share the draft with you (and maybe get some feedback?), but I cannot (yet) share it in public.

**Comment by stephentetley** [comment]
Thanks Magnus. Yes I am on Gitter - I seem to not get notifications anymore so I rather forgot about it haven't logged on in months. I'm happy to read through a draft.

**Comment by magnus-madsen** [comment]
We will need several weeks to polish the implementation, so the feature is not yet available.

**Comment by magnus-madsen** [comment]
See #7433
