### ISSUE TITLE
Parser: strange error message

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7638]
```
enum Color {
    case Red, 
}
```

```
>> Parse Error: Expected <Name> or 'Pure' before '}'

12 |     case Red, 
                 ^
                 Here
```

How can Pure be expected here?

**Comment by herluf-ba** [comment]
That's because we needed `Pure` to be a keyword but it is also used to name a type in `Prelude.flix`. That means that the set of tokenkinds that are allowed to name types needs to include `Pure` too.
It has been nagging me for months, and I'd really like `Pure` to not be a keyword and just treated as a regular NameUpperCase!

**Comment by herluf-ba** [comment]
Just to be clear: To fix this issue, we need to make a decision on whether `Pure` is a keyword, and possibly change some minor stuff in the standard library accordingly

**Comment by magnus-madsen** [comment]
OK. This seems like something we should discuss... Potentially with more people.

Its not really a problem right now, since error messages are on average significantly better than before.
