### ISSUE TITLE
Use placeholder snippets in InvokeMethodCompleter and InvokeStaticMethodCompleter

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8255]

**Comment by magnus-madsen** [comment]
@lozander CC

**Comment by LoZander** [comment]
While looking at this issue, I think I stumbled upon another issue. When using an instance of a java class and starting to type out a method name in dot-notation, there seem to be certain situations in which no completion suggests appear at all. At least this was the case for using a `StringBuilder`.

Here's an example of code where no suggestions appear (cursor position denoted with |):
```
...
import java.lang.StringBuilder;

def main(): Unit \ IO =
    let s: StringBuilder = new StringBuilder();
    s.ap|                      <-- suggestions should appear, but do not
    println(s.toString());
    ()
```

Here's an example where suggestions do appear (cursor position denoted with |):
```
...
import java.lang.StringBuilder;

def main(): Unit \ IO =
    let s: StringBuilder = new StringBuilder();
    s.ap|                      <-- suggestions appears
    ()
```

The issue seems to occur depending on what comes after the unfinished line. The same issue does not occur with static methods like trying to call something from `java.lang.Math`. I suspect the issue might be that the error created by the unfinished line, depending on what cames after it, somehow prevents the LS from having sufficient information to determine what class the object of the variable is a instance of, and so it can't come up with any suggestions, or something like that. That would explain why the issue only occurs for non-static method completion. But that's just speculation.

**Comment by LoZander** [comment]
> While looking at this issue, I think I stumbled upon another issue. When using an instance of a java class and starting to type out a method name in dot-notation, there seem to be certain situations in which no completion suggests appear at all. At least this was the case for using a `StringBuilder`.
> 
> Here's an example of code where no suggestions appear (cursor position denoted with |):
> 
> ```
> ...
> import java.lang.StringBuilder;
> 
> def main(): Unit \ IO =
>     let s: StringBuilder = new StringBuilder();
>     s.ap|                      <-- suggestions should appear, but do not
>     println(s.toString());
>     ()
> ```
> 
> Here's an example where suggestions do appear (cursor position denoted with |):
> 
> ```
> ...
> import java.lang.StringBuilder;
> 
> def main(): Unit \ IO =
>     let s: StringBuilder = new StringBuilder();
>     s.ap|                      <-- suggestions appears
>     ()
> ```
> 
> The issue seems to occur depending on what comes after the unfinished line. The same issue does not occur with static methods like trying to call something from `java.lang.Math`. I suspect the issue might be that the error created by the unfinished line, depending on what cames after it, somehow prevents the LS from having sufficient information to determine what class the object of the variable is a instance of, and so it can't come up with any suggestions, or something like that. That would explain why the issue only occurs for non-static method completion. But that's just speculation.

Perhaps I should add a new github issue describing this problem?

**Comment by magnus-madsen** [comment]
Thanks for the detailed comment. I think this has to do with the parser, since as you describe it depends on the next line.

So I think this is separate issue we can explore.
