### ISSUE TITLE
Add Date and Time Operations to the Standard Library

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#859]
We should probably look at the new date and time library in Java. But also others like Haskell etc.

**Comment by stephentetley** [comment]
Hi Magnus, I know I've got plenty on with Array and String, but I needed some Date / Time operations for scripts I've been using for work, so I've started looking at this.

My plan is limited to wrapping some of the existing classes in Java's new time library as a provisional step rather than look at a full design of a time library. So far though, the Java libraries seem to work quite nicely in a functional setting.

Work in progress is here:

https://github.com/stephentetley/flix-time

**Comment by magnus-madsen** [comment]
Looks good :) Can you tell me why the wrapper class `DateTimeWrapper ` is necessary? I was hoping those could mostly be avoided with the new import mechanism.

**Comment by stephentetley** [comment]
Thanks.

I've been using the wrapper where I need to cast to an interface, but I'll try casting on the Flix side with `as`.

**Comment by stephentetley** [comment]
Ah, I can cast to an interface in Flix so I'll see if I can remove DateTimeWrapper.

**Comment by magnus-madsen** [comment]
I don't think we will add this to the Flix library in the near term. Meanwhile Stephens library is ready for use. Perhaps we should include it in the community build?
