### ISSUE TITLE
Annotation completions seems broken

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8638]
E.g. `@Test`

**Comment by magnus-madsen** [comment]
@LoZander CC

**Comment by JonathanStarup** [comment]
i thought it was `@test`, thats what ive been using

**Comment by magnus-madsen** [comment]
Neither works for me.

**Comment by LoZander** [comment]
The issue is specifically this: if you type @ nothing is suggest ed but if you type the first letter of the an notation text, the annotation is suggested.

E. g. typing `@T` gives nothing while `T` suggests (among others) `@Test`.

For some reason, if the annotation is made into an expression completion suggestion, it will actually be suggested when typing `@T` in an expression. I additionally tried to make it a trait decl completion, but here it behaved attrangely, just like for module decl completions.

I don't know why these suggestions work differently in this way when classifying them as a expr completions as supposed to decl completions. Perhaps some result of how decls vs exprs are parsed? I don't know. It might also be an issue in the completers but I don't know where if so

**Comment by magnus-madsen** [comment]
Maybe @ is not a trigger char?

**Comment by JonathanStarup** [comment]
i think its the parser thing where it only goes into annotations if it sees @ *and* a name. its a problem for many autocompletes

**Comment by magnus-madsen** [comment]
I can type @T and not see anything.

**Comment by LoZander** [comment]
yeah, thats the weird part. It's also strange that it *does* work as expected in expression context. It light be the trigger word thing, but even if @ isn't a trigger word, wouldn't er get suggestions you the type t and are standing with the unfinished line @T? Or perhaps if a word starts with something that isn't a trigger char, nothing will be suggested even after you type the next letter?

**Comment by JonathanStarup** [comment]
as we discussed: add a hook in completionProvider in getContext (?) to have UndefinedAnnotation give the module context. This (along with ctrl+space) should allow nice completions (except maybe for @ by itself)

**Comment by LoZander** [comment]
Is this issue done, or is there more to do?
