### ISSUE TITLE
Rework HoverProvider to use search

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8639]
We should refactor HoverProvider to search through the AST instead of using the index.

The core idea is to introduce a new family of functions like:

```scala
def visitExpr(expr: Expr, visit: Expr => Unit, accept: Expr => Boolean): Unit = expr match {
    case Expr.IfThenElse(exp1, exp2, exp3, tpe, eff, loc) =>
      visitExpr(expr)
      if (accept(exp1)) {
        visitExpr(exp1, visit, accept)
      }
      if (accept(exp2)) {
        visit(exp2, visit, accept)
      } if (accept(exp3)) {
        visitExpr(exp3, visit, accept)
      }
    // and so forth
}
```

We will also need visitors for almost everything in the root:

```scala
case class Root(modules: Map[Symbol.ModuleSym, List[Symbol]],
                  traits: Map[Symbol.TraitSym, Trait],
                  instances: Map[Symbol.TraitSym, List[Instance]],
                  sigs: Map[Symbol.SigSym, Sig],
                  defs: Map[Symbol.DefnSym, Def],
                  enums: Map[Symbol.EnumSym, Enum],
                  structs: Map[Symbol.StructSym, Struct],
                  restrictableEnums: Map[Symbol.RestrictableEnumSym, RestrictableEnum],
                  effects: Map[Symbol.EffectSym, Effect],
                  typeAliases: Map[Symbol.TypeAliasSym, TypeAlias],
                  uses: Map[Symbol.ModuleSym, List[Ast.UseOrImport]],
                  entryPoint: Option[Symbol.DefnSym],
                  reachable: Set[Symbol.DefnSym],
                  sources: Map[Source, SourceLocation],
                  traitEnv: Map[Symbol.TraitSym, Ast.TraitContext],
                  eqEnv: ListMap[Symbol.AssocTypeSym, Ast.AssocTypeDef],
                  names: MultiMap[List[String], String],
                  precedenceGraph: LabelledPrecedenceGraph)
```

We can start with visitDef and visitExpr.

We will also need functions like:

```scala
def inside(loc1: SourceLocation, loc2: SourceLocation): Boolean = ...
def inside(uri: String, pos: Position, loc: SourceLocation): Boolean = ...
```

With all of this, we should be able to replace:

```scala
    index.query(uri, pos) match {
      case None => mkNotFound(uri, pos)
      case Some(entity) => hoverEntity(entity, uri, pos)
    }
```

with something like:

```scala
visitRoot(root, hoverEntity, expr => inside(uri, pos, expr.loc))
```

**Comment by magnus-madsen** [comment]
@LoZander CC

**Comment by LoZander** [comment]
Im at a point where it feels like most of the main structure is there. A problem I've run into is when we're in `visitDef` and we need to visit the expression in it. We need to give `visitExpr` some visit function, but `visitDef` doesn't know of all the top level visit functions, only it's own `Def => Unit` function. This is a general issue with the current signatures and the fact that we have nested structures of changing types. At the top level, we need a list of `_ => Unit` visit functions for all the kinds of elements we might visit. The most obvious solution is to just always carry that list of functions instead of only the function for the current type of element.

For instance, right now we have `visitDef(defn: Def, visit: Defn => Unit, accept: SourceLocation => Boolean)` but this change would make it `visitDef(defn: Def, visits: Visits, accept: SourceLocation => Boolean` where `Visits` is some kind of abstraction that holds all the visit functions.

 Thoughts? Maybe there's a better way of doing it?

**Comment by magnus-madsen** [comment]
> For instance, right now we have visitDef(defn: Def, visit: Defn => Unit, accept: SourceLocation => Boolean) but this change would make it visitDef(defn: Def, visits: Visits, accept: SourceLocation => Boolean where Visits is some kind of abstraction that holds all the visit functions.

Yes, but before you introduce some new abstraction, just add the extra arguments.

**Comment by LoZander** [comment]
> > For instance, right now we have visitDef(defn: Def, visit: Defn => Unit, accept: SourceLocation => Boolean) but this change would make it visitDef(defn: Def, visits: Visits, accept: SourceLocation => Boolean where Visits is some kind of abstraction that holds all the visit functions.
> 
> Yes, but before you introduce some new abstraction, just add the extra arguments.

Alright. It'll be pretty combersome signatures, but that's probably fine temporarily :)

**Comment by magnus-madsen** [comment]
I just think it is important to get the code "filled in" and working -- so we can see the structure.

**Comment by magnus-madsen** [comment]
Recall that refactoring comes after something works.

**Comment by LoZander** [comment]
Yes, I agree with that. Currently I have a lot of holes to fill in, but as soon as I've updated the signatures, I think it'll start coming together fast

**Comment by magnus-madsen** [comment]
> Yes, I agree with that. Currently I have a lot of holes to fill in, but as soon as I've updated the signatures, I think it'll start coming together fast

You could focus on expressions and everything under there. That way you can get it to work with HoverProvider.

**Comment by LoZander** [comment]
> > Yes, I agree with that. Currently I have a lot of holes to fill in, but as soon as I've updated the signatures, I think it'll start coming together fast
> 
> You could focus on expressions and everything under there. That way you can get it to work with HoverProvider.

Yeah, I will. Though in theory the hover provider should eventually work for more than expressions as well, right?

**Comment by LoZander** [comment]
I can see that in it's current state, it does not go beyond expressions and types

**Comment by magnus-madsen** [comment]
When you are done, it should work for everything you can hover.

**Comment by LoZander** [comment]
The documentation for Positions used in the LSP is that it's zero indexed on both line and column (characters). This matches the LSP specification ofc. But in practice, the positions given by `LanguageServer.scala` seems to actually be -indexed, based on simply printing the position as I hover over different places in VSCode. Presumably its the same for the other providers. This is very strange. 

I think I found the culprit. When parsing JSON into positions (main/src/ca/uwaterloo/flix/api/lsp/Position.scala, the function at line 44), 1 is added to the line number and character number. A comment says its to account for Flix using 1-indexing internally. This however conflicts with the documentation for Positions and as well as the LSP specification. There are also other functions in the same module that do not expect the Position to be 1 indexed, fx `fromBegin` at line 32.

This puts me in an awkward position: on one hand, it makes sense to change this so that Position is zero indexed just like the LSP specification, but this would very likely break a lot of code. On the other hand, I could change the documentation for Position to reflect that it is 1-indexed, but then Position no longer matches the LSP specification.

Thoughts?

**Comment by LoZander** [comment]
What I could do, to not have to handle this discrepency right now, would be to change the docs to reflect that its 1-indexed and then leave a TODO comment, noting that it should be refactored to reflect the LSP spec. That way, at least it's communicated that it's 1-indexed and that this should be fixed eventually, and I won't have to deal with a great refactoring right now.

**Comment by LoZander** [comment]
then we could make that refactoring a different issue

**Comment by LoZander** [comment]
It seems that SourceLocations for number literals for some reason include the following symbol. For instance `2+3`, the location for `2` seems to actually include `+`. This is *not* the case for `"a"+"b"`, where the location for `"a"` does *not* include `+`.

I don't know the origin of this issue, but I reckon it might be something in the parser phase. Experimentation shows me that this issue only happens if it's a number literal with no explicit number type (fx no `f32` etc.), so it might have to do with the case at line 970 in the parser.

It's a kinda small issue, but it can cause some issues, especially with my work on the hover provider and maybe my work on the visitor based search in general. fx for `2+3` the location for 2 entirely contains the location for +.

**Comment by magnus-madsen** [comment]
Did you look into how the +1/-1 issue with source locations is handled in the rest of the LSP codebase?

**Comment by magnus-madsen** [comment]
> It seems that SourceLocations for number literals for some reason include the following symbol. For instance 2+3, the location for 2 seems to actually include +. This is not the case for "a"+"b", where the location for "a" does not include +.

The symbol + is rewritten to Add.add. You may want to find where that happens and see how the source locations are treated.

**Comment by LoZander** [comment]
Should the visitor also visit symbols, or should it stop at visiting the node that contains the symbol? There are some ast nodes that denote uses of symbols, ofc. the question is if the symbols themselves should be visited

**Comment by magnus-madsen** [comment]
> Should the visitor also visit symbols, or should it stop at visiting the node that contains the symbol? There are some ast nodes that denote uses of symbols, ofc. the question is if the symbols themselves should also be visited. I used to think no, but thinking about it further, I'm starting to think yes, because the visitor will need to be used for things like renaming, meaning we have to use it to find occurances of symbols. Ofc. that could be done by defining a consumer for each situation that _could_ contain the symbol, but that seems like a hack a use site of the visitor should not have to make

I don't think visiting the symbols themselves is useful. The symbols only contain a source location, but that is already available from visiting the declarations. So in short, no.

But I would have visitors for SymUse.

**Comment by LoZander** [comment]
What about for stuffl like renaming where you want to specifically find occurances of the symbols themselves? Is it still better to just do that using consumer functions over the different contexts that the symbol can occur in?

**Comment by magnus-madsen** [comment]
> What about for stuffl like renaming where you want to specifically find occurances of the symbols themselves? Is it still better to just do that using consumer functions over the different contexts that the symbol can occur in? Because this would be a case where it might be easier if the symbols are themselves also visited, no?

Visiting the symbol does not allow you to know where it occurs. 

You need to visit the expression and/or the UseSym thing.

For example, visiting Symbol.DefnSym tells you nothing about where it occurs.

**Comment by LoZander** [comment]
> > What about for stuffl like renaming where you want to specifically find occurances of the symbols themselves? Is it still better to just do that using consumer functions over the different contexts that the symbol can occur in? Because this would be a case where it might be easier if the symbols are themselves also visited, no?
> 
> Visiting the symbol does not allow you to know where it occurs.
> 
> You need to visit the expression and/or the UseSym thing.
> 
> For example, visiting Symbol.DefnSym tells you nothing about where it occurs.

Visiting the symbols does allow you to know the sourcelocation, but I suppose that's not that useful by itself. I suppose, only the context they occur in is interesting, like for instance the expression a symbol occurs in

**Comment by magnus-madsen** [comment]
> > > What about for stuffl like renaming where you want to specifically find occurances of the symbols themselves? Is it still better to just do that using consumer functions over the different contexts that the symbol can occur in? Because this would be a case where it might be easier if the symbols are themselves also visited, no?
> > 
> > 
> > Visiting the symbol does not allow you to know where it occurs.
> > You need to visit the expression and/or the UseSym thing.
> > For example, visiting Symbol.DefnSym tells you nothing about where it occurs.
> 
> Visiting the symbols does allow you to know the sourcelocation, but I suppose that's not that useful by itself. I suppose, only the context they occur in is interesting, like for instance the expression a symbol occurs in

But you can get that exact information from visiting the declaration.

**Comment by LoZander** [comment]
> > > > What about for stuffl like renaming where you want to specifically find occurances of the symbols themselves? Is it still better to just do that using consumer functions over the different contexts that the symbol can occur in? Because this would be a case where it might be easier if the symbols are themselves also visited, no?
> > > 
> > > 
> > > Visiting the symbol does not allow you to know where it occurs.
> > > You need to visit the expression and/or the UseSym thing.
> > > For example, visiting Symbol.DefnSym tells you nothing about where it occurs.
> > 
> > 
> > Visiting the symbols does allow you to know the sourcelocation, but I suppose that's not that useful by itself. I suppose, only the context they occur in is interesting, like for instance the expression a symbol occurs in
> 
> But you can get that exact information from visiting the declaration.

yep, true

**Comment by LoZander** [comment]
Most of the visitor is done now. There are some caveats and surely some refining to be done, but I think we're most of the way there

**Comment by LoZander** [comment]
So now Ill focus on finishing the hover provider

**Comment by LoZander** [comment]
Im kinda worried about the performance tbh. It's not too bad, but dragging my mouse across different things, there is a noticable delay before hover information shows. I'm not sure how it compares to before though. What do you think?

**Comment by magnus-madsen** [comment]
> Im kinda worried about the performance tbh. It's not too bad, but dragging my mouse across different things, there is a noticable delay before hover information shows. I'm not sure how it compares to before though. What do you think?

On my mac its fine, but we can look into it. I already have some ideas.

**Comment by magnus-madsen** [comment]
But don't worry, we also save some time once the indexer is disabled.

**Comment by LoZander** [comment]
Oh, I figured the indexer wouldn't be invoked upon a hover, but perhaps it's always invoked even if the index is not used?

**Comment by LoZander** [comment]
I thought it would only be invoked if you made a change to the source code, actually

**Comment by magnus-madsen** [comment]
(It might be running in the background)

**Comment by LoZander** [comment]
oh, I see

**Comment by magnus-madsen** [comment]
Fixed in master.
