### ISSUE TITLE
Move Consumer and Acceptor to their own source files

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8937]

**Comment by magnus-madsen** [comment]
@LoZander CC

**Comment by LoZander** [comment]
I'm looking at doing this and I'm about to move the `InsideAcceptor` into its own file, and it's making me think about the `inside` function. Really, it should be in some other module somewhere. It's not just used by the acceptor at this point either. It's used and useful beyond this. I just don't know where the function should be. I almost wanna put it in a 

It doesn't make sense to put it in `Position.scala`, since it's not really asking about positions, but pairs of positions and URIs. If we change the function a bit to operate on LSP Locations instead of SourceLocations, then we could put it in Location.scala as `Location.contains(uri: String, pos: Position)`. But then that would mean whenever `InsideAcceptor.accept` is invoked, it has to convert the SourceLocation to an LSP Location to then use `Location.contains`, which is kinda awkward.

I could also just make a Inside.scala module, I suppose. It just feels a bit awkward as well.

For now I'll just leave it inside the `Visitor` module. But let me know what yall think is best.

**Comment by magnus-madsen** [comment]
I think its good enough for now.
