### ISSUE TITLE
Recoverable lookupTrait

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9194]
What are the consequences if `lookupTrait` returns an Option?

**Comment by jaschdoc** [comment]
Two functions depend on `lookupTrait`:
- `resolveDerivation` - related to automatic derivations on (restrictable) enums
- `resolveTraitConstraint` - related to instances and functions (spec)

After the refactor, `lookupTrait` can only return `None` if the trait does not exist. Otherwise, it returns `Some(trait)`, possibly adding an error to the shared context.

For `resolveDerivation` we can simply propagate the `Option` because if the trait does not exist we should not try to generate something that does not exist that could replace the error. Additionally, `lookupTrait` will have reported an error. Thus, at the enum declaration level we just treat this as "this is not a derivation so skip this". Otherwsie, we have a valid trait and all is well (except it may be inaccessible but that error will be reported by `lookupTrait`). In short: propagate the option, generate derivation if it exists, otherwise skip.

For `resolveTraitConstraint` we also propagate the `Option` by returning `Validation[Option[TraitConstraint], ResolutionError]`. Again, if it is `None`, `lookupTrait` will have reported an error. If the body of the instance or def / sig uses a function defined on the trait that we did not find, it simply reports that function as being undefined in addition to the trait lookup failure. That seems like okay behavior: if we try to use `a` defined on `x`  and `x` does not exist then `a` does not exist either. The `Some` case is the happy path (except for accessibility which should be reported by `lookupTrait`). Thus, in `resolveSpec` and `resolveInstance` we only include the trait constraints that are `Some(trait)`.

**Comment by jaschdoc** [comment]
Another option is to add a `Declaration.Error` AST node but that seems like a much bigger change.
