### ISSUE TITLE
Types in lower case does not work in methods

### ISSUE THREAD

**Issue by johandegn** [flix/flix#928]
Using types as `int` or `str`, with  lower case first letters, work when working on the 'top level' where no methods are introduced.  The same types, declared with lower case first letters, can't be used in methods, where you apparently have to use capital starting letters.
While the this code works:
```
rel A(a: Int)
def main(): #{A} =
    #{A(1). A(2).}
```
this one, whit a small 'i', does not:
```
rel A(a: int)
def main(): #{A} =
    #{A(1). A(2).}
```
It gives the following resolution error:
```
>> Non-relation, non-lattice type '20 => Relation(A)[(20)]'.

9 | def main(): #{A} =
                ^^^^
                non-relation, non-lattice type.



Compilation failed with 1 error(s).
```
The same thing goes for `str` instead of `Str`, and i would assume other types too.

**Comment by magnus-madsen** [comment]
In Flix lowercase names are variables. Both for terms and types.

Thus:

```
def f(x: Int): Int = x
```

here the variable `x` has type `Int`. But here:

```
def f[a](x: a): a = x
```

the variable `x` is polymorphic (generic) and has type `a`.

Since Flix supports type parameter elision, the above can also be written just as:

```
def f(x: a): a = x
```

Of course type variables do not have to be just a single letter, so:

```
def f(x: int): int = x
```

is actually a polymorphic function where `int` is just a rather unfortunately chosen type parameter name!

In this case, the compilation error showing the problem is a bit obscure, but not something that can be fixed before we have kinds.
