### ISSUE TITLE
Autocomplete of `println` broke

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9375]
We have a function called `println` that is defined in the root module, i.e. it does not have to be use'd to be, well, used.

But currently we get this behavior:

![image](https://github.com/user-attachments/assets/79624656-01d6-4ff6-a5f9-a690be3e7502)

![image](https://github.com/user-attachments/assets/1d0797a1-40b1-44ea-b2bb-1d97899a269b)

**Comment by magnus-madsen** [comment]
@stormckey This is a regression so would be good to get fixed soon. (I am not entirely sure what the problem is though. I suppose the old DefCompleter used to offer `println` and now that is gone or ?).

**Comment by stormckey** [comment]
> @stormckey This is a regression so would be good to get fixed soon. (I am not entirely sure what the problem is though. I suppose the old DefCompleter used to offer `println` and now that is gone or ?).

Oh that's quite annoying :(

Yeah, DefCompleter is banned in this case to avoid providing two duplicated completions for println. What we need to do here is to fix AutoUseCompleter and LocalScopeCompleter, not to use println in this case.

I think the problem is that `println` is not in LocalScope but in root.defs, so currently, we treat it as something needed to be used. We may need to also treat things in root module as if they are in localscope to fix this problem.

**Comment by stormckey** [comment]
So I think defs in `root.defs` whose namespace is empty are those in the root module? So we just need to take them into consideration?

**Comment by magnus-madsen** [comment]
> So I think defs in `root.defs` whose namespace is empty are those in the root module? So we just need to take them into consideration?

Yes that is correct.
