### ISSUE TITLE
Possible update for fuzzyMatch

### ISSUE THREAD

**Issue by stormckey** [flix/flix#9572]
It would be good if typing "A.foo" matches "A.B.foo", which means the user can skip some namespace in the middle.

But now the fuzzyMatch is designed to work just for unqualified name, not qualified name. If we directly apply `fuzzyMatch` to the example above(split before every capital letter), it will check ["A.foo"] against ["A.", "B.foo"] and the match will fail.

An easy way to make `fuzzyMatch` work for both qualified and unqualified name is to split before both capital letters and ".". Then for the case above, it will check ["A", ".foo"] against ["A", ".", "B", ".foo"]. The [".", "B"] will be skipped and the check will pass.

**Comment by JonathanStarup** [comment]
I think that's a good idea. I think in general, all autocomplete should work on a QName format, so qualified/unqualified shouldn't use different code. like with autocomplete I want `f` to complete to `A.f` but i could also want `A.f` to complete to `B.A.f`. This is the same "treat all names as qnames" kind of idea

**Comment by magnus-madsen** [comment]
> It would be good if typing "A.foo" matches "A.B.foo", which means the user can skip some namespace in the middle.

I am not convinced this is actually useful. Sometimes less is more, i.e. not giving too many suggestions. 

If you want A.B.foo you can already access it by typing either `foo` or `A.B.f`

**Comment by stormckey** [comment]
Ok. We could argue that most of the time people are just `use` the parent module of something, and then qualify that thing with the parent module.

In the case above, one may `use Jonathan.Module.Something` and then just use `Something.empty` anywhere he need it.

For that use case, we could adopt a stricter matching, where we require the leading namespace to be identical while perform fuzzyMatch just over the last ident. In this case we don't need to change fuzzyMatch.

The downside of this method is that when someone, for some reason, wants to type `Jonathan.Module.Something.empty`, he will have to go through every namespace along the way.

**Comment by magnus-madsen** [comment]
I think you are overthinking it.

We used to have something like this. Our first iteration of autocomplete **would just return everything** and let the user + VSCode sort it out. This turned out to be annoying. Too much information and too many suggestions are also a problem.

What is nice about our current approach is that when you type `Qux.Foo.` its tells you what is inside `Foo`. That is a good thing. 

You can also type `babbleblab` and it will search everywhere and help you with the import/use.

But let us not over-complicate - both for the user and for ourselves - by trying to support everything.

Lets focus on what we have:

- Completion of things in scope (what everyone expects)
- Completion of "things that are inside things" (e.g. I type `Qux.Foo.` and I learn what is inside `Foo`).
- Auto import/use completions where I type `babbleblab` and I am offered suggestions of where to import/use it from.

**Comment by magnus-madsen** [comment]
When we have that and everything works well then we can discuss how to extend and iterate.
