### ISSUE TITLE
Debate: What are the most important libraries for a new language?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#973]
What should we focus on as the absolutely essential libraries for Flix?

Suggestions:

- collections and core data types (partially done)
- File IO?
- Network?
- Commandline parser?
- Other types of parsers?
- Http client/server?

Other ideas?

**Comment by stephentetley** [comment]
A comprehesive File IO library would be good. I've just started looking at this myself.

Date and Time would be good too. 

I've a parser combinator library in progress that aims to be good for parsing "text data". In the Haskell world the related parser combinators would be Attoparsec and ReadP. Parsec can of course be used for text data but it's found use-case was parsing source code - so some things it does a "text data" parser doesn't need to do simplifying the implementation. 

I've also a "fact importer" in progress to load facts from Csv, MySQL and flat text files. I was trying to get it to work with the parser combinators this week but there were problems. This is why I've started to look at file IO.

Finally, I've a pretty printer in progress which might be useful at some point for the Flix shell - in principle data types could be shown with nice formatting / nesting.

A streaming library that can interface with Java's Iterator would be good. 

Exporting Datalog answer sets to Csv would be very useful. Maybe this should be a compiler builtin (like the special tabular printing for answers is currently) or maybe it should be a library. Exporting to other formats (MySQL, HTML, ...) seems more open ended so should be done via libraries rather than builtins.

**Comment by magnus-madsen** [comment]
Thank you for the feedback Stephen.

I was thinking of getting some students to work a bit on an I/O library -- but we should be sure to deconflict, so there is no duplication of effort.

The parser library and import/export of facts sounds very interesting! We recently added a "fold" operation on constraint sets. The syntax is not great, but it can be seen here:

https://github.com/flix/actors/blob/master/src/main/actor/ActorSystem.flix#L151

and here:

https://github.com/flix/flix/blob/master/main/test/ca/uwaterloo/flix/language/feature/Test.Expression.FixpointFold.flix

> A streaming library that can interface with Java's Iterator would be good.

Could you expand on this? Do you mean some kind of interop with Iterator from Java? Or do you mean the Stream stuff or something third?

> Exporting Datalog answer sets to Csv would be very useful.

Indeed! The fold operation can be used here, but not in a generic way. I think we need a more expressive type system or possibly macros to allow you to write a single implementation of a CSV exporter.

**Comment by magnus-madsen** [comment]
I wanted to survey what packages are popular for other languages.

Here is JavaScript: Most dependent on NPM packages:

- lodash - standard library
- chalk - terminal coloring
- request - http client
- commander - command line parsing
- react
- debug
- async
- fs-extra
- moment - date utilities

Other notable packages:
- glob - globbing utilities
- inquirer - a request/response library for terminal apps
- uuid
- rimraf - recursive delete
- mkdirp - recursive create directory
- dotenv - load configuration from file
- winston - logging library with transport
- ora - terminal spinner
- ms - time format converter
- jest - testing framework

**Comment by magnus-madsen** [comment]
Python (only including things not already covered that look interesting):

- matplotlib - plot graphs
- psutil - process monitoring
- chardet - character encoding detector
- simplejson
- toml

**Comment by magnus-madsen** [comment]
Interesting Clojure packages:
- environ - lib for accessing environmental variables.
- me.raynes/fs - file utils
- gloss - binary format lib

**Comment by stephentetley** [comment]
I've got reading env vars working in my collection of `System` modules. They're a bit under-cooked at the moment, but I'll hopefully improve them over the summer.

Some status on what I've been working on:

A lot of the code is written for the Time library which wraps Java's new time library - it needs documentation and tests.

Similarly the Regex library has much of the code written but needs a bit of polish for the API plus documentation and tests.

I've written a Pull Stream module that can connect to Java's iterators. It would be hard to connect to Java's streams directly, but any stream provides an iterator.

I've just improved FactIO (loading and exporting Datalog facts) so it can better handle "real world" Csv (e.g. with or without headers, handling different quote and separator chars should be next...). Also reading from flat files was recently reworked and is now usable for "real world" tasks, previously it had just been a toy. 

I've ported QuickCheck from Haskell, though it is basically a toy at the moment.

Pretty Print combinators need documentation and tests but otherwise are working well.

Using the Pretty Print combinators, I've written a combinator library to build HTML documents. Needs quite a bit of work.

Parser combinators have been a problem. Normal recursive parser combinators seem prohibitively slow at the character level and I think they really need to be using Java loops directly. I've tried with `java.util.Scanner` but it doesn't really have the right interface, I've also got a experiment that wraps Java stubs that do use loops for character scanning but it's rather messy and I'm not so satisfied with it.

**Comment by magnus-madsen** [comment]
> Parser combinators have been a problem. Normal recursive parser combinators seem prohibitively slow at the character level and I think they really need to be using Java loops directly.

If the function is tail recursive (directly call itself) then it becomes just a simple loop in the bytecode. Might still be too slow though.

**Comment by magnus-madsen** [comment]
But all of this sounds amazing. Looking forward to it :)

I am hoping to have some time to work on other modules over the summer.

**Comment by stephentetley** [comment]
Thanks Magnus.

I think the last "all Flix" version I had of the Parser monad wasn't written in CPS but all the recursive combinators were. I was having problems getting a CPS parser monad to type without existential types, I've now worked out a CPS representation that doesn't need existentials so I'll remake the library using that. 

If character level parsers are still too slow I'll try to encode enough useful ones with regex matching where I can lean on Java through the Flix regex library I'm working on, but I don't need to be writing and wrapping ad hoc Java character readers.
